### ISSUE TITLE
Openssl vulnerability in distroless/nodejs:14

### ISSUE THREAD

**Issue by talentedandrew** [GoogleContainerTools/distroless#1002]
I'm using `distroless/nodejs:14` in my docker file. The Snyk scanner shows a [Vulnerability issue](https://security.snyk.io/vuln/SNYK-DEBIAN10-OPENSSL-2426310) in my docker image which uses `distroless/nodejs:14`.  The issue is arising from the `openssl` package for versions <1.1.1d-0+deb10u8. Is there any fix available for this issue?

```
FROM node:14 as build

COPY .XXXX /XXXX/.XXXX
WORKDIR /XXXX/XXXX
COPY XXXX XXXX
RUN XXXX

COPY . .

FROM gcr.io/distroless/nodejs:14

EXPOSE XXXX
ENV NODE_ENV production
COPY --from=build /XXXX/XXXX/ /XXXX
WORKDIR /XXXX
CMD ["XXXX"]

```

**Comment by loosebazooka** [comment]
The fixes are not available in debian yet. But it is weird that the scanner is showing that you need `+deb10u8` because it thinks you're image is based on debian10 (it should be debian11), have you rebuilt recently?
