### ISSUE TITLE
Java-17:latest Image based on Oracle OS instead of Debian

### ISSUE THREAD

**Issue by BenedictQ** [GoogleContainerTools/distroless#1028]
I was running an image built on the Distroless java-17:latest image as a root image through a vulnerability scanner Apr 19, 2022 11:53am.

The scan detected Oracle OS version 8 as the OS for that image. The documentation for this repo suggests on Debian is used for images. Can you explain how this happened? e.g. was this a temporary mistake in a version of that image, or have you been experimenting with Oracle OS and accidentally pushed it?

Note that this doesn't happen anymore on the latest image (sha256:d4f79d7bfa331a02718599f3f01cc6c8532f718d66c219fe7e23d80021bf59b5). Unfortunately I don't have an SHA reference for the scan where it happened.

P.S. The vulnerability scan found only 4 medium vulnerabilities in Oracle OS, whereas the java-17-debian11 image has several high vulnerabilities.

**Comment by loosebazooka** [comment]
Pretty hard for me to debug this. As for the vulns on the debian image -- see #1022 for updates on the most critical one.
