### ISSUE TITLE
OpenJDK 11.0.15 released on 4/19, need update of distroless-java11 images

### ISSUE THREAD

**Issue by ajay-aggarwal** [GoogleContainerTools/distroless#1029]
Hello, OpenJDK 11.0.15 was released on 4/19. I was curious what is the cadence for releasing updates to corresponding distroless java11 images (gcr.io/distroless/java11-debian11). The latest gcr.io/distroless/java11-debian11 image seems little old and on 11.0.14 for java. Thanks.

**Comment by loosebazooka** [comment]
based on debian: see https://packages.debian.org/bullseye/openjdk-11-jdk

**Comment by ajay-aggarwal** [comment]
Hello - it is now in bullseye (security)
https://security-tracker.debian.org/tracker/source-package/openjdk-11

**Comment by loosebazooka** [comment]
yeah just submitted the update: https://github.com/GoogleContainerTools/distroless/pull/1034

**Comment by ajay-aggarwal** [comment]
thanks!
