### ISSUE TITLE
Documentation for Node.js: 18 is now latest

### ISSUE THREAD

**Issue by luc122c** [GoogleContainerTools/distroless#1035]
Hi there, the [ReadMe for Node.js](https://github.com/GoogleContainerTools/distroless/blob/f0e17e79c46735364e4fd77ee4f0102a3a73ccce/nodejs/README.md) says that `latest` maps to `16` to mirror the [official node image](https://hub.docker.com/_/node). `18` is now `latest` so distroless should update its docs and tagging to reflect this.

**Comment by luc122c** [comment]
It looks like `18` is already being tagged as `latest`, so it should just be a docs update. I'll work on a PR.
![Screenshot 2022-05-09 at 20 51 21](https://user-images.githubusercontent.com/7257092/167486713-9e2baffc-23f1-44e6-a580-22530f601832.png)
[REFERENCE](https://console.cloud.google.com/gcr/images/distroless/global/nodejs@sha256:d47624eb8083d7a0e8897cbdaf92aa71b71828cfd92b3b3dfc5567e08ad8a392/details)

**Comment by loosebazooka** [comment]
Yeah sorry, I think we missed that in the upgrade. I'll go change it now.

**Comment by luc122c** [comment]
Thanks @loosebazooka I've submitted a PR and signed the CLA.
