### ISSUE TITLE
gcr.io/distroless/cc:debug fails with Rust app: line 1: syntax error: unexpected ")"

### ISSUE THREAD

**Issue by lcmgh** [GoogleContainerTools/distroless#1040]
```Dockerfile
# You can override this `--build-arg BASE_IMAGE=...` to use different
# version of Rust or OpenSSL.
ARG BASE_IMAGE=rust

# docker build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy -t exporter_distroless .
# Our first FROM statement declares the build environment.
FROM ${BASE_IMAGE} AS builder
WORKDIR /build
COPY . /build

# Create empty app dirs that will be copied to distroless
RUN mkdir -p /app/config

# Test
RUN cargo test --release

# Build our application.
RUN cargo build --release

FROM gcr.io/distroless/cc:debug
USER nonroot

# Place for config files
COPY --from=builder --chown=nonroot:nonroot /app /
COPY --from=builder --chown=nonroot:nonroot /build/target/release/my-app /app/
WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["/app/my-app"]

```
Building the Docker file locally on Windows 10 leads to no problems. Building the Docker image on my CICD env with `BMW_Ubuntu_20.04_Server` and running it on Kubernetes makes the Container fail on startup with: 
`/app/my-app: line 1: syntax error: unexpected ")"`

I can reproduce the error message by executing `sh /app/my-app`. Just running `/app/my-app` as in the entrypoint command works fine.

**Comment by loosebazooka** [comment]
I'm not sure exactly what to do with this. I assume this is an error from busy box, but why would you run your rust app with `sh`?

**Comment by lcmgh** [comment]
> I'm not sure exactly what to do with this. I assume this is an error from busy box, but why would you run your rust app with `sh`?

I don't run the app with `sh`, that was just for debugging purpose with the outcome that it produces the same error message as when I run the Dockerfile (as posted above) on Kubernetes.

**Comment by loosebazooka** [comment]
You're using the shell style entrypoint for docker, see: https://docs.docker.com/engine/reference/builder/#entrypoint

What you really want is the exec type: `ENTRYPOINT /app/my-app`

**Comment by lcmgh** [comment]
You mean I am using the exec form?
exec form: `ENTRYPOINT ["executable", "param1", "param2"]` 
shell form: ENTRYPOINT command param1 param2

Distroless doc says I must use exec form
https://github.com/GoogleContainerTools/distroless#entrypoints

**Comment by loosebazooka** [comment]
Oh whoops.

**Comment by lcmgh** [comment]
Yes I can send you a download link by mail if that is okay for you.

**Comment by loosebazooka** [comment]
Fundamentally this seems like a configuration issue. If you can isolate it to distroless that would be a good step before I spend some time on this.

1. try with a different base image
2. inspect the container config (docker inspect)
3. did you say it runs with docker run?

**Comment by lcmgh** [comment]
> 3. did you say it runs with docker run?

No, see:
```
$ docker run -it <internal-registry/image>
/app/my-app: line 1: syntax error: unexpected ")"
```
That at least tells me it is probably not related to my local Win10 or remote Kubernetes environment.

What works:
```
$ docker run -it --entrypoint=sh <internal-registry/image> -i
/app $ ./my-app
```

**Comment by lcmgh** [comment]
`$ docker run --entrypoint=/app/myapp <internal-registry/image>` starts the app as expected.

**Comment by loosebazooka** [comment]
Unfortunately this doesn't appear to be a distroless problem. Something about your config is having your code run as shell. Check your configs/build to see what is going on. try `docker inspect`

**Comment by lcmgh** [comment]
I switched to debug to analyze why the container crashed on startup.

**Comment by lcmgh** [comment]
I was able to get it working by switching back to the non-debug version `gcr.io/distroless/cc:latest`. I initially used `:debug` to track another issue I had during startup.

**Comment by lcmgh** [comment]
Why is it closed? The issue still appears with :debug version.

**Comment by loosebazooka** [comment]
Well it seemed like your core issue was solved, and you didn't provide any update to the other questions asked for debugging in https://github.com/GoogleContainerTools/distroless/issues/1040#issuecomment-1123858293.

Fundamentally we don't necessarily have the time to debug everyone's runtime issues. If there is a core problem with distroless we will fix, but solving for problems like this, related generically to containers, are better suited for community debugging on stackoverflow.

**Comment by lcmgh** [comment]
When I have time I'll try to reproduce with your rust example.
