### ISSUE TITLE
glibc version issue with binaries compiled against Ubuntu 22.04

### ISSUE THREAD

**Issue by pdeva** [GoogleContainerTools/distroless#1054]
**Describe the bug**

Seeing this error:

```
/app: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app)
/app: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app)
```

**To Reproduce**
Compiling a Go program on Ubuntu 22.04 LTS and running it on distroless:base results in the above error.

**Expected behavior**
Go program should run without errors.

**Console Output**
If applicable, add information from your container run

**Additional context**

**Comment by loosebazooka** [comment]
Distroless uses debian and ships with glibc 2.28 ... So you have to compile against a version compatible with that for it work. Or compile with cgo disabled?

**Comment by pdeva** [comment]
yes so the bug is opened so that distroless would upgrade its glibc version

**Comment by loosebazooka** [comment]
No we have no mechanism for providing out of band updates to glibc. This is what debian bullseye provides and we track them.
