### ISSUE TITLE
Standardise naming of nodejs images

### ISSUE THREAD

**Issue by omBratteng** [GoogleContainerTools/distroless#1084]
To not fill the PR with non-related discussion, re: https://github.com/GoogleContainerTools/distroless/pull/1083#issuecomment-1184551777, I open this issue as a tracker to discuss standardising nodejs images.

> I think it might be time to standardize the naming of nodejs images to be similar to the others.
> ```
> nodejs<version>-debian<version>:{root, nonroot, debug, debug-nonroot}
> ```
> We can leave the old naming as legacy for now and deprecate those in ~6 months ?

**Comment by omBratteng** [comment]
Examples
- nodejs18-debian11:latest
- nodejs16-debian11:debug-nonroot

**Comment by omBratteng** [comment]
Would it be optional to drop the `-debian<version>` suffix, so it would always mean the latest distro version?
Like `nodejs18:latest` would mean `nodejs18-debian11:latest`.

**Comment by omBratteng** [comment]
In your initial comment, you wrote `root`. Would that be `latest`? Or do both? `latest` and `root` tag.

**Comment by loosebazooka** [comment]
right right, another slip. latest is correct.

**Comment by loosebazooka** [comment]
so 
```
nodejs<version>-debian<version>:{latest, nonroot, debug, debug-nonroot}
```

**Comment by omBratteng** [comment]
Awesome. I'll take a look at it.

**Comment by omBratteng** [comment]
I've opened a draft PR #1086.
What's the reason that node14 isn't built with multi-arch? There are arm64 versions of it.

**Comment by loosebazooka** [comment]
Probably just history. Change to what you think makes sense
