### ISSUE TITLE
Feature Request: Anaconda Python 3 

### ISSUE THREAD

**Issue by FuriouslyCurious** [GoogleContainerTools/distroless#109]
A distroless version of Anaconda Python 3 will make life much easier for many data science applications!

**Comment by Yongjin0919** [comment]
Theif

**Comment by lathama** [comment]
@FuriouslyCurious in the case you have not tried Multistage then have a look at an example at https://github.com/stlpython/Meetings/blob/master/2018-05-01/introduction/Dockerfile where you could convert it to install and use the Anaconda tool the same as pip.

**Comment by lathama** [comment]
@FuriouslyCurious is this issue still important to you? Have you tried to use multi-stage? If it is not important can you please close the issue.
