### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Immortalin** [GoogleContainerTools/distroless#111]
Having a python 3 distro would make many machine learning tasks easier!

**Comment by mattmoor** [comment]
See also: https://github.com/GoogleCloudPlatform/distroless/issues/109

Are you also interested in Anaconda?

**Comment by Yongjin0919** [comment]
How can i send report?

**Comment by lathama** [comment]
I am using the Python3 Distroless image so it exists. Can we close this?

**Comment by raliste** [comment]
Any plans to update to Python 3.6 ? A lot of packages (such as PyCrypto) already stopped giving support for older versions of py3.

**Comment by lathama** [comment]
Note that Debian Stretch is the base and currently only has Python 3.5 but you could update https://github.com/GoogleContainerTools/distroless/blob/master/WORKSPACE#L24-L47 and build with Sid or Buster if you want Python 3.6

**Comment by lathama** [comment]
@dlorenc can you close, this is out dated
