### ISSUE TITLE
Networking broken when using dind-rootless

### ISSUE THREAD

**Issue by milero** [GoogleContainerTools/distroless#1120]
**Describe the bug**
Running wget or ping on [github.com](https://github.com) returns _bad address_ error.

**To Reproduce**
When using this image with dind-rootless, domains like [github.com](https://github.com) or [bitpoke.io](https://bitpoke.io) are not resolved properly, whereas [google.com](https://google.com) does resolve.

**Expected behavior**
All valid domains should resolve properly.

**Console Output**
```
#4 0.522 + wget -O /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
#4 0.523 wget: bad address 'github.com'
```

**Additional context**
Might be related to https://gitlab.alpinelinux.org/alpine/aports/-/issues/11879 and https://github.com/alpinelinux/docker-alpine/issues/155 and might be caused by this commit: 3f935302f43896bef7240b9bd80a8c6f4c5cac4b

**Comment by loosebazooka** [comment]
Distroless doesn't have `wget` or `ping`?

**Comment by loosebazooka** [comment]
What image are you using?

**Comment by milero** [comment]
It has them on debug non-root tags. We are using `base-debian11:debug-nonroot`.

**Comment by calind** [comment]
You can reproduce it by running docker-in-docker in rootless mode (`dind-rootless` tag from https://hub.docker.com/_/docker).

We are using dind-rootless in our CI pipelines and up until 3f935302f43896bef7240b9bd80a8c6f4c5cac4b we did not had any networking issues.

**Comment by loosebazooka** [comment]
As debug images are a convenience and not meant for production, they are extremely low priority for us, if you can isolate the issue and provide a fix I can merge a PR.
