### ISSUE TITLE
Node.js 18 image size vs Node.js 16

### ISSUE THREAD

**Issue by david-szabo97** [GoogleContainerTools/distroless#1174]
Node.js 18 image size is 50 MB more than Node.js 16.

Node.js 18 introduced a lot of files in the `include/openssl` directory. Is anyone familiar with what these files are used for? I'd guess they are used for building native addons. Therefore could they be excluded from the image? Since the image is basically used as a runtime and not for building anything.

![image](https://user-images.githubusercontent.com/2256104/201223330-49a3e21b-473e-4cf6-8d76-854318b7b3b2.png)

**Comment by loosebazooka** [comment]
Did you find any information on this?

**Comment by david-szabo97** [comment]
@loosebazooka There is an issue ongoing at Node.js: https://github.com/nodejs/node/issues/45454
