### ISSUE TITLE
openJDK 11.0.17 has been out for a while, distroless/java11 images need update

### ISSUE THREAD

**Issue by ajay-aggarwal** [GoogleContainerTools/distroless#1214]
OpenJDK quarterly security release 11.0.17 has been out since November 2022. However distroless/java11-debian11 image is still at 11.0.16. Can we have the image updated with latest OpenJDK 11? Thanks.

**Comment by dlorenc** [comment]
Feel free to try the Chainguard images - they have OpenJDK 11.0.18 already - https://github.com/chainguard-images/images/tree/main/images/jdk

cgr.dev/chainguard/jdk:openjdk-11.0.18

It looks like these images will be stuck in 11.0.16 until Debian updates: https://packages.debian.org/bullseye/openjdk-11-jdk

**Comment by loosebazooka** [comment]
images are now at 11.0.18
