### ISSUE TITLE
How to set umask

### ISSUE THREAD

**Issue by ding-ma** [GoogleContainerTools/distroless#1217]
Since the `:latest` tag do not have a shell, how can i set umask?

**Comment by loosebazooka** [comment]
Well there is no umask, but there's also no cmdline utilities. What are you using to generate files?

**Comment by ding-ma** [comment]
For processes as EKS has a low soft limit but a high hard limit. I would like to be able to increase the soft limit.

**Comment by dlorenc** [comment]
> For processes as EKS has a low soft limit but a high hard limit. I would like to be able to increase the soft limit.

Do you mean ulimit, not umask?

**Comment by ding-ma** [comment]
yes sorry

**Comment by ding-ma** [comment]
For those wondering, you can set the umask with a shell wrapper in golang. Before launching the user's program simply call syscall.Umask()
