### ISSUE TITLE
FR: Support for distroless Nginx web server

### ISSUE THREAD

**Issue by ibidani** [GoogleContainerTools/distroless#1219]
For Node applications that host only static files, a more performant and secure runtime will be Nginx or Caddy.
Will you consider publishing a web server for hosting static sites? 🙏

**Comment by loosebazooka** [comment]
Right now we're trying to limit the breadth of images to maintain in this repo. We have some updates in progress that should make it easier to build your own images... (But they are not ready). There are other distroless-style image offerings or there that might satisfy your needs in the meantime (@dlorenc)

**Comment by dlorenc** [comment]
I've been summoned!

Please try cgr.dev/chainguard/nginx and let us know what you think!

**Comment by ibidani** [comment]
Wow really impressive work with Chainguard, Thanks @loosebazooka @dlorenc
