### ISSUE TITLE
golang:1.20-bullseye builder-image incompatible with gcr.io/distroless/static-debian11

### ISSUE THREAD

**Issue by tim-hilt** [GoogleContainerTools/distroless#1227]
**Describe the bug**

If I build my go-application with `golang:1.20` (aka [1.20.0-bullseye](https://github.com/docker-library/golang/blob/b0badfc359dc188155f6447b0bf20118f6851e37/1.20/bullseye/Dockerfile)) I can't execute the build-output. It always shows `/exec file not found`

**To Reproduce**

1. Use the following `Dockerfile` to build a simple go-application:

``` Dockerfile
# Builder
FROM golang:1.20 AS builder
WORKDIR /go/src/app
COPY . .
RUN go build -ldflags="-w -s"

# Runner
FROM gcr.io/distroless/static-debian11
COPY --from=builder /go/src/app/app /
CMD ["/app"]
```

2. `docker build -t app .`
3. `docker run app`

**Expected behavior**

`golang:1.20` is the same as `golang:1.20.0-bullseye`, which I would assume is compatible with `distroless-static-debian11` (Debian Bullseye == Debian 11 after all). Using `golang:1.20-alpine` as the builder-image works, which seems counter-intuitive to me!

Shouldn't a debian-based Docker-image be "more compatible" than an alpine-based one?

**Additional context**

```
- Docker version 20.10.23, build 715524332f
- Linux t14s 6.1.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 01 Feb 2023 17:07:39 +0000 x86_64 GNU/Linux
```

**Comment by loosebazooka** [comment]
if you're using static, the build system shouldn't matter too much since there is no libc dependency. But this is still a bit strange. Can you link to an image that you've built that has this broken behavior?

**Comment by tim-hilt** [comment]
I just tried it out with a "hello-world" application. I can not reproduce the behavior there unfortunately. I think it might have something to do with the dependencies I'm using in the real application (gin and zerolog).

maybe I'll find the time to build a mini example in the upcoming days that can reproduce the issue. Would you be fine with letting this open until then?

**Comment by loosebazooka** [comment]
yeah sounds good.

**Comment by tim-hilt** [comment]
Alright, I managed to reproduce it. It seems, that `zerolog` ([src](https://github.com/rs/zerolog)) is at fault here. As soon as I added it to the module, the distroless-image couldn't run the binary, although I could confirm that the file is present:

``` sh
exec /debug-go-docker: no such file or directory
```

Here is my sample-repo: https://github.com/tim-hilt/debug-go-distroless To reproduce:

``` bash
git clone git@github.com:tim-hilt/debug-go-distroless.git
cd debug-go-distroless
docker build -t test . && docker run test
```

**Comment by Sineaggi** [comment]
Under debian, the following dynamic libraries were linked.
```
$ ldd debug-go-docker
#13 0.360       linux-vdso.so.1 (0x00007ffd3c0be000)
#13 0.360       libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa9d4600000)
#13 0.360       libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa9d45de000)
#13 0.360 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa9d4409000)
#13 0.360 	/lib64/ld-linux-x86-64.so.2 (0x00007fa9d4620000)
$ file debug-go-docker
#15 0.328 debug-go-docker: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=1L6nEjZ8U0MncEjk-UB4/vrHKgD5ME3p88ijm-lyT/FwTU0Unp7du6pAZq1CA0/ZdEoPEGoeDLUTv9LKB-4, stripped
```
Under alpine, the binary was statically linked.
```
$ file debug-go-docker
#13 0.302 debug-go-docker: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=abID4x10rl1q2jhU1VYL/h2SwLkMUafa8ZG-P-s_e/r0qkFBF8Mb-2E512HKCp/i6oGtUWSfgitHdnnB7ZQ, stripped
```

The static image would run with the static distroless tag, but for a dynamically linked go binary you'd need at least cc (or more?).

**Comment by tim-hilt** [comment]
So the go build command does different things depending on the distro?

**Comment by Sineaggi** [comment]
That would be a question for the [team](https://github.com/docker-library/golang) that manages the "official" golang docker images. Perhaps go is aware of it's own environment and will produce a statically linked binary when building under alpine?

**Comment by tim-hilt** [comment]
Thanks for the replies. I‘ll look into this a bit more. I‘ll consider this issue solved though.
