### ISSUE TITLE
tag and make a release

### ISSUE THREAD

**Issue by sebgoa** [GoogleContainerTools/distroless#123]
Could you tag the repo and make a github release, so that we can load the `package_manager` rules remotely ?

Right now your python image for example has a build that assumes local package_manager rules.

as much as I understand bazel :(

**Comment by MarkusTeufelberger** [comment]
You can just load external rules via a git commit hash instead of a tag.

**Comment by sebgoa** [comment]
yes I know and that's what I did, but I think there should be a tagged release.

**Comment by dlorenc** [comment]
Do you need anything in the release other than a git tag?

You might have been bitten by this too, but the auto-generated github release tarballs aren't generally safe to use via `http_archive` WORKSPACE rules, since the tar SHAs can change.

**Comment by sebgoa** [comment]
ok, the full story is that I was building a container and I wanted to try the new way to load debs.

I realized the rules where in the `package_manager` in this repo and not in the `rules_docker` repo. So I had to add:

```
git_repository(
    name = "distroless_rules",
    remote = "https://github.com/googlecloudplatform/distroless.git",
    commit = "4a20649aac319b2ee2f9c058c6a100784904ce7d"
)
```
Which made me look up the latest commit since there was no tag available.

I guess I don't need a release but only a tag.
