### ISSUE TITLE
Images being republished despite no change: stamping causing unnecessary updates

### ISSUE THREAD

**Issue by phlax** [GoogleContainerTools/distroless#1239]
**Describe the bug**

We (Envoy) build on the `distroless-nossl` image as we compile statically and have no need for anything other than glibc.

The `nossl` image was a hugely welcome addition for us as we were previously fielding vuln reports to the (unused) ssl in the published container.

One of the perceived benefits is that the container image should not need to change too often.

The problem is that we use dependabot to track the published images and they are being updated several times a week despite afaict no change to the image that we are actually using.

As we publish a `latest` image i dont want to hold back on updates, or have to analyze every update to figure if should be included

(~EDIT: checking and we dont actually publish a `distroless` latest so potentially could just ignore the updates until release - but it would be still be very useful to know when the image really has been updated~ correction, we do! https://hub.docker.com/r/envoyproxy/envoy-distroless-dev/tags)

The ideal for us would be the published image only gets updated when there is a change - or versioned releases are used so we can track them rather than git commits.

**To Reproduce**

To confirm my suspicions i built the following docker image:

```Dockerfile
FROM debian:bullseye-slim

COPY --from=gcr.io/distroless/base-nossl-debian11:nonroot@sha256:bf6159657aa6ac2c0d52e78a616991ac523adafd0718d17c6a013958a6770e1d / /tmp/current
COPY --from=gcr.io/distroless/base-nossl-debian11:nonroot@sha256:99a9bd01c70cf08873a808e08d78a576a7b3f370246a07ad147ec480cdcf96b0 / /tmp/next

RUN echo "#!/bin/bash -e" > /compare.sh \
    && echo "du -c /tmp/current | grep total" >> /compare.sh \
    && echo "du -c /tmp/next | grep total" >> /compare.sh \
    && chmod +x /compare.sh

CMD ["/compare.sh"]
```

running this suggests there is no change to the fileystem at least:

```console
$ docker run --rm distroless-compare
18952	total
18952	total
```

**Expected behavior**

Images are published when there are actual changes (or versioned releases)

**Comment by loosebazooka** [comment]
Yeah this is likely due to stamping of the creation time that was added in with https://github.com/GoogleContainerTools/distroless/pull/1203. Since the commit changes, the `createdAt` time also changes even if the particular build doesn't. I can see how it's pretty disruptive the way the repository/build is structured right now.

I'll think I'll revert for now until we can find a solution that works.

**Comment by phlax** [comment]
thanks @loosebazooka thats really appreciated

**Comment by phlax** [comment]
not sure if something reverted or there is just has been changes to the distroless nossl image but seeing quite a few updates again

**Comment by loosebazooka** [comment]
curious... I'll re-open for now and inspect

**Comment by phlax** [comment]
i didnt check the actual contents but we are just getting a lot of updates again

**Comment by loosebazooka** [comment]
Just an update here, this might happen for a few more builds, but we're moving the build to rules_oci and it should be resolved then. Apologies for the inconvenience.

**Comment by phlax** [comment]
np, thanks for letting us know

**Comment by phlax** [comment]
no - looking good our end, thanks

**Comment by phlax** [comment]
@loosebazooka this seems to be happening again - wondering if the updates are genuine or whether something changed that is causing daily publishing

**Comment by loosebazooka** [comment]
We did a reversion of a change that broke something. So it was triggered a rebuild.
