### ISSUE TITLE
Our App image is not building from yesterday

### ISSUE THREAD

**Issue by sathishkumarpsk** [GoogleContainerTools/distroless#1262]
**Describe the bug:**
Our app is node based and we build our app using docker distroless nodejs 14 but is failing from yesterday with the below error. It used to work till yesterday and is it anyway related to the pr changes (https://github.com/GoogleContainerTools/distroless/pull/1256)?

```
Step 5/9 : FROM gcr.io/distroless/nodejs:14
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'
Terminating Docker daemon.
```

Before we updating manifest, any clarity or suggestion would be helpful!

**More information:**
We use concourse CI and below are the docker version used.
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfca03
 Built:             Thu Aug 29 05:26:30 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfca03
  Built:            Thu Aug 29 05:32:56 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Happy to give more details if needed

**Comment by polarathene** [comment]
That release of Docker Engine is quite old, does your CI not have anything newer?

**Comment by sathishkumarpsk** [comment]
It is organization level docker engine currently used. Does upgrading it will resolve the issue? if so, we can try doing that.

**Comment by loosebazooka** [comment]
Yeah an upgrade should solve your issue

**Comment by sathishkumarpsk** [comment]
Docker engine update didn't help.

Actually nodejs:14 distroless mediaType recently updated, which is actually started breaking our pipeline. we can see it [here](https://gcr.io/distroless/nodejs:14). Issue fixed after updating the node version to nodejs:18, as node:18 uses the manifest type we configured.

Anyway great thanks for all your inputs!!
[loosebazooka](https://github.com/loosebazooka) [polarathene](https://github.com/polarathene)

**Comment by loosebazooka** [comment]
Be advised the  nodesjs:<version> tags are deprecated. You should be using nodesjs<version>-debian11, which have oci manifest types

**Comment by sathishkumarpsk** [comment]
yeah, that seems useful, thanks for the inputs @loosebazooka
