### ISSUE TITLE
Image base-debian11:latest-amd64 equals base:latest-amd64 in registry

### ISSUE THREAD

**Issue by nikolaevn** [GoogleContainerTools/distroless#1266]
Two images have **same** sha256 hashes (both now have tag latest-amd64):

gcr.io/distroless/base-debian11@sha256:2c50b819aa3bfaf6ae72e47682f6c5abc0f647cf3f4224a4a9be97dd30433909
gcr.io/distroless/base@sha256:2c50b819aa3bfaf6ae72e47682f6c5abc0f647cf3f4224a4a9be97dd30433909

Publishing bug?

**Comment by loosebazooka** [comment]
those are the same images: base and base-debian11, the only difference is that base may change at some point to point at debian12 (when ready).

**Comment by nikolaevn** [comment]
Thanks for clarification.
