### ISSUE TITLE
Java17 is not published under java: Is it a bug or is it expected?

### ISSUE THREAD

**Issue by evrardjp** [GoogleContainerTools/distroless#1272]
**Describe the bug**

Not really a bug, more a question before issuing a PR.

Images for java17 are published under https://console.cloud.google.com/gcr/images/distroless/global/java17 but not into https://console.cloud.google.com/gcr/images/distroless/global/java .

Is it intentional to split per version, and not have 17 in https://console.cloud.google.com/gcr/images/distroless/global/java (but have 11).

**To Reproduce**
Check links above

**Expected behavior**
All java versions listed in https://console.cloud.google.com/gcr/images/distroless/global/java

**Console Output**
- 

**Additional context**
- 

**Additional content**
Do we need to document the expected structure of the images for java? This might remove expectations mismatches.

**Comment by loosebazooka** [comment]
https://github.com/GoogleContainerTools/distroless#what-images-are-available

gcri.io/distroless/java has not been updated since Apr 2022

**Comment by evrardjp** [comment]
Thanks for clarifying @loosebazooka . That's what I thought too. Have a good day!
