### ISSUE TITLE
Accordingly to the README file the gcr.io/distroless/java11 is not supported nor updated

### ISSUE THREAD

**Issue by devdecrux** [GoogleContainerTools/distroless#1276]
According to the documentation here: https://github.com/GoogleContainerTools/distroless/blob/main/README.md#what-images-are-available the docker image "gcr.io/distroless/java11" is not supported nor updated. However, it's updated on a daily basis. Is this some kind of a documentation mistake or not up-to-date information?

Please for clarification.

Thanks in advance for your time!

**Comment by loosebazooka** [comment]
yes technically `java11` points to `java11-debian11`, but I don't want people to get into the habit of using `java11` under the assumption that it points to `debian11`. For instance when `debian12` is released, we'll make `java11` point to `java11-debian12` or something.

**Comment by movalchev** [comment]
Thank you for the clarification.
