### ISSUE TITLE
Time sync with node/host not synced

### ISSUE THREAD

**Issue by Jeansen** [GoogleContainerTools/distroless#1281]
**Describe the bug**
When I restore my cluster nodes to a previous snapshot - they all are KVM machines - they are out of sync with respect to the current time. After I have synced them, all Nodes and all pods with full images (having a shell) show the same time. That's even true before and after correcting time. Pods running on distroless do not show the accurate time. They stick to the "old" time.

**To Reproduce**
- Create a cluster with N nodes in a VM
- Deploy e.g. cert-manger
- Create a snapshot
- Wait some hours
- Restore the snapshot
- Sync time (I use chronyd)
- Deploy an application that relies on cert-manger, e.g. jaeger

**Expected behavior**
All nodes and all pods should have the same time.

**Console Output**
Here's an excerpt of a jager deployment:
```
Error from server (InternalError): error when creating "https://github.com/jaegertracing/jaeger-operator/releases/download/v1.42.0/jaeger-operator.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": x509: certificate has expired or is not yet valid: current time 2023-03-24T20:25:56Z is after 2023-03-02T15:11:24Z
Error from server (InternalError): error when creating "https://github.com/jaegertracing/jaeger-operator/releases/download/v1.42.0/jaeger-operator.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": x509: certificate has expired or is not yet valid: current time 2023-03-24T20:25:56Z is after 2023-03-02T15:11:24Z
Error from server (NotFound): secrets "os-cluster-admin-password" not found
```

**Additional context**
If I delete the pods, everything works, naturally.

**Comment by loosebazooka** [comment]
This is a bit of a complex example. If you could figure out why it's not sync'ing and what is needed, that is an item we can act on.

**Comment by Jeansen** [comment]
@loosebazooka Yes, I know. Unfortuantely the project to setup Kubernetes is quite complex. So, I could only outline the context. I will try to get some minimal setup with a distroless:debug container.

**Comment by Jeansen** [comment]
OK, I revert my bug. I've checked with the :debug image, and time is fine there. The error must be somewhere else ... Sorry for the noise!

**Comment by loosebazooka** [comment]
The debug image has a shell though... I don't know if that was needing with your experiment

**Comment by Jeansen** [comment]
I don't know either, but that was the quickest way to find out, if the pod has the same time as the node. So, if it is the same image, only with a shell, then I would deduce, the container runs just fine and it is an application issue. For now, I'll check with the guys from the cert-manager team.
