### ISSUE TITLE
:latest tag does not exist for nodejs 16 and 18

### ISSUE THREAD

**Issue by diamkil** [GoogleContainerTools/distroless#1285]
**Describe the bug**
Trying to pull the nodejs distroless image without specifying a tag (like on the README.md) will return and error

**To Reproduce**
Try to pull gcr.io/distroless/nodejs18-debian or  gcr.io/distroless/nodejs16-debian

**Expected behavior**
The image gets pulled

**Console Output**
`manifest for gcr.io/distroless/nodejs18-debian:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/distroless/nodejs18-debian/manifests/latest"`

**Comment by loosebazooka** [comment]
try `nodejs18-debian11`

**Comment by diamkil** [comment]
> try `nodejs18-debian11` not `nodejs18-debian`

The documentation should reflect this (sorry for the phone picture) ![image](https://user-images.githubusercontent.com/35732047/228966314-729a06f3-e6ea-472d-8e4a-1d17039053f2.png)

**Comment by loosebazooka** [comment]
Ah. Thanks for pointing that out
