### ISSUE TITLE
architecture specific pulls with tag

### ISSUE THREAD

**Issue by mnacken** [GoogleContainerTools/distroless#1306]
**Describe the bug**
We are using [Renovate](https://github.com/renovatebot/renovate) for updating our own internal images which are based on the distroless images.

So far we have been able to keep everything up to date using a tag including the architecture for example "nodejs18-debian11:nonroot-amd64@sha256:733debf656767452adbedc10c2100e988ccac7c63589c13d6a9587a2bbb74501" and the sha-digest.

For some time, however, the images listed [here](https://console.cloud.google.com/gcr/images/distroless/global/nodejs18-debian11) doesnt include architecture in tag anymore.
I can see these tags with architecture here: https://console.cloud.google.com/gcr/images/distroless/global/nodejs20
But as mentioned in README it seems that this is considered deprecated.
>Any other tags are considered deprecated and are no longer updated

Is it planned that `<image>-<distro>` images will again be offered with the architecture included in the tag ?

**Comment by loosebazooka** [comment]
No the architecture specific tags will exist. I'll update the readme

**Comment by mnacken** [comment]
Thanks for updating the README. When I'm looking for nodejs18-debian11 Images: https://console.cloud.google.com/gcr/images/distroless/GLOBAL/nodejs18-debian11

I dont find any of the architecture tagged images for nodejs, like i.e for example https://console.cloud.google.com/gcr/images/distroless/global/java17-debian11

**Comment by loosebazooka** [comment]
Yeah, I think those tags are missing currently -- but should be addressed here: https://github.com/GoogleContainerTools/distroless/pull/1317#pullrequestreview-1425474391
