### ISSUE TITLE
Question about deprecation for gcr.io/distroless, Container Registry

### ISSUE THREAD

**Issue by atpons** [GoogleContainerTools/distroless#1320]
According to https://cloud.google.com/container-registry/docs/release-notes#May_15_2023, it states that `gcr.io/distroless` are deprecated in Container Registry and users are required to migrate to Artifact Registry.

Do you have any plans to migration to Artifact Registry?

Thank you all for your contributing.

**Comment by loosebazooka** [comment]
I think we'll just be doing gcr.io hosted on artifact registry for a bit. But I haven't tested that out yet, but we're pretty safe for another year it looks like.

**Comment by j-windsor** [comment]
I have an issue b/297937428 impacting customers for my team that will not be fixed in GCR as it is deprecated. Is there a timeline for this?

**Comment by grassehh** [comment]
Any udpates about this ? Container Registry will be replaced by Artifact Registry on March 18, 2025.

**Comment by loosebazooka** [comment]
I'm still kinda slowly working on this. No timeline is available. But it'll get done before deprecation. We will still use the gcr.io urls.

**Comment by baraknaveh** [comment]
@loosebazooka looks like updates to gcr.io stopped coming as of March-11.

**Comment by loosebazooka** [comment]
?

**Comment by loosebazooka** [comment]
Gcr.io is still serving images as far as I can tell.

**Comment by baraknaveh** [comment]
@loosebazooka still serving, but the last build creation dates are March 11

**Comment by loosebazooka** [comment]
Can you point me to what you're looking at

**Comment by baraknaveh** [comment]
@loosebazooka I'm looking at https://console.cloud.google.com/gcr/images/distroless/global/java-base-debian12 (sorting by created time, descending).

We're experiencing a new incompatibility issue between a fully patched `python:3.12-slim-bookworm` and `gcr.io/distroless/base-debian12` for a configuration that has been working for while now. My suspicion is that `gcr.io/distroless/base-debian12` might have fallen behind on updates. Might be a red herring but the last created time of March-11 seems to align with this explanation.

**Comment by loosebazooka** [comment]
We were doing some active development around then with the distroless ruleset, those times may not be useful. "upload time" is probably what you want. You can assume at best that creation time is always some arbitrary time in the past.

**Comment by baraknaveh** [comment]
Thanks for clarifying! 
We'll keep investigating and I'll report back if we find anything share-worthy.

**Comment by coderkakarrot** [comment]
@loosebazooka Is it safe to assume that images are migrated to Artifact Registry, we will continue using gcr.io domain hosting images?

**Comment by polarathene** [comment]
> we will continue using gcr.io domain hosting images?

https://github.com/GoogleContainerTools/distroless/issues/1630#issuecomment-2336467872

> _`gcr.io/distroless` is now served by the AR infrastructure._
> _The GCR infra is shutting down but the domain `gcr.io` will continue to served by AR._

**Comment by baraknaveh** [comment]
@polarathene thanks for the clarification!
