### ISSUE TITLE
Debian 12 Support

### ISSUE THREAD

**Issue by Sineaggi** [GoogleContainerTools/distroless#1337]
Debian 12 "bookworm" has been released!

News article [here](https://www.debian.org/News/2023/20230610).

**Comment by pupapaik** [comment]
Debian 12 support would be awesome to get Python 3.10. How much time it can take?

**Comment by dlorenc** [comment]
Feel free to try the chainguard images based on Wolfi, they have support for multiple versions of python:

cgr.dev/chainguard/python

**Comment by theganyo** [comment]
We're unable to build with latest Golang container (golang:1.20.5) and as it's now being built from Debian 12 and this container is missing expected libs.

```
/registry-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /registry-server)
/registry-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /registry-server)
/registry-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /registry-server)
```

https://github.com/apigee/registry/issues/1196#issuecomment-1593795069

**Comment by j-be** [comment]
@theganyo try building with `1.20.5-bullseye`

**Comment by theganyo** [comment]
Thanks @j-be ! Yes, I just switched to the bullseye build and that works fine.

**Comment by joberget** [comment]
Any update on this?

**Comment by SanjayVas** [comment]
Note that despite this being marked as completed by #1385, that PR only added Debian 12 images for `base`, `static`, `base-nossl` and `cc`. The officially supported `java11`, `java17`, `nodejs18`, and `nodejs20` images still haven't been updated. The experimental `python3` has also not been updated.

Should this issue be reopened or a new one filed? If the latter, this one should be updated to clarify what it covers.

**Comment by loosebazooka** [comment]
Lets just open a new one.

**Comment by loosebazooka** [comment]
https://github.com/GoogleContainerTools/distroless/issues/1398
