### ISSUE TITLE
update glibc

### ISSUE THREAD

**Issue by ice-cronus** [GoogleContainerTools/distroless#1342]
Golang 1.20.5 [uses glibc 2.32](https://github.com/docker-library/golang/issues/466), while  gcr.io/distroless/base-debian11:latest has 2.31

As a result it leads to the error 
```
/app: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app)
/app: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app)
```

**Comment by pebo** [comment]
The `1.20` tag now points to bookworm (debian 12): https://hub.docker.com/_/golang
```
1.20.5, 1.20, 1, latest:
  1.20.5-bookworm
  1.20.5-windowsservercore-ltsc2022
  1.20.5-windowsservercore-1809
```

If you want to use go `1.20.5` you could try switching the build image to `golang:1.20.5-bullseye` or ``golang:1.20-bullseye``

**Comment by smcguirecn** [comment]
Thanks! Yeah, for now we're just holding golang version back to 1.20.4 ... but I'll try the bookworm thing in the coming days

**Comment by pplmx** [comment]
> This is due to the changeover of the `golang` image builds to use Debian 12, while the Distroless images are all still tagged `-debian11`. Once `-debian12` Distroless image tags are available, you'll be able to simply use the `golang` image tags like you were using before. Until then you can use the `golang:1.20-bullseye` to perform your build with the latest go 1.20.x.

## Using `golang:1.20-bullseye`, still throws error:

```txt
Error: Dynamic Linking Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/src/so/libtcpserver.so)
```

## Dockerfile
```Dockerfile
FROM golang:1.20-bullseye AS so
# build dynamic lib
# ...

FROM node:18-bullseye AS env
# install node packages
# ...

FROM gcr.io/distroless/nodejs18-debian11
# running js app with golang dynamic lib

```

**Comment by pplmx** [comment]
> > This is due to the changeover of the `golang` image builds to use Debian 12, while the Distroless images are all still tagged `-debian11`. Once `-debian12` Distroless image tags are available, you'll be able to simply use the `golang` image tags like you were using before. Until then you can use the `golang:1.20-bullseye` to perform your build with the latest go 1.20.x.
> 
> ## Using `golang:1.20-bullseye`, still throws error:
> ```
> Error: Dynamic Linking Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/src/so/libtcpserver.so)
> ```
> 
> ## Dockerfile
> ```dockerfile
> FROM golang:1.20-bullseye AS so
> # build dynamic lib
> # ...
> 
> FROM node:18-bullseye AS env
> # install node packages
> # ...
> 
> FROM gcr.io/distroless/nodejs18-debian11
> # running js app with golang dynamic lib
> ```

## Solution

After the above, build image on **`Ubuntu 18`**

**Comment by rayshihUI** [comment]
Use golang: bullseye could solve this issue

**Comment by theory** [comment]
Looks like using `-bullseye` isn't necessary with the `golang:1.21` image.

**Comment by loosebazooka** [comment]
debian12 images are available for base, base-nossl and static. I believe this should now be working.

**Comment by lcmgh** [comment]
Could you also provide the changes for gcr.io/distroless/cc ? @loosebazooka 
I am trying to run an executable built on `rust:1-bookworm` which is not runnable on `gcr.io/distroless/cc`

`/app/executable: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/executable)`

**Comment by duke-cliff** [comment]
@loosebazooka I am using the latest distroless/cc, it's still using `2.31`.

distroless/base is not working for us as well as it does not have `libstdc++.so.6`

**Comment by loosebazooka** [comment]
are you using distroless/cc-debian12 ?

**Comment by daluntw** [comment]
`gcr.io/distroless/static-debian12` will not work with `golang:1.21.4` for me

**Comment by sankalp-khare** [comment]
Using distroless-debian12 (instead of debian11) fixed this for me
