### ISSUE TITLE
Basic java app does not seem to be able to resolve its own hostname

### ISSUE THREAD

**Issue by rvowles** [GoogleContainerTools/distroless#136]
I have tried running this up inside k8s with Java applications we have. They cannot resolve their own hostname into an ip. I have confirmed by having the Java app "cat" the /etc/hosts file is in the /etc/file, and it is there. 

For some weird reason, many Java libraries (such as Jedis, Quartz, Mule, etc) get very upset if they can't determine what their hostname's ip is.

This isn't necessarily an "issue" - it may be by design, but I cannot find any reference to it, so I thought I should ask if it was intended.

**Comment by dlorenc** [comment]
Could you provide a stacktrace or some more info on what happens? I think k8s overrides/injects the etc/hosts file so I'm not sure what we'd have to do in the image to make this work.

**Comment by rvowles** [comment]
@dlorenc do you have a way i can do that? k8s does normally add the pod name to the etc/hosts, but because there is no shell i can't get into the instance to see what has actually happened. The stack trace is just your usual "cannot resolve hostname". 

If you have a suggestion on how  to get onto the filesystem to see what is going on (should i do that sideload busybox hack?) then i can add more info.

**Comment by mattmoor** [comment]
FWIW If you use `:debug` instead of `:latest` you should have `busybox`.

**Comment by rvowles** [comment]
ok! i can do that!

**Comment by rvowles** [comment]
i got onto the box and see this:

/ # cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.17.0.8	bizservices-all-3290099977-5szr5
/ # cat /etc/resolv.conf 
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
/ # cat /etc/nsswitch.conf
cat: can't open '/etc/nsswitch.conf': No such file or directory

so the pod name is in the /etc/hosts as expected.

the stack trace is

java.net.UnknownHostException: bizservices-all-3290099977-5szr5: bizservices-all-3290099977-5szr5: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[?:1.8.0_141]
	at redis.clients.jedis.HostAndPort.getLocalHostQuietly(HostAndPort.java:105) ~[jedis-2.9.0.jar!/:?]

when run with: openjdk:8u151-jre-slim

cat /etc/resolv.conf 
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
root@bizservices-all-3427948651-31q68:/# cat /etc/hosts 
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.17.0.8	bizservices-all-3427948651-31q68
root@bizservices-all-3427948651-31q68:/# cat /etc/nsswitch.conf 
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis

(no failure to find)

**Comment by rvowles** [comment]
sorry, formatting issues there.

**Comment by jiel** [comment]
Hello @rvowles 
Nothing new about your issue ? 
I think I ran into something similar (see #174)

**Comment by rvowles** [comment]
Its still open - I presume they haven't attempted to fix it.

**Comment by jiel** [comment]
I got a good insight on my issue, see: https://github.com/GoogleCloudPlatform/distroless/issues/174#issuecomment-378137247
(The file /etc/nsswitch.conf is not in the distroless image)

**Comment by rvowles** [comment]
This issue is blocking us from using this as the base image with Jib. aka https://github.com/GoogleContainerTools/jib

**Comment by lathama** [comment]
You should be able to use the :debug images to access them for troubleshooting issues. See https://github.com/GoogleContainerTools/distroless#debug-images for more info.

**Comment by mblaschke** [comment]
I'm using the image `jimmidyson/configmap-reload` which is included in the official helm chart repository for prometheus which is also causing this issue.

This container is used to detect configmap changes and reloads prometheus if it detects one. Because someone registered a VM in our cloud with the name `localhost` (for what ever reason) the requests are going to this VM instead to `127.0.0.1`.

This image is using `gcr.io/distroless/base` as base and uploads a golang binary. So it's not just a java issue.

Took hours to find this issue but we can clearly see that the DNS requests are hitting the external DNS instead of directly using `127.0.0.1` for `localhost`.

And still it's also a **security issue** because an external attack could redirect the traffic if this attacker can gain access to the DNS.

**Comment by bas-velthuizen** [comment]
Is there any progress on this issue?

**Comment by chanseokoh** [comment]
This is a duplicate of #174 and fixed by supplying `/etc/resolv.conf `. Make sure to use the latest images.

**Comment by chanseokoh** [comment]
Sorry, `/etc/nsswitch.conf`, not `/etc/resolv.conf`.
