### ISSUE TITLE
nodejs18:latest is still running 18.16.1

### ISSUE THREAD

**Issue by sophos-daniels** [GoogleContainerTools/distroless#1363]
**Describe the bug**
The `gcr.io/distroless/nodejs18-debian11:latest` image is still running v18.16.1 event though PR: https://github.com/GoogleContainerTools/distroless/pull/1357 was merged several days ago. Checking the nodejs20 image and it has the correct version v20.5.0, from this PR: https://github.com/GoogleContainerTools/distroless/pull/1361 merged at the same time as the node18 PR.

**To Reproduce**
1. `docker run --pull=always -it gcr.io/distroless/nodejs18:latest`
2. view node.js output

**Expected behavior**
The latest node18 image should be running v18.17.0

**Console Output**
<img width="645" alt="Screenshot 2023-07-26 at 9 43 57 AM" src="https://github.com/GoogleContainerTools/distroless/assets/91908637/a8e0a847-bfbd-43b8-ae00-aa96e6feff60">

**Comment by loosebazooka** [comment]
https://github.com/GoogleContainerTools/distroless/issues/1324#issuecomment-1608061953
