### ISSUE TITLE
gcr.io/distroless/cc should be based on Debian12

### ISSUE THREAD

**Issue by nolik** [GoogleContainerTools/distroless#1404]
**Describe the bug**
Despite of closing https://github.com/GoogleContainerTools/distroless/issues/1337 
`gcr.io/distroless/cc` still use Debian 11.

**To Reproduce**
```
 docker run -it gcr.io/distroless/cc:debug
/ # cat /etc/issue
Debian GNU/Linux 11 \n \l
```

**Expected behavior**
fresh `gcr.io/distroless/cc` image should use Debian 12 (will be nice as well include Openssl 3+ that used by Debian12).

**Additional context**
Seems `gcr.io/distroless/cc` doesn't include Debian12.

**Comment by siketyan** [comment]
Any ETA for switching the default to Debian 12 entirely? I can prepare a pull request for this if needed.

**Comment by loosebazooka** [comment]
The switch over is expected to happen on Oct 20, as announced on slack (https://kubernetes.slack.com/archives/CQ2SA4JK0/p1695233686311049) and the google group (https://groups.google.com/g/distroless-users/c/_O6X7ThkUDg)

**Comment by loosebazooka** [comment]
@siketyan you can still create a PR, I will just wait to merge it once the date has passed

**Comment by Sineaggi** [comment]
This issues can be closed
```
 docker run -it gcr.io/distroless/cc:debug
/ # cat /etc/issue
Debian GNU/Linux 12 \n \l
```

**Comment by polarathene** [comment]
Ref: https://github.com/GoogleContainerTools/distroless/pull/1574
