### ISSUE TITLE
Python3 in debian12 (regular and plus)

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/distroless#1409]
This is a tracking issue for python3 support for debian12. This is a breaking change for people simply doing a `python3-debian11` -> `python3-debian12` migration but I think we should change this early and now while we still can.

Python will move out of experimental and we will create two new images:

`python3`: python and deps
`python3-plus`: `python3` plus ctypes support and a shell

**Comment by loosebazooka** [comment]
@evanj @griggheo @afbjorklund seem to have the most recent comments on this? Any thoughts?

**Comment by lathama** [comment]
Having a shell is not ideal to me. Maybe calling it `python-shell` would call the issue out as security teams may be relying on the name Distroless.

**Comment by loosebazooka** [comment]
@lathama do you need the ctypes stuff?

**Comment by lathama** [comment]
I do not need ctypes in my usage. I feel that `plus` does not reflect the actual difference. I am looking at this from a security point of view. I will think about this some more.

**Comment by loosebazooka** [comment]
sure `plus` can be a different name, but I think the question really I'm looking for is how should the two images be split (plain python3 and python3+ctypes+shell)? or do we need a third images without a shell but with the ctypes support?

**Comment by lathama** [comment]
@loosebazooka thanks I see your question now. 

* I think a user that needs ctypes and shell might be better off using `python-slim` or some other image. 
* If a user needs to use `find_library()` then they may need to place the libraries in the image anyway.

I don't have an answer to your question. I can see an application that uses ctypes for performance and that would be awesome with Distroless. I can imagine an application getting pushed into Distroless and installing the kitchen sink in the process(shell).

I once caught a developer loading JavaJDK4 into an application class path and using the RHEL installer to side load their JDK version on a system. I am thinking about how to discourage or reduce the loss of trust in the Distroless idea.

**Comment by evanj** [comment]
Related: I did some investigation about the usage of the ctypes find_library function. This probably will break some third-party packages, but it seems like gunicorn, which is a relatively important third party package, no longer depends on this. See https://github.com/GoogleContainerTools/distroless/issues/601#issuecomment-1735550059

**Comment by evanj** [comment]
> * If a user needs to use `find_library()` then they may need to place the libraries in the image anyway.

Historically the problem has been calls to `ctypes.util.find_library('c')` and `ctypes.util.find_library('rt')` which some third-party libraries use to call glibc functions that don't have Python wrappers.

**Comment by loosebazooka** [comment]
Alright, so the plan is to just update the python image with no ctype support and noshell and move forward with that as the default behavior for gcr.io/distroless/python3-debian12 (debian11 will not change)

We can add back in an image with support for ctypes and shell if users truly need those.

**Comment by loosebazooka** [comment]
okay here we go: https://github.com/GoogleContainerTools/distroless/pull/1415

this will break people who have certain expectations of what python3-debian12 contained. Hopefully the impact is pretty small if those popular frameworks have removed dependencies on shell and ctypes

**Comment by lathama** [comment]
@loosebazooka maybe next round we can drop the 3 as I hope most of the users understand it is Python 3

**Comment by loosebazooka** [comment]
We could just do that here. And that wouldn't break anyone if we did the build

**Comment by matthewcummings** [comment]
@loosebazooka I see that you've merged your change, does this mean that python3-debian12 is officially out of the experimental stage?

**Comment by loosebazooka** [comment]
Yeah I should close this. But python3-debian12 is out of experimental

**Comment by matthewcummings** [comment]
@loosebazooka can you update the ReadME, it still says:

```
The following images are also published on gcr.io, but are considered experimental and not recommended for production usage:

[gcr.io/distroless/python3-debian12](https://github.com/GoogleContainerTools/distroless/blob/main/experimental/python3/README.md)
[gcr.io/distroless/python3-debian11](https://github.com/GoogleContainerTools/distroless/blob/main/experimental/python3/README.md)
```

**Comment by loosebazooka** [comment]
Ah, right, feel free to put up a PR. Or I'll get it to it at some point this week.

**Comment by matthewcummings** [comment]
I can open a PR, just remove that whole section or leave the `python3-debian11` as still experimental? @loosebazooka

**Comment by lathama** [comment]
I can do a PR because I missed the testing above

**Comment by matthewcummings** [comment]
Great, thanks @lathama

**Comment by loosebazooka** [comment]
leave python3 on debian11 as experimental

**Comment by lathama** [comment]
@loosebazooka ack, that is what I did, I did not want to go to far down the rabbit hole on the PR

**Comment by tonglil** [comment]
For anyone running into needing the shell during the build, I was able to access it by setting the `SHELL` to `/busybox/sh`:

```dockerfile
FROM gcr.io/distroless/python3-debian12:debug

SHELL ["/busybox/sh", "-c"]

RUN echo "baz"
```
