### ISSUE TITLE
Node 20.9.0 build missing

### ISSUE THREAD

**Issue by jbergstroem** [GoogleContainerTools/distroless#1438]
It seems like the build for 20.9.0 failed to complete: https://github.com/GoogleContainerTools/distroless/runs/18037134677 - as a user it'd be great to have access to the first 20.x LTS build.

**Comment by loosebazooka** [comment]
Oh yeah sorry I'm investigating this. I think the node serving infra timed out. I'll restart the build

**Comment by jbergstroem** [comment]
Seems like it was updated. Closing.
