### ISSUE TITLE
Extend Java 11 EOL date

### ISSUE THREAD

**Issue by johngmyers** [GoogleContainerTools/distroless#1439]
I request distroless to extend the java11 EOL date of 2023-12-01,  preferably to 2024-06-01, near when Debian 11 goes end of life.

The 2023-12-01 date was announced in #1408 on 2023-09-20. This was late in or after some organizations have done their Q4 planning. It does not give much time for a change that warrants a fair amount of testing.

It is not clear why the runway is so short or what benefit distroless gets from cutting support so long before Debian appears to do so.

**Comment by dlorenc** [comment]
Didn't this repo switch to debian 12? That's probably the cause here.

**Comment by loosebazooka** [comment]
I mean I not super attached to the eol date. We can extend Java a bit like the base and static images. Distroless is just a huge build and trimming it makes my life easier.

**Comment by johngmyers** [comment]
The current December date is particularly troublesome for us for Java 11. Python and Node aren't an issue for us (that I know of) because Debian 12 didn't drop support for a major version of Python and distroless doesn't tie Node support to Debian. 

Extending Java 11 like the base would be much appreciated.

**Comment by loosebazooka** [comment]
I think we might just solve this by providing java11 from temurin on debian12. similar to #1444

**Comment by johngmyers** [comment]
That would also work.

**Comment by johngmyers** [comment]
Made irrelevant by #1656

**Comment by loosebazooka** [comment]
@johngmyers are you still using java11? I was wondering if we should port java11 via temurin to debian12

**Comment by loosebazooka** [comment]
lol okay sounds good

**Comment by dheeg** [comment]
> I was wondering if we should port java11 via temurin to debian12

@loosebazooka Hi. It would be beneficial for us if that would happen.
