### ISSUE TITLE
Node.js base image does not include npm

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleContainerTools/distroless#152]
Most node.js developers use `npm start` as the command to start their application process.  When trying to do this with a distroless image, I get this error:

```
$ docker run -it -p 3000 wat
module.js:538
    throw err;
    ^

Error: Cannot find module '/npm'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

You can find the sources I'm using here:
https://github.com/JustinBeckwith/nodistro

To reproduce:
```
git clone https://github.com/JustinBeckwith/nodistro.git
cd nodistro
docker build -t wat .
docker run -it -p 3000 .
```

**Comment by ajuhaszcf** [comment]
The distroless image directly calls node directly (instead of a standard shell) so you’ll have to pass in the Javascript file directly with the docker run command. You can see the correct usage in the example multi-stage docker file.

`docker run .... src/index.js`

The Node’s install tar file actually does install npm, I’m actually trying to find time to remove that, decreasing both image size and increasing security.

**Comment by JustinBeckwith** [comment]
Thanks for the heads up :)  I was able to get this to work by monkeying with the Dockerfile to modify the entrypoint (thanks @dlorenc).  For node.js, using `npm` to start application is super idiomatic.  For most developers, they're going to expect to use that as their entrypoint.  There were 3 things I found that could have been a little easier :)

1. *Putting node.js on the path.* I had to know that the node binary was in a specific folder, and I couldn't just use it on the entrypoint.  It would be great if this just worked.
2. *Using entrypoint instead of CMD.*  Most other images I've worked with use CMD instead of ENTRYPOINT.
3. *Letting me use `npm start` in CMD.* This is pretty idiomatic for node.js developers, and something they're just going to expect to be able to do.  If the answer here is that we need to change `npm` to make it avoid shelling out - that's something we can run by them!

**Comment by pavel-kiselyov** [comment]
@JustinBeckwith you don't actually need `npm` or `yarn` to run package scripts - they're just shortcuts being run by `node`. E.g. right now I'm running my Vue.js project like this:

```
CMD ["node_modules/.bin/vue-cli-service", "serve"]
```

**Comment by nbcchen** [comment]
> [@JustinBeckwith](https://github.com/JustinBeckwith) you don't actually need `npm` or `yarn` to run package scripts - they're just shortcuts being run by `node`. E.g. right now I'm running my Vue.js project like this:
> 
> ```
> CMD ["node_modules/.bin/vue-cli-service", "serve"]
> ```

@pavel-main : 
How do I run that with `yarn`? I can do
```dockerfile
ENTRYPOINT ["yarn"]
CMD ["vue-cli-service", "serve"]
```
with other node images. But there's no `node_modules/.bin` for me to do this in gcr.io/distroless/nodejs
