### ISSUE TITLE
How to add msttcorefonts to the image

### ISSUE THREAD

**Issue by bkrajendra** [GoogleContainerTools/distroless#1523]
I am using jasper reports in my application. Jasper requires some basic fonts to be available in the system
Earlier with alpine image we used to install fonts in the base image and use it.
But how can we achieve same in the distroless image as suggested solution for jasper https://stackoverflow.com/a/74978195

Is there any specific location we can copy the fonts?
Will it work if the required fonts are copied to /usr/share/fonts or /usr/local/share/fonts directories?

**Comment by loosebazooka** [comment]
I don't think we can give guidance on adding fonts. Packages cannot be added using the tooling in that example on the image because the image does not contain tooling. You can create a tar and docker ADD it to the image and I believe that expands it out.

**Comment by bkrajendra** [comment]
Hi @loosebazooka,

I've encountered an ongoing issue despite attempting various solutions. 
Unfortunately, none have proven effective thus far. The root cause of the problem seems to be related to the absence of fontconfig in the container image, coupled with a lack of fonts within the container itself.

Any insights or suggestions on how to resolve this would be greatly appreciated.

This is what I have tried.

Solution 1:
Used a multi-stage build and copied the fonts from build step to final distroless stage.
```
FROM myregistry:5000/xyz/builder-base:mytag as BUILDER
# ubuntu image with fonts in it
# do some stuff here, build artifacts
FROM myregistry:5000/xyz/mydistroless:mytag
# Copy app.jar
COPY --from=BUILDER /build/target/myapp.jar /opt/iamboss/app.jar
COPY --from=BUILDER /usr/share/fonts /usr/local/share/fonts
## Run my app
ENTRYPOINT ["java", "-jar","app.jar"]
```

Solution 2:
manually copied fonts with docker ADD to the global fonts directory.
```
# added language, env var. 
ENV LANG en_GB.UTF-8

ADD ./fonts.tar.gz /usr/share/fonts/truetype/dejavu/
ADD ./fonts.tar.gz /usr/local/share/fonts/truetype/dejavu/
```

But all of these could not resolve the issue.
I have also posted the question on SO:
https://stackoverflow.com/questions/78274155/adding-fonts-to-distroless-container-for-jasper-reports-in-java-application

I am currently getting following exceptions:
```
java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
        at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
        at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224)
```
or
```
java.lang.RuntimeException: Fontconfig head is null, check your fonts or fonts configuration.
        at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1271)
```

**Comment by bkrajendra** [comment]
Apologies for the confusion.
With detailed debugging, I realized that the distroless image I was using from Azul jdk.
https://hub.docker.com/r/azul/zulu-openjdk-distroless
was not actually a google distroless image, they are using scratch as the base image. hence do not have fonts or fontconfig.

After using:
FROM gcr.io/distroless/java17-debian12:latest
my issue with the application not recognizing fonts in container is resolved.
