### ISSUE TITLE
Download packages more robustly

### ISSUE THREAD

**Issue by drigz** [GoogleContainerTools/distroless#153]
Bazel's downloader is fairly robust: when you use a 'mirror.bazel.build' URL with `http_archive`, you can be confident it will not error out when fetching. However, as dpkg_parser.py uses urllib2 directly, it doesn't take advantage of this reliability.

From skimming #72, it seems like work is underway to allow fixing a package version, and hosting it in a mirror. It would be good to take advantage of Bazel's downloader as part of this redesign.

For example, one error we've seen in CI:

```
ERROR: error loading package 'src/docker': Encountered error while reading extension file 'file/packages.bzl': no such package '@package_bundle//file': dpkg_parser command failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kbuilder/.cache/bazel/_bazel_kbuilder/external/dpkg_parser/file/dpkg_parser.par/__main__.py", line 188, in <module>
  File "/home/kbuilder/.cache/bazel/_bazel_kbuilder/external/dpkg_parser/file/dpkg_parser.par/__main__.py", line 79, in main
  File "/home/kbuilder/.cache/bazel/_bazel_kbuilder/external/dpkg_parser/file/dpkg_parser.par/__main__.py", line 107, in download_dpkg
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 578, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 632, in _read_chunked
    raise IncompleteRead(''.join(value))
httplib.IncompleteRead: IncompleteRead(4096 bytes read)
 (/home/kbuilder/.cache/bazel/_bazel_kbuilder/external/dpkg_parser/file/dpkg_parser.par --package-files /home/kbuilder/.cache/bazel/_bazel_kbuilder/external/debian_stretch/file/Packages.json,/home/kbuilder/.cache/bazel/_bazel_kbuilder/external/debian_stretch_backports/file/Packages.json --packages libpython2.7 --workspace-name package_bundle)
```

**Comment by MarkusTeufelberger** [comment]
That work is mostly finished in https://github.com/mgit-at/rules_pkg. I'm just waiting for a more permanent place to put this ruleset to iterate over it a bit more (Bazel is a bit of a moving target at the moment) before making it more public.

**Comment by drigz** [comment]
Since we are only downloading a single .deb, I decided to use `http_file` directly, eg:

```
http_file(
    name = "libpython_2_7",
    sha256 = "032647c0cff6788b0d813f45e848a467f02090f358c7e056767cec041eedc3fa",
    urls = [
        "http://ftp.de.debian.org/debian/pool/main/p/python2.7/libpython2.7_2.7.13-2+deb9u2_amd64.deb",
        "http://ftp.uk.debian.org/debian/pool/main/p/python2.7/libpython2.7_2.7.13-2+deb9u2_amd64.deb",
        "http://ftp.us.debian.org/debian/pool/main/p/python2.7/libpython2.7_2.7.13-2+deb9u2_amd64.deb",
        "http://ftp.ca.debian.org/debian/pool/main/p/python2.7/libpython2.7_2.7.13-2+deb9u2_amd64.deb",
    ],
)
```

This was much easier than migrating to rules_pkg.

**Comment by MarkusTeufelberger** [comment]
I didn't know that this was only about a single file.

Just make sure to also either include a link to the archive mirror or to host the file yourself too, official Debian mirrors are a moving target.

**Comment by drigz** [comment]
Thanks for the tip!

**Comment by mstump** [comment]
Any progress on this item? We're close to abandoning bazel for container builds because it's proving to be unreliable in production.

**Comment by MarkusTeufelberger** [comment]
If downloading pakages from public mirrors is unstable for you, you might want to host them on a local mirror anyways. I didn't move forward a lot with the "native" (skylark) implementation, since Bazel wants to move to a "lockfile" style approach sooner or later and I want to wait for it to happen before I invest time in building infrastructure and tooling around something that could be obsoleted upstream in a few weeks or months.

**Comment by drigz** [comment]
@mstump How many dependencies do you have, and how often do they change? We only have one at the moment, but we haven't seen any related build failures since moving to `http_file`:

```
http_file(
    name = "libpython_2_7",
    sha256 = "032647c0cff6788b0d813f45e848a467f02090f358c7e056767cec041eedc3fa",
    urls = [
        "http://ftp.de.debian.org/debian/pool/main/p/python2.7/libpython2.7_2.7.13-2+deb9u2_amd64.deb",
        "http://snapshot.debian.org/archive/debian/20171129T213627Z/pool/main/p/python2.7/libpython2.7_2.7.13-2+deb9u2_amd64.deb",
    ],
)
```

If it's impractical to maintain the `http_file` rules manually, you could try using [rules_pkg](https://github.com/bazelbuild/rules_pkg) to automate it.

**Comment by Globegitter** [comment]
Seems there is now https://github.com/bazelbuild/rules_pkg as an official repository rule - giving it a spin myself now.

**Comment by MarkusTeufelberger** [comment]
Yes, those are the scripts that I migrated over there a while ago - still waiting for the final lockfile design/support in Bazel to do a bigger overhaul and (hopefully) write most of it all in native skylark/starlark.

Feedback is more than welcome, I didn't work on it lately but can catch up and improve if necessary.

**Comment by tmc** [comment]
@MarkusTeufelberger could you provide an update here -- can you point to the lockfile plans you mentioned?

**Comment by MarkusTeufelberger** [comment]
There was discussion a while ago to make Workspace rules more dynamic (e.g. just describe the location of a git repository) and add support for lockfiles (e.g. the commit hash would be either taken from this lockfile, or the latest one would be written to it, if it isn't in there yet).

It is still in "draft" or "under review" state here at https://github.com/bazelbuild/proposals ("A Brave New World for the Bazel WORKSPACE File" and the followup "Extending the design of WORKSPACE files").

**Comment by donmccasland** [comment]
This seems like a bug more appropriate for the rules_docker project: https://github.com/bazelbuild/rules_docker
