### ISSUE TITLE
MODULE_NOT_FOUND when starting any node application based on latest distroless images

### ISSUE THREAD

**Issue by ggobbe** [GoogleContainerTools/distroless#1532]
**Describe the bug**
We are using `gcr.io/distroless/nodejs20-debian12:nonroot` as our runtime base image. 

Yesterday, a new image was published for this tag. 

Since then, anything we are running on top of it, is failing with the following error:

```
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/home/node/api/src/main.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: ]
}

Node.js v20.11.1
```

**To Reproduce**
- Build image using `FROM gcr.io/distroless/nodejs20-debian12:nonroot`
- Run it
- It fails

**Expected behavior**
It should start.

**Console Output**
```
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/home/node/api/src/main.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: ]
}

Node.js v20.11.1
```

**Additional context**
N/A

**Comment by ajzo90** [comment]
Perhaps related: I'm noticed issues with `gcr.io/distroless/base-debian12:debug` from yesterday, where we got permission problems when creating/reading directories stopping our application to boot. Just started investigating.

**Comment by ggobbe** [comment]
Using the `/app` directory instead of `/home/node` resolves the issue.

**Comment by loosebazooka** [comment]
Yeah I'm going to revert https://github.com/GoogleContainerTools/distroless/pull/1533

**Comment by loosebazooka** [comment]
I think our "differ" wasn't checking file permissions... that may have lead here. Give it a few hours and the new images should be available

**Comment by ggobbe** [comment]
As the change got reverted, I'll close the issue. Thanks

**Comment by loosebazooka** [comment]
Thanks for reporting.turns out our differ was insufficient. Were remediating this now
