### ISSUE TITLE
Reduce nodejs image size by removing /nodejs/include directory

### ISSUE THREAD

**Issue by pkwarren** [GoogleContainerTools/distroless#1548]
**Describe the bug**
Distroless nodejs images currently include the `/nodejs/include` directory (55.4M). A large portion of this is `/nodejs/include/node/openssl` (53.9M) which includes include files for multiple architectures and variants.

**To Reproduce**
* Pull `gcr.io/distroless/nodejs20-debian12:latest` or `gcr.io/distroless/nodejs20-debian12:debug` images:
```
gcr.io/distroless/nodejs20-debian12                latest            7fc7b55da7d5   N/A              181MB
gcr.io/distroless/nodejs20-debian12                debug             8f8496cf32e2   N/A              183MB
```

* Examine the size of the `/nodejs/include` directory within the container. Note that it makes up ~30% of the overall image size even though a compiler is not shipped in the image to use the include files.

**Expected behavior**
Either the nodejs images should omit the `/nodejs/include` directory or provide an image with a different tag to allow users to reduce the size of their nodejs images.

**Console Output**
```
$ docker run --rm --entrypoint sh -it gcr.io/distroless/nodejs20-debian12:debug
/ # du -sh /nodejs/include/
55.4M	/nodejs/include/
```

**Additional context**
n/a

**Comment by loosebazooka** [comment]
Sounds reasonable. Can you point to some documentation about the include directory?

**Comment by omBratteng** [comment]
@loosebazooka I have created a draft #1597

**Comment by daaain** [comment]
I checked that the PR referenced above was merged in May, but I just built an image using gcr.io/distroless/nodejs22-debian12:nonroot ([9f0d01f30f68](https://console.cloud.google.com/artifacts/docker/distroless/us/gcr.io/nodejs22-debian12/sha256:9f0d01f30f6899ac92abb0cba7d394320167f426687eaafd90f2293c97534ee6?inv=1&invt=Abd8XQ)) with a standalone Next.js app, was wondering why it's still 240.03 MB and apparently the Node.js layer is still 114.09 MB.

What else needs to happen for these changes to be reflected in the images on gcr.io?

![image](https://github.com/user-attachments/assets/b2418c31-af0f-49f1-b6ae-7bc6199a8c9b)

**Comment by omBratteng** [comment]
@daaain the nodejs binary itself is about ~114 MB

```
❯ /bin/ls -la
total 111792
drwxr-xr-x. 2 root root       120 Sep 17 17:09 .
drwxr-xr-x. 6 root root       180 Sep 17 17:09 ..
lrwxrwxrwx. 1 root root        45 Sep 17 17:09 corepack -> ../lib/node_modules/corepack/dist/corepack.js
-rwxr-xr-x. 1 root root 114472472 Sep 17 17:09 node
lrwxrwxrwx. 1 root root        38 Sep 17 17:09 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxrwxrwx. 1 root root        38 Sep 17 17:09 npx -> ../lib/node_modules/npm/bin/npx-cli.js
```

<img width="717" alt="image" src="https://github.com/user-attachments/assets/7df1fcc3-d2fe-4bc6-80a8-c5e767ace7b0">

If you use [dive](https://github.com/wagoodman/dive), you can also see that the layer that adds 115MB only adds the license and node binary.
Not much that can be reduced there.

<img width="1840" alt="image" src="https://github.com/user-attachments/assets/1c88b0f3-9a0e-45b9-91a2-99f2375f0ad6">

Do you compile next.js into [standalone mode](https://nextjs.org/docs/pages/api-reference/next-config-js/output#automatically-copying-traced-files)? It could reduce the bundle size a little bit.
> This will create a folder at `.next/standalone` which can then be deployed on its own without installing `node_modules`.

**Comment by daaain** [comment]
Oh right, I tried to use dive, but it doesn't seem to work on my Mac since I switched docker to use containerd.

I'm using standalone mode, so the actual app and dependencies are only 24 MB (you can see in the screenshot as the next layer), so that's why I was wondering where 90% of the image size is coming from.

I thought I could get the image using distroless below what's possible with alpine after reading [this post](https://xeiaso.net/notes/2024/small-nextjs-images/), but maybe not.

**Comment by omBratteng** [comment]
I think alpine compiles their node version which some different settings than the official nodejs binary.

**Comment by daaain** [comment]
I'm trying to research now what's inside that massive binary and wondering if it has all the dependencies statically linked, in which case the rest of the image could jettison SSL and C libs?

This is maybe a bit off topic in this issue, but maybe compiling a Node [Single executable application](https://nodejs.org/api/single-executable-applications.html#single-executable-applications) and using base-nossl-debian12 as base could be an alternative way to go?

**Comment by omBratteng** [comment]
I wouldn’t worry that much about the size of the base image. If multiple images ise the same base image, it’s kinda “cached” on the system as long as they all use the same layers

**Comment by omBratteng** [comment]
Could probably reduce the binary size if we’d compile the binary to be specific for debian.

But I think distroless just wants to use original releases, @loosebazooka could probably verify this statement

**Comment by loosebazooka** [comment]
If it doesn't complicate the could too much it'd probably be fine. But we don't really build anything else from source so it would be a one off. Wonder if someone at canonical, red hat or chainguard might be more appropriate for this.

**Comment by omBratteng** [comment]
It'll probably complicate a bit, and could break things, so probably not really worth it

**Comment by daaain** [comment]
I don't think it's worth the complexity building from source and / or trying to remove something someone at some point will miss, to me there are 2 opportunities:
1. find a leaner build upstream (that is still complete, but maybe doesn't have support for other distros, etc)
2. remove library packages from the OS if they are statically linked and included in the binary

**Comment by omBratteng** [comment]
Yeah, don't think it's worth it. It's better to use the official built version, that way we don't need to maintain it.

And I think this issue can be closed, as the image no longer contains the include directory.
