### ISSUE TITLE
Add a Ruby distroless?

### ISSUE THREAD

**Issue by raliste** [GoogleContainerTools/distroless#156]
You already have a ruby image at https://github.com/GoogleCloudPlatform/ruby-docker. Any plans to create a distroless version?

**Comment by dlorenc** [comment]
No plans for now. We're not planning on adding anymore images to this repo.

**Comment by Atem18** [comment]
Someone made one : https://github.com/unasuke/distroless-ruby

Does not seems that much difficult to do it.

**Comment by Nakilon** [comment]
@Atem18  according to `docker image inspect` it's larger than ruby-alpine -- 59mb vs 56mb. Then what's the point?

**Comment by Atem18** [comment]
@Nakilon security ?

**Comment by loosebazooka** [comment]
I think alpine also uses a different libc (musl)? That could potentially cause compatibility issues with binaries you include in the build (that were not compile against it)?
https://www.musl-libc.org/faq.html

**Comment by Atem18** [comment]
Yes, there is also that and that matter way more than 3MB of disk space

**Comment by dirkjonker** [comment]
Using musl instead of glibc can make quite a big difference in performance. But try for yourself to see what works best.
