### ISSUE TITLE
`static` tag is based on Debian 11

### ISSUE THREAD

**Issue by m-barthelemy** [GoogleContainerTools/distroless#1570]
Currently, the `static` tag points to images based on Debian 11.
Debian 11 will reach its end of support in July 2024.
Is there a plan to update this tag so that it refers to images built using Debian 12?

Reference :https://github.com/GoogleContainerTools/distroless/blob/22cd078ffac95e35015f052c95447afd0d2818e7/BUILD#L16

**Comment by loosebazooka** [comment]
yeah we need to update this. I'll do that soon.

**Comment by loosebazooka** [comment]
should be updated!
