### ISSUE TITLE
Google Cloud Container Registry will be closed

### ISSUE THREAD

**Issue by eggplants** [GoogleContainerTools/distroless#1612]
Google Cloud Container Registry will be closed after March 18, 2025.

https://cloud.google.com/container-registry/docs/resources
> Container Registry is deprecated and scheduled for shutdown. Effective May 15, 2024, Artifact Registry hosts images for the gcr.io domain in projects without previous Container Registry usage. After March 18, 2025, Container Registry will be shut down.

Do you plan to migrate to a container registry like Artifact Registry, DockerHub or GitHub container registry?

**Comment by loosebazooka** [comment]
Yeah distroless will continue to work on artifact registry with the gcr.io address.
