### ISSUE TITLE
gcr.io no updated tags anymore

### ISSUE THREAD

**Issue by reitzmichnicht** [GoogleContainerTools/distroless#1617]
**Describe the bug**
I checked only the java images, but it looks like all those latest, non-root amd-64 tags are missing now since may.
https://console.cloud.google.com/gcr/images/distroless/global/java-base-debian12

**Expected behavior**
New pushed layers have also updated tags assigned to it

**Comment by loosebazooka** [comment]
Those tags seem to still exist. There just haven't been any updates since then as we are fixing some access to the snapshot server.

**Comment by reitzmichnicht** [comment]
This means there are no security updates provided since may, does not improve my trust on relying on these images :(
