### ISSUE TITLE
go needs libstdc++

### ISSUE THREAD

**Issue by mattmoor** [GoogleContainerTools/distroless#162]
I'm getting increasing reports of this lib missing from folks using `go_image` ([example](https://github.com/bazelbuild/rules_docker/issues/315)).

Luckily `rules_go` now supports `pure = "on"`, but we should get the base image fixed for the default case.

Assigning to @dlorenc to triage.

**Comment by james-r-smith** [comment]
I'm using the base image and getting the same error referenced. Is this being worked on, and what is a temporary work-around on the client-side? Thanks!

**Comment by justinsb** [comment]
The cc image does have libstdc++ and I was able to switch my base to `distroless/cc` and it "worked for me".

I'm not using the `go_image` task (I use `container_image` directly), but `go_image` does have a `base` field which might work.

**Comment by donmccasland** [comment]
Okay, I need some opinions here.  If I'm reading things right, by design neither base nor static should include a bunch of shared libraries.  And since there is a work around for projects needing that library using distroless/cc I'm thinking we should close this won't fix.

**Comment by jayeye** [comment]
Three years later, the problem persists.

**Comment by prestonvanloon** [comment]
@loosebazooka could you kindly provide information why this issue was closed? Has it been fixed?

**Comment by loosebazooka** [comment]
Just bug bankruptcy. I will reopen since it appears people are interested in it.

**Comment by loosebazooka** [comment]
okay so there are solutions for this that make sense. If you're using `go_image`, update the base to use distroless/cc.
