### ISSUE TITLE
Tracking bug to migrate to AR

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/distroless#1630]
Should have no user impact. But users should comment here if they have breakages that can be attributed to this.

- All image references should remain the same (ex: gcr.io/distroless/static). 
- authentication should not be required to pull images.

**Comment by lathama** [comment]
Would it be nice to explain to the users why there is a migration and what AR means in this context.

**Comment by loosebazooka** [comment]
Yup, good point. Context: https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr

**Comment by loosebazooka** [comment]
Completed

**Comment by polarathene** [comment]
What is the new home for distroless? I only briefly glanced over the linked context where it mentions `gcr.io` will shutdown completely by March 2025?

There was a table showing `gcr.io` being replaced by `pkg.dev` but that doesn't seem to work?:

```console
$ docker pull pkg.dev/distroless/static
Using default tag: latest
Error response from daemon: error unmarshalling content: invalid character '<' looking for beginning of value
```

**Comment by lathama** [comment]
To use pkg.dev you may need to gcloud auth first. the `<` is likely an auth issue. gcr.io will live on after the shutdown as I read.

**Comment by loosebazooka** [comment]
Distroless will continue to use gcr.io

**Comment by polarathene** [comment]
@loosebazooka ah ok, so the mention about `gcr.io` shutdown in 2025 won't affect distroless? Is that because of `pkg.dev` apparently requiring auth like @lathama mentioned?

I'm not that familiar with either registry, I just wanted to double check if distroless was going to be offered at AR publicly and eventually drop `gcr.io`, but if `gcr.io` will continue to be reliable for years no worries 👍 Thanks!

**Comment by loosebazooka** [comment]
`gcr.io/distroless` is now served by the AR infrastructure. The GCR infra is shutting down but the domain `gcr.io` will continue to served by AR.
