### ISSUE TITLE
java21-debian12 missing jdk.random

### ISSUE THREAD

**Issue by andreas-ajaib** [GoogleContainerTools/distroless#1636]
**Describe the bug**

Getting this error when running RandomGenerator using `java21-debian12` image.
```
stack_trace	
java.lang.IllegalArgumentException: No implementation of the random number generator algorithm "L128X1024MixRandom" is available
	at java.base/java.util.random.RandomGeneratorFactory.findProvider(Unknown Source)
	at java.base/java.util.random.RandomGeneratorFactory.factoryOf(Unknown Source)
	at java.base/java.util.random.RandomGeneratorFactory.of(Unknown Source)
```

**To Reproduce**

1. Implement this kind of code
```java
final RandomGenerator randomGenerator = RandomGeneratorFactory.of("L128X128MixRandom").create();
```
2. ~~Build~~ Run the app using `gcr.io/distroless/java21-debian12`

or

1. Clone this https://github.com/andreasarf/docker-demo/tree/main
2. Run `docker-compose up`

**Expected behavior**

Should support RandomGenerator algorithms as specified [here](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/random/package-summary.html#algorithms)

**Console Output**
If applicable, add information from your container run

**Additional context**

Working fine on the java17 image, which could be compared here: https://github.com/andreasarf/docker-demo/tree/java17

**Comment by andreas-ajaib** [comment]
I see Java 21 images are using temurin, whereas Java 17 images are using openjdk. This might be the root cause.
https://github.com/adoptium/temurin-build/issues/2843

**Comment by andreasarf** [comment]
Hi @loosebazooka any update on this? at least can you confirm that it will be fixed or not? i need to plan accordingly the release of my app. if not, that's ok. i will stick to the Java 17 or find another Java 21 image.

**Comment by andreas-ajaib** [comment]
Hi @loosebazooka any update on this? at least can you confirm that it will be fixed or not? i need to plan accordingly the release of my app. if not, that's ok. i will stick to the Java 17 or find another Java 21 image.

**Comment by loosebazooka** [comment]
We'll probably continue to use temurin.

**Comment by loosebazooka** [comment]
And will probably move all Java images to temurin on the next cycle (you'll still have Debian jdk 17 on debian 12)

**Comment by andreas-ajaib** [comment]
Thanks for the confirmation. But do you think/plan to use workaround like creating your own custom JRE, like https://github.com/adoptium/temurin-build/issues/2883#issuecomment-1598365621?

**Comment by loosebazooka** [comment]
Unlikely, It sounds like they think this is a problem and maybe they'll just fix it.

**Comment by slachiewicz** [comment]
Maybe it's related to this report https://bugs.openjdk.org/browse/JDK-8330005
