### ISSUE TITLE
README.md Link for including debian packages 

### ISSUE THREAD

**Issue by rv-cturley** [GoogleContainerTools/distroless#164]
Link for including debian packages links to another repo with no information on how to preform the specified task.

Ln# 100
`* [Including debian packages](https://github.com/bazelbuild/rules_docker#docker_build-1)`

**Comment by r2d4** [comment]
The name of the rule has changed to `container_image` so the link is broken

It should be https://github.com/bazelbuild/rules_docker#container_image-1

PRs happily accepted

**Comment by lathama** [comment]
I just checked and line 119 in the README.md is updated. please close.

**Comment by chanseokoh** [comment]
Yeah, I remember I fixed this in #280 (https://github.com/GoogleContainerTools/distroless/pull/280/files#diff-04c6e90faac2675aa89e2176d2eec7d8R119).
