### ISSUE TITLE
Openssl vulnerabilities reported for cc-debian12

### ISSUE THREAD

**Issue by ivan-kiselev** [GoogleContainerTools/distroless#1655]
- [x] I have read the [SECURITY.md](https://github.com/GoogleContainerTools/distroless/blob/main/SECURITY.md)
- [x] I understand that this repo tracks debian package releases and cannot fix debian CVEs on its own
- [x] this CVE shows a fix is available in the appropriate debian version (buster, bullseye) and channel (main, security) *and* it has been more than 48 hours.

Security tooling reports 2 high level vulnerabilities when run against `gcr.io/distroless/cc-debian12`, with suggested fix of upgrading openssl to [3.0.14-1~deb12u1](https://packages.debian.org/source/stable/openssl), which is marked as "stable" on https://tracker.debian.org/pkg/openssl.

Aforementioned security tooling has been run against [this image](https://console.cloud.google.com/artifacts/docker/distroless/us/gcr.io/cc-debian12/sha256:061e7bf5e9352f1c417859037d6885e90a0906e4d2165d578aabfe33aab344d6)

**Comment by loosebazooka** [comment]
should be fixed on the next build (after #1657). Our updater was failing on some debian11 dependencies (but those are now all removed).
