### ISSUE TITLE
docker image tag

### ISSUE THREAD

**Issue by tuananh** [GoogleContainerTools/distroless#166]
can we have tags for all the docker images?

example: if i want to use an older version image of node (8.9.0) instead of the latest 8.9.1

**Comment by r2d4** [comment]
I don't think we're planning to publish and maintain multiple configurations of these images at the moment. 

You can follow the example of how we've built these images and build them with the specific dependencies that you need.

**Comment by tuananh** [comment]
@r2d4 would you take a PR to build and test docker images on git tags? like in [bitnami-docker-node](https://github.com/bitnami/bitnami-docker-node/blob/master/circle.yml)

**Comment by dlorenc** [comment]
Dup of #123
