### ISSUE TITLE
Is there any way to get a shell from running container?

### ISSUE THREAD

**Issue by itmard** [GoogleContainerTools/distroless#168]
Hi there,
Sometimes we need to get bash or ssh into a running container for debugging . Is it possible  to do this with these images ?

**Comment by mattmoor** [comment]
The `:debug` tagged images container `busybox`, so you can `--entrypoint=sh`, but the `:latest` images drop this to bias towards minimal containers in production.

**Comment by itmard** [comment]
Thanks for your reply. So there is no busybox or any kind of shell in
production images?

**Comment by mattmoor** [comment]
Not currently, no.

**Comment by dubek** [comment]
@itmard You can copy the busybox into a running container and then run it there. If you have a running container named `mycontainer1`, you can run:

```
docker cp /path/to/busybox mycontainer1:/sh
docker exec -it mycontainer1 /sh
```

The busybox executable can be extracted from the `busybox:latest` docker image, for example. Make sure it is statically linked:

```
$ file busybox
busybox: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

**Comment by dlorenc** [comment]
Closing as this looks addressed. Also see https://github.com/kubernetes/features/issues/277 for another take on a similar use-case.
