### ISSUE TITLE
How import properly pip dependency

### ISSUE THREAD

**Issue by Ducatel** [GoogleContainerTools/distroless#171]
Hi, 
I try to make my first image build on distroless.
I wish use the python3 image with a docker multistage build.

What I did :
```Dockerfile
FROM python:3.5 AS build-env

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --target=./ --no-cache-dir -r requirements.txt
COPY test.py ./
COPY src ./src/

################################################

FROM gcr.io/distroless/python3
COPY --from=build-env /usr/src/app /app
WORKDIR /app

CMD ["test.py"]
```
It's working but my source file `test.py` is mix with the pip dependency.
If I set the target of pip in `--target=./site-packages`, it will be copied in output image but cannot be used by my `test.py`.

I must copy my `site-packages` content to `/usr/lib/python3.5` ?

So how I can use pip dependency "properly" ? 
Thanks in advance for your help

Ps: There is any plan to upgrade python from 3.5 to 3.6 ?

**Comment by akravetz** [comment]
It's pretty straight forward using the Bazel build method: https://github.com/bazelbuild/rules_python

**Comment by Ducatel** [comment]
All of my ci/cd pipelines are built around docker file. So l prefer to use native Docker solutions. 

Also the python rules are in alpha and I need to use production ready solution.

**Comment by jiel** [comment]
Hello @Ducatel 

I use this:
```dockerfile
FROM gcr.io/distroless/python3
COPY --from=build-env /app /app
COPY --from=build-env /usr/local/lib/python3.5/site-packages /usr/local/lib/python3.5/site-packages

WORKDIR /app
ENV PYTHONPATH=/usr/local/lib/python3.5/site-packages
```
Hope this help.

**Comment by Ducatel** [comment]
Thanks @jiel 
Your solution is quiet similar to what I did before.
So maybe there is no better/proper solution for using pip

**Comment by tejal29** [comment]
yes.  We dont have docker native solutions.
We support bazel rule for apt package manager in https://github.com/GoogleContainerTools/base-images-docker/blob/master/package_managers/download_pkgs.bzl

Untill python_rules are stable, you can write a similar rule for installing from pip for a given list of python packages.
However, using the python_rules is the way to go.

**Comment by tejal29** [comment]
Closing this for now. Please open if you have questions.
