### ISSUE TITLE
Base debian12 crashes when binary is static linked with libgcc on ppc64le

### ISSUE THREAD

**Issue by zgooner** [GoogleContainerTools/distroless#1716]
**Describe the bug**
When compiling "hello world" type of program with static linked libgcc on ppc64le platform program crashes with message **Segmentation fault**

**To Reproduce**
Create image with gcr.io/distroless/base-debian12 as base image and run binary with static linked libgcc.

**Expected behavior**
Program should run but it crashes before it gets to the main function.

**Console Output**
```
/ $ ./tmp/test
Segmentation fault
```

**Comment by zgooner** [comment]
I executed program on `debian:12` and it gives the same output as distroless debian(segfault).

**Comment by zgooner** [comment]
It is worth to mention that I compile my binary on Ubuntu 20 and then it gets copied to the container.

**Comment by loosebazooka** [comment]
Sorry but this doesn't appear like a Distroless problem, it could be a difference in the systems you are using to build and deploy (either a libgcc/glibc version or the underlying architecture).
