### ISSUE TITLE
package_manager: handling transitive dependencies

### ISSUE THREAD

**Issue by kevingessner** [GoogleContainerTools/distroless#181]
Given this (incomplete) WORKSPACE

```
dpkg_list(
    name = "package_bundle",
    packages = [
        "curl",
    ],
    # etc
)

container_pull(
    name = "distroless_cc",
    registry = "gcr.io",
    repository = "distroless/cc",
    digest = "sha256:ddab43453dc99454b6a28aba1a2c3c28f508f603359a50a977c37dfe64c15c39",
)
```

and BUILD

```
container_image(
   name = "broken_curl",
   base = "@distroless_cc//image",
   debs = [packages["curl"]],
)
```

The image generated as `//:broken_curl` doesn't work:

```
$ > bazel run lib/docker:broken_curl && docker run bazel/lib/docker:broken_curl curl -h
# [snip]
curl: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

This error is because the `curl` package has [required dependencies](https://packages.debian.org/stretch/curl), but `dpkg_list` doesn't install them.  Instead, I have to track down the dependencies (as well as their dependencies, and so on), and manually add them to both `dpkg_list`and the `container_image`.  It's a pain, and I don't know if I've missed any until it fails at runtime.

`dpkg_list` should automatically resolve those dependencies.  Adding `packages["foo"]` to an image should automatically add not only `foo` but all of its transitive dependencies without an extra manual step.  This matches the behavior of `apt` and makes for a smoother workflow.

**Comment by MarkusTeufelberger** [comment]
It is not clear which packages would be installed if dependencies (only required ones? what about optional or recommended ones?) are automatically added. While that might match the behaviour of `apt`, there are downsides and there's a reason why `apt` and `dpkg` both exist (and the former is just a fancy way of calling the latter with a few more things around it).

If you need help with finding/listing dependencies, check out http://collab-maint.alioth.debian.org/debtree/ for example.

**Comment by kevingessner** [comment]
That makes sense.  In that case, `package_manager` should provide apt-like behavior as well as the current dpkg installation.  That is, a configurable way to install a package and its dependencies, taking into account exclusions, optionals, etc).  It would be a "convenience wrapper" around `dpgk_list` but I think it would see a lot of adoption -- manually dependency management feels like the corner case, compared to an apt-like "install the package and just make sure it works".  Would you be open to that as an extension?

**Comment by MarkusTeufelberger** [comment]
I am not a maintainer or owner of this repository, so I can't speak for their project's direction. Personally I am opposed to magic tools and view the explicitness of Bazel as an advantage. Implicitly solving a dependency tree (there might be many more than one solution by the way) for every build doesn't sound like a good thing to do, just to save someone to look up explicit dependencies once.

**Comment by tejal29** [comment]
Hi @kevingessner, Sorry for the delay,
We have a set of other rules which will install packages for apt_get and resolve deps.
You can use the same rule 
```
download_pkgs(
    name = "download_curl",
    additional_repos = [
        "deb http://ftp.de.debian.org/debian jessie main",
    ],
    image_tar = "@distroless_cc//image.tar",
    packages = [
        "curl",
    ],

install_pkgs(
    name = "install_curl",
    image_tar = "@distroless_cc//image.tar",
    installables_tar = ":download_curl.tar",
    output_image_name = "cc_with_curl",
)

``` 

We also have  macro which does all of this:
```
bootstrap_image_macro(
    name = "cc_curl",
    date = "2018/05/18",
    image_tar = "@distroless_cc//image.tar",
    output_image_name = "cc_curl",
    packages = [
        "curl",
    ],
    store_location = "cc_curl/builds",
)
```
The store_location/<date>/ is where all the download package will be cached. When you build the image next time with the same date, the rule will install the packages from the downloaded store.

**Comment by tejal29** [comment]
These rules are in https://github.com/GoogleContainerTools/base-images-docker. Will Add documentation to explain these.

**Comment by tejal29** [comment]
Answered.

**Comment by kevingessner** [comment]
So great to know -- thanks!
