### ISSUE TITLE
About docker `HEALTHCHECK`

### ISSUE THREAD

**Issue by pwob** [GoogleContainerTools/distroless#183]
How do you guys enabled healthcheck in multibuild docker using distroless? Currently it is not working for us because obviously `curl` is not available in distroless image.

**Comment by dlorenc** [comment]
I'm not sure I understand the question. How is curl related to HEALTHCHECK? What do you mean by "multibuild"? Can you share an example of what you're trying to do without distroless/bazel?

**Comment by dlorenc** [comment]
Closing. Please reopen with more info.

**Comment by Junkern** [comment]
I just stumbled upon the `distroless` docker images and the same question also popped into my mind.

We are deploying our docker images using `docker-compose` (for exposting ports, configs, secrets and so on) and also utilize the [healthcheck](https://docs.docker.com/compose/compose-file/#healthcheck), so that our swarm knows whether a replica is healthy or not

Our healthcheck_command is: `test: ["CMD", "curl", "-f", "http://localhost:10000"]`

I would like to use the distroless images (for several reasons), but wow would the healthcheck work with a `distroless` image, as `curl` is not available there? How do/would you solve that?

**Comment by Junkern** [comment]
@dlorenc

**Comment by pwob** [comment]
@Junkern For now we solved it by making a service (Kubernetes) that calls an endpoint of the api `/healthcheck` in a certain interval.

**Comment by barmic** [comment]
After the reading of this blog post https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr/, I create a custom tool write in `go` to make only my check (and build it with a docker build stage).

**Comment by verglor** [comment]
@pwob @Junkern You can add 84kB busybox wget to the image and use it [instead of curl](https://stackoverflow.com/a/47722899/489790):
```Dockerfile
FROM busybox AS builder

ARG BUSYBOX_VERSION=1.31.0-i686-uclibc
ADD https://busybox.net/downloads/binaries/$BUSYBOX_VERSION/busybox_WGET /wget
RUN chmod a+x /wget

FROM gcr.io/distroless/java

COPY --from=builder /wget /usr/bin/wget
```

@barmic Custom healthcheck in higher language (go, java, ...) even built into native binary is at least several MB large and probably overkill for simle HTTP check.

**Comment by barmic** [comment]
@verglor My go binary is huge indeed (about 7MB), but comparing to JDK isn't noticeable (~3% of total size) and ensure that can't be used to call another service. If I want reduce the size I can use java, I have already the JDK so one executable class/jar  should fit in some KB.

**Comment by madduci** [comment]
The solution of @verglor unfortunately doesn't work in distroless/java:

```
docker inspect $container --format "{{ (index (.State.Health.Log) 0).Output }}"
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

**Comment by mabrarov** [comment]
Hi @madduci,

Could the way you define `HEALTHCHECK` in you `Dockerfile` be the reason Docker trying to run `/bin/sh`?

[Dockerfile reference. HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck):

> The command after the `CMD` keyword can be either a shell command (e.g. `HEALTHCHECK CMD /bin/check-running`) or an **exec** array (as with other Dockerfile commands; see e.g. `ENTRYPOINT` for details).

Can you try this (does it work for your case)?

```
HEALTHCHECK --interval=30s \
            --timeout=5s \
            CMD ["/usr/bin/wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
```

**Comment by mabrarov** [comment]
Hi @madduci,

Regarding [my previous comment](https://github.com/GoogleContainerTools/distroless/issues/183#issuecomment-823181507) - it looks like HEALTHECHECK should return predefined exit codes:

[Dockerfile reference. HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck):

> The command’s exit status indicates the health status of the container. The possible values are:
> 
> * 0: success - the container is healthy and ready for use
> * 1: unhealthy - the container is not working correctly
> * 2: reserved - do not use this exit code

This means that we cannot rely on exit code of wget and should treat any non-zero exit code of wget as 1. This definitely requires either a custom binary or a shell script. You can try to create symlinks for the downloaded BusyBox like I do it in [mabrarov/docker-compose-init-container](https://github.com/mabrarov/docker-compose-init-container/blob/master/init-image/src/main/resources/Dockerfile#L7).

**Comment by madduci** [comment]
Hi @mabrarov ,

thank you for your reply, I will try the suggestion.
It's interesting how with docker-compose, I'm able to write the following:

```
healthcheck:
  test: [ "CMD", "/usr/bin/wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health" ]
  interval: 15s
  timeout: 3s
  retries: 5
  start_period: 30s
```

and it just works, but I can't understand why the command issued in the `Dockerfile `isn't, triggering the `/bin/sh: not found` error

**Comment by barmic** [comment]
Since my last comment, I change of method. Now I use a custom java tool: https://gist.github.com/barmic/a12c5256f735f4748e3a6f511367407e

This give a very simple tool of 4KB without security issue.

**Comment by mabrarov** [comment]
@barmic,

There can be issues with [custom Java tool](https://github.com/GoogleContainerTools/distroless/issues/183#issuecomment-823880833):

1. It can be slow at start (taking ~1 sec to start).
1. Java application consumes CPU at the start, i.e. Java startup time heavily depends on CPU.
1. If one uses `JAVA_TOOL_OPTIONS` environment variable to pass JVM options into his Java application, then custom Java tool will pick `JAVA_TOOL_OPTIONS` environment variable too, which seems to be unwanted in most cases (e.g. when `JAVA_TOOL_OPTIONS` environment variable defines Java heap size).

**Comment by barmic** [comment]
1s to start a jvm? Never in my case (it's about 10 times more quick). I don't know how can compute the load (part of memory page will be shared between 2 jvm, evaluate CPU load will depende of env and CPU,…) probably it can be possible to disable some startup work.

You can control the env of this tool as you want, it's not a problem.

For my case, the security issue is widely more important than CPU consuming.

**Comment by mabrarov** [comment]
Hi @barmic,

> Never in my case (it's about 10 times more quick)

Have you tried to limit CPU resource for container which uses custom Java tool for health check?

> You can control the env of this tool as you want, it's not a problem.

`JAVA_TOOL_OPTIONS` environment variable is automatically picked by Java. There is no way to define `JAVA_TOOL_OPTIONS` environment variable for passing JVM options into the main Java application and avoid custom Java tool (which is used just for the health check) to pick the same JVM options.

**Comment by mabrarov** [comment]
FYI,

With [powerman/dockerize](https://github.com/powerman/dockerize) 0.14.0+ (refer to [dockerize#103](https://github.com/powerman/dockerize/issues/103)) it's possible to use Dockerize for Docker health check this way:

```
HEALTHCHECK --interval=30s \
            --timeout=5s \
            CMD ["/usr/bin/dockerize", "-timeout", "1s", "-wait", "http://localhost/health", "-exit-code", "1"]
```

I [use Dockerize for Docker health check](https://github.com/mabrarov/docker-compose-init-container/blob/master/docker-compose/docker-compose.yml#L65) in [mabrarov/docker-compose-init-container](https://github.com/mabrarov/docker-compose-init-container) where Dockerize fits well into a case when Distroless Java image is used.

**Comment by starlightromero** [comment]
Hi @barmic,

Would you share your go code and Dockerfile for the custom healthcheck? I'm running into a weird error where my healthcheck works with an alpine base image but not with a distroless image.

```Dockerfile
# syntax = docker/dockerfile:1.2

FROM golang:1.16.6-alpine as base

SHELL [ "/bin/ash", "-eo", "pipefail", "-c" ]

RUN echo "SHA_CRYPT_MIN_ROUNDS=999999999" > /etc/login.defs

RUN --mount=type=secret,id=passwd echo "root:$(cat /run/secrets/passwd)" | chpasswd -c sha512

RUN sed -ni "1p" /etc/passwd && \
    sed -ni "1p" /etc/shadow && \
    sed -ni "1p" /etc/group

FROM golang:1.16.6-alpine as geolocation

WORKDIR /app

COPY geolocation/go.* .

RUN go mod download

COPY geolocation/* .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .

FROM golang:1.16.6-alpine as healthcheck

WORKDIR /app

COPY healthcheck/go.* .

RUN go mod download

COPY healthcheck/* .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .

# FROM gcr.io/distroless/static:nonroot
FROM golang:1.16.6-alpine

COPY --from=base /etc/passwd /etc/passwd
COPY --from=base /etc/shadow /etc/shadow
COPY --from=base /etc/group /etc/group
COPY --from=geolocation /app/geolocation /usr/bin/geolocation
COPY --from=healthcheck /app/healthcheck /usr/bin/healthcheck

USER 1000

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=2 CMD healthcheck

ENTRYPOINT [ "/usr/bin/geolocation" ]

```

**Comment by JULIANCHO923** [comment]
The strategy to have a healthcheck standalone file to validate my app works very well

I based on this post: https://mflash.dev/post/2021/03/01/java-based-health-check-for-docker/


```java
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse.BodyHandlers;

public class HealthCheck {
  public static void main(String[] args) throws InterruptedException, IOException {
    var client = HttpClient.newHttpClient();
    var request = HttpRequest.newBuilder().uri(URI.create("http://localhost/healthcheck")).build();   
    var response = client.send(request, BodyHandlers.ofString());
    if (response.statusCode() != 200) {
      throw new RuntimeException("Healthcheck failed");
    }
  }
}
```

Here is the snippet to the Dockerfile where I'm using the healthcheck file

```dockerfile
FROM gcr.io/distroless/java11-debian11
COPY myapp/src/main/resources/healthcheck/ .
HEALTHCHECK --interval=15s --timeout=10s --start-period=45s --retries=3 CMD ["java", "HealthCheck.java", "||", "exit", "1"]
```
