### ISSUE TITLE
Dockerfiles for non-Bazelish speakers

### ISSUE THREAD

**Issue by DazWilkin** [GoogleContainerTools/distroless#188]
Recommend:
Provide Dockerfiles for distroless images to broaden the understanding of their composition

My colleague introduced me to distroless and I've become convinced to start using these images. For Golang, I've use `FROM: scratch` but distroless provides a consistent base for all runtimes that I use.

One thing I'm challenged by is that there (appear to be no) published Dockerfiles for the images. And so, as I currently have, trying to convert someone else's Golang solution to distroless, I'm hitting errors but unclear what's in the image; the Bazel `BUILD` appears straightforward but it's not a Dockerfile and I assume, like others, that having a more familiar definition to review would help.

I assume (!?) Bazel generates Dockerfiles as an intermediate step. If it does, could we get those posted here to help those who don't speak fluent Bazelish to understand what we're using?

**Comment by MarkusTeufelberger** [comment]
> I assume (!?) Bazel generates Dockerfiles as an intermediate step.

No, it does not, that's the main appeal.

**Comment by salrashid123** [comment]
distrolss uses the [basel/rules_docker](https://github.com/bazelbuild/rules_docker) and the way i understand it, the filesystem and image spec is created out of band, outside of docker.

for example, even an image's manifest is generated by hand here:

- [https://github.com/bazelbuild/rules_docker/blob/master/container/join_layers.py#L73](https://github.com/bazelbuild/rules_docker/blob/master/container/join_layers.py#L73)


FWIW, if you want to build and test, try the ```base``` image as used by golang (in the example below, the ```:debug``` image)

```
bazel build base:debug
bazel run base:debug
```
(you'll see the image locally ```docker images```)
```
$ docker images
REPOSITORY                                    TAG                                                                IMAGE ID            CREATED             SIZE
gcr.io/distroless/base                        debug                                                              393d2aba0075        48 years ago        17.5MB
bazel/base                                    debug                                                              11b6ccfb158f        48 years ago        17.5MB
```

if you want to see the image filesystem using ```:debug``` directly,

```
docker run --entrypoint=sh -ti gcr.io/distroless/base:debug
```

or extract the whole image:
```
docker save gcr.io/distroless/base -o img.tar
```

**Comment by dlorenc** [comment]
Closing, I think this has been explained.
