### ISSUE TITLE
No `/home` Directory

### ISSUE THREAD

**Issue by james-r-smith** [GoogleContainerTools/distroless#190]
I am using a Go package that looks for the `HOME` directory. What's funny is that it's added as an environment variable as `/home`, but there is no `/home` directory. 😅 I thought it's most likely a bug that hasn't been noticed yet. Example shown below.

```
/ # env
HOSTNAME=e337fa5d65df
SHLVL=1
HOME=/home
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/busybox
PWD=/
/ # ls
busybox  dev      etc      lib      lib64    proc     sys      tmp      usr      var
```

**EDIT** : Only tested in `base` image.
**EDIT 2** : Also in `cc` image, which I'm actually now using, as I need the shared libraries that it contains. 😅 Please add to this image if possible. Thanks!
**EDIT 3** : Also in `nodejs` image. I would suggest ensuring all containers have then`/home` directory. Currently, I'm just copying the `/home` directory from the previous Docker build stage.

Tasks:
- [ ] Update passwd_file rule to provide an optional output with homedirs. https://github.com/bazelbuild/rules_docker/pull/407
- [ ] Update rules_docker dep in distroless and add optional homedir 
- [ ] Release distroless debian image.

**Comment by tejal29** [comment]
Thanks @james-r-smith. Taking a look now.

**Comment by tejal29** [comment]
I think the default is set by passwd_entry rule here https://github.com/bazelbuild/rules_docker/blob/4a8d25890a583dd5b30383458a452b6aaa043fe7/contrib/passwd.bzl#L59
This rule should also create the dir.
Will make a change there.

**Comment by tejal29** [comment]
I think this is due to passwd_entry setting default home to "/home"
Combine that with this feature in docker https://github.com/moby/moby/issues/2968
home variable is parsed from /etc/passwd. 
I think the correct fix is to make a dir in same rule.
