### ISSUE TITLE
Reorganize Repository

### ISSUE THREAD

**Issue by dlorenc** [GoogleContainerTools/distroless#197]
This repository currently contains a mixture of images suitable for use in production, experimental images, and tools used to build both of these.

This issue proposes a reorganization of the repository to help make it clear to users which type of image or tool they are using.

AFAIK there are production dependencies on the base and java images. The ca-certs and package_manager rules are also used to build production images.

The rest of the repository is effectively experimental:

Strawman:

base/
java/
cacerts/
package_manager/
experimental/
  /python2.7
  /python3
  /nodejs
  /dotnet
  /busybox

Question: Should cc be in the top level or experimental?

**Comment by tejal29** [comment]
This looks good to me.
Regarding cc, do we know how many people are using it?

Thanks

**Comment by Globegitter** [comment]
@dlorenc @tejal29 what is the reason some of these images are "not suitable" for production? We have been running the python2.7 image (with some extra dependencies on top) now in production for weeks serving millions of requsts.
