### ISSUE TITLE
implicit dependency of docker_rules breaks in host without python3

### ISSUE THREAD

**Issue by raliste** [GoogleContainerTools/distroless#201]
When using distroless on a different workspace such as 

```
load(
    "@distroless//package_manager:package_manager.bzl",
    "dpkg_list",
    "dpkg_src",
    "package_manager_repositories",
)
```

the implicit dependency of docker_rules breaks the build if the host doesn't have python3.

docker_rules has fixed the issue in https://github.com/bazelbuild/rules_docker/commit/2cad17b377ae6381a17dd986a1f5954a46e5d21b

**Comment by donmccasland** [comment]
We're now using release 0.12.0 of bazelbuild that contains that fix:
# Docker rules.
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "413bb1ec0895a8d3249a01edf24b82fd06af3c8633c9fb833a0cb1d4b234d46d",
    strip_prefix = "rules_docker-0.12.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.12.0.tar.gz"],
)
