### ISSUE TITLE
distroless crashes on `new HttpClient()`

### ISSUE THREAD

**Issue by haf** [GoogleContainerTools/distroless#203]
```
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
  at System.Net.Http.CurlHandler..ctor()
  at System.Net.Http.HttpClientHandler..ctor()
  at Logary.Targets.InfluxDb.Impl.State.create(InfluxDbConf conf, RuntimeInfo runtime)
```

https://github.com/logary/logary/blob/master/src/targets/Logary.Targets.InfluxDb/Targets_InfluxDb.fs#L380

Ref:

 - https://stackoverflow.com/questions/47713211/the-type-initializer-for-system-net-http-curlhandler-threw-an-exception - possible reason?
 - Tracked by https://github.com/logary/logary/issues/337

How to debug this? `printenv` is gone and so are all other tools

**Comment by haf** [comment]
I tried moving back to MSFT's official containers and that didn't have any issues with `new HttpClient()`

**Comment by salrashid123** [comment]
@haf  - Would you happen to stil have a minimal repro of this issue in addition to some specs on where you were running it (i.,e docker version, host OS, the ```.csproj``` file you used?  I tried a couple of things back a month ago but can't repro.

**Comment by lathama** [comment]
I read it as the user switch platforms at https://github.com/logary/logary/issues/337#issuecomment-397051225 so maybe close this issue.

**Comment by salrashid123** [comment]
i wanted to dig in a bit more as i don't think you'd have to swap out base run images.  I think we've covered much of whats needed for ```dotnet``` with this long list of [libs](https://github.com/GoogleContainerTools/distroless/blob/master/WORKSPACE#L92).

I tried to repro this but no go;   i wonder if something speific compile flags was set during build that coudl've contributed to this.   If  there's no repro available, i'm ok to close this out as that.

**Comment by lathama** [comment]
Looks like they need libcurl aka /usr/lib/x86_64-linux-gnu/libcurl* which is not there in base.

```
$ docker run -it --entrypoint=sh gcr.io/distroless/base:debug
/ # ls -lha /usr/lib/x86_64-linux-gnu/
total 3088
drwxr-xr-x    5 root     root        4.0K Jan  1  1970 .
drwxr-xr-x    4 root     root        4.0K Jan  1  1970 ..
drwxr-xr-x    2 root     root        4.0K Jan  1  1970 audit
drwxr-xr-x    2 root     root        4.0K Jan  1  1970 engines-1.1
drwxr-xr-x    2 root     root       12.0K Jan  1  1970 gconv
-rw-r--r--    1 root     root        2.6M Jan  1  1970 libcrypto.so.1.1
-rw-r--r--    1 root     root      432.5K Jan  1  1970 libssl.so.1.1
/ # 
```

So something like this hand typed method will get them there with docker multistage

```
FROM debian:stable AS build-env
RUN apt -qq install libcurl3

FROM gcr.io/distroless/base
COPY --from=build-env /usr/lib/x86_64-linux-gnu/libcurl* /usr/lib/x86_64-linux-gnu/
```

**Comment by salrashid123** [comment]
sorry, by base i meant the base for their docker file in multi-stage, not ```distroless:base```

the ```dotnet``` image does include ```libcurl``` in it...i wanted to see what specific directives/build commmands  OP used 

```
$ docker run -it --entrypoint=sh gcr.io/distroless/dotnet:debug

/ # ls -lha /usr/lib/x86_64-linux-gnu/ | grep curl
lrwxrwxrwx    1 root     root          12 Jan  1  1970 libcurl.so.3 -> libcurl.so.4
lrwxrwxrwx    1 root     root          16 Jan  1  1970 libcurl.so.4 -> libcurl.so.4.4.0
-rw-r--r--    1 root     root      510.4K Jan  1  1970 libcurl.so.4.4.0
/ #
```

**Comment by lathama** [comment]
ack, got it, I re-re-read the title and issue statement and can't figure that out.

**Comment by haf** [comment]
Yes, you can run build and run Rutta in Logary with the Mixpanel target (or any other target really), with this image as the base image.

Due to the high latency on the reply here, I'm unable to create a further minimal repro than "make a HTTP request". If that doesn't crash for you, then all is fine. I'm unsubscribing from this issue now.

**Comment by salrashid123** [comment]
@r2d4  it'd be ok to mark this closed-norepro; if it comes up again, we'll reopen or ref this
