### ISSUE TITLE
Go Timezone file?

### ISSUE THREAD

**Issue by drcrallen** [GoogleContainerTools/distroless#205]
As per https://golang.org/src/time/zoneinfo.go , go needs to have `ZONEINFO` available if the code handles timezone stuff at all. But I don't see any documentation in the builder base about if it is included, or how to include it.

This ask is that a special GO build on top of builder base be created that includes any go-specific items like `ZONEINFO` environment variables and the `zoneinfo.zip` file.

**Comment by dlorenc** [comment]
You'll probably need to install the debian tzinfo package using the package manager rules if you'd like this to work. We could consider adding it to our base image if it's not already there.

**Comment by lathama** [comment]
@drcrallen here is an example of adding the zoneinfo in a multistage Docker Dockerfile

`FROM debian:stable AS build-env
ENV LANG C.UTF-8
RUN apt-get -qq update
RUN apt-get -qq install tzdata

FROM gcr.io/distroless/base
EXPOSE 8080/TCP
COPY app /app/
COPY --from=build-env /usr/share/zoneinfo /usr/share/zoneinfo
CMD ["/app/app"]
HEALTHCHECK CMD ["/app/app", "--health"]
`

If this resolves your query please ack and close issue.

**Comment by lathama** [comment]
I would close this because of the known GOLang issue. From the outside I can imagine that a new user would be confused about what image to use for GOLang so a targeted image might not be a bad idea down the road.

**Comment by dlorenc** [comment]
Correct, tzdata should be present. Looks like this is being fixed upstream in go.
