### ISSUE TITLE
Organize Examples

### ISSUE THREAD

**Issue by lathama** [GoogleContainerTools/distroless#216]
Like #210 #213 and #215 there are various links that are off by one directory mainly from a move to the experimental directory. I would like to organize the examples by updating the primary README.md and the per language README.md files with correct links. I am using the questions and comments from a recent presentation I gave on Distroless as a guide to helping new users.

Goals:
* Correct existing documentation links - 1 x PR
* Convert links to full https:// links that bring the user to a source of truth 1 x PR
* Update examples that are lacking in detail - ? x PR

**Comment by dlorenc** [comment]
Is this done yet?

**Comment by lathama** [comment]
Just getting down cycle this week to work on this. Existing links soon.

**Comment by lathama** [comment]
In PR #220 the bulk of the relative links are resolved. I will start on the full links for those who have cloned or downloaded the repo to get back to the system of record as here. Can update base url with string replace if the source of truth ever changes.

**Comment by lathama** [comment]
I have an email from Github that some triggers and emails or notifications from my PR were not ran in relation to #220 please advise if something is missing. Everything looks fine to me.

**Comment by dlorenc** [comment]
I think this is fixed now, thanks!
