### ISSUE TITLE
docker multiarch image - add ppc64le/s390x architectures to docker image

### ISSUE THREAD

**Issue by grooverdan** [GoogleContainerTools/distroless#222]
I was looking to use the distroless as a base for skydive (https://hub.docker.com/r/skydive/skydive/) on all architectures but it was only accessible on x86_64.

It seems bazel has a cross-compilation capability to make this happen.

Thanks the great contribution to container security.

**Comment by dlorenc** [comment]
We have no way to test images on these architectures, so I'm a bit hesitant to ship binaries for them. Would you be interested in forking/hosting your own binaries in a different project?

**Comment by grooverdan** [comment]
There is a travis `os: linux-ppc64le` for running builds/tests on real hardware. I've got an example multiarch builds/deployment with https://github.com/grooverdan/hello-world/ / https://travis-ci.org/grooverdan/hello-world.

If the package `qemu-user-static` (tested Fedora and Ubuntu) is installed on the running OS, and `/usr/bin/qemu-${TARGET_GOARCH}-static` is copied inside the container, then you can have a fully emulated hardware test container. I certainly understand if this doesn't meet the reassurance criteria.

I'm not yet ready to run my own project (first exposure to Bazel) yet but I'll probably get time eventually to hack on the dependencies (https://github.com/bazelbuild/rules_docker/issues/300? / https://github.com/bazelbuild/bazel/issues/5657? others?). I certainly can help out with testing (running/writing).

**Comment by donmccasland** [comment]
I'm not sure we can ever support this, but if someone wants to take a crack at it, I'm ready to review PRs and build results.

**Comment by mattmoor** [comment]
It should be relatively straightforward to add additional architectures following what I'm doing for arm64 here (and it's baseline changes): https://github.com/GoogleContainerTools/distroless/pull/586
