### ISSUE TITLE
docker run: /busybox/sh: can't open <programm>

### ISSUE THREAD

**Issue by xinau** [GoogleContainerTools/distroless#224]
Im not sure if this is a bug or a functiolity which I don't quite get.
If I execute 
```console
$ docker run --entrypoint=/busybox/sh --rm -it gcr.io/distroless/base:debug 
/ # pwd
/
```
but 
```console
$ docker run --entrypoint=/busybox/sh --rm -it gcr.io/distroless/base:debug pwd
/busybox/sh: can't open 'pwd'
```
what part am I missing, why is this not working ?

**Comment by lathama** [comment]
From the README  the example is just sh
`docker run --entrypoint=sh -ti gcr.io/distroless/base:debug`

**Comment by xinau** [comment]
By specifying `sh` as a entrypoint this also isn't working.
```console
$ docker run --rm -it --entrypoint=sh gcr.io/distroless/base:debug pwd
sh: can't open 'pwd'
```

After some more investigation it seems like this might be a general problem with `busybox` as the official docker image has a similar problem.
```console
$ docker run --rm -it --entrypoint=sh busybox pwd
sh: can't open 'pwd': No such file or director
$ docker run --rm -it  busybox pwd
/
```
Maybe I am missing something, I just would like to understand this in my opinion strange behaviour.

**Comment by xinau** [comment]
Seems to be my own stupidity yesterday. For got the `-c`
Now it works. Sry for bothering.
```console
$ docker run --entrypoint=/busybox/sh --rm -it gcr.io/distroless/base:debug -c pwd
/
```
