### ISSUE TITLE
uclibc BusyBox in Distroless debug images fails with "ls: Value too large for defined data type"

### ISSUE THREAD

**Issue by xinau** [GoogleContainerTools/distroless#225]
*UPDATE by @chanseokoh: this issue is specifically about the pre-built, buggy BusyBox binary compiled using uClibc embedded in the Distroless `:debug` Docker images (e.g., [`gcr.io/distroless/java:debug`](https://gcr.io/distroless/java:debug)). The root cause is [Bug 11651](https://bugs.busybox.net/show_bug.cgi?id=11651) in BusyBox.*

---

It seems like LargeFileSupport is disabled in the debug images.
```console
$ docker run --entrypoint=/busybox/sh --rm -it gcr.io/distroless/base:debug 
/ # ls /
ls: can't open '/': Value too large for defined data type
```
According to the [coreutils docs](https://www.gnu.org/software/coreutils/faq/#Value-too-large-for-defined-data-type) this error is caused by not enabling LargeFileSupport when compiling.

The default docker image doesn't seem to have this problem
```console
$ docker run --entrypoint=/bin/sh --rm -it busybox
/ # ls
bin   dev   etc   home  proc  root  sys   tmp   usr   var
```

**Comment by dlorenc** [comment]
cc @tejal29

**Comment by tejal29** [comment]
hmm not able to reproduce this
```
docker run --entrypoint=/busybox/sh --rm -it gcr.io/distroless/base:debug 
Unable to find image 'gcr.io/distroless/base:debug' locally
debug: Pulling from distroless/base
8f125ded1b48: Pull complete 
8ca8724e5ffb: Pull complete 
Digest: sha256:333a18407c0e2d46b264a240175284b3bd2482892f4273bacb63a5d37a7adea2
Status: Downloaded newer image for gcr.io/distroless/base:debug
/ # ls
busybox  etc      lib      proc     tmp      var
dev      home     lib64    sys      usr
```

**Comment by dlorenc** [comment]
Same here. @xinau do you have any other info on how you reproduced this?

**Comment by xinau** [comment]
Since I've done several package updates (kernel, util-linux, ...)  in the mean time, they seem to have magically fixed the problem. I can't reproduce it anymore :( . 

Sry for bothering.

**Comment by dgageot** [comment]
I have the same issue on Docker for Mac `Version 18.06.0-ce-mac69 (26398)`

```
docker run --entrypoint=sh --rm gcr.io/distroless/base:debug -c ls
ls: can't open '.': Value too large for defined data type
```

**Comment by dgageot** [comment]
Funny, on D4M, it sometimes works just after I restart Docker or remove all the images. And then it breaks again

**Comment by dgageot** [comment]
See https://github.com/docker/for-mac/issues/3203

**Comment by reegnz** [comment]
I ran into the same issue on Docker for Windows:
```
reegnz@DOOD:~/distroless
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false
reegnz@DOOD:~/distroless
$ docker image ls gcr.io/distroless/java:debug
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
gcr.io/distroless/java   debug               a2b123fd9877        48 years ago        119MB
reegnz@DOOD:~/distroless
$ docker run -it --rm --entrypoint=sh gcr.io/distroless/java:debug -c ls
ls: can't open '.': Value too large for defined data type
```

**Comment by emaildanwilson** [comment]
I'm seeing this running against a k8s cluster. It is intermittent, for some pods works fine, other give this error. Perhaps it could be related to how large the filesystem is which the container is on?

**Comment by nfk** [comment]
I confirm this issue with docker 18.06.1-ce and gcr.io/distroless/java:debug (0507ea3dccb1). The restart of the docker daemon solves the issue.

**Comment by gf1730** [comment]
In my experience, the error "Value is too large for defined data type" is raised when a 32-bit application/library tries to access a file that has a 64-bit inode and overflows the 32-bit integer used to store the inode number.

**Comment by daisy-ycguo** [comment]
I confirm this issue with docker 18.06.1-ce on Mac.
```
$ docker run --entrypoint=/busybox/sh --rm -it gcr.io/distroless/base:debug
/ # ls
ls: can't open '.': Value too large for defined data type
```
```
$docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by donbowman** [comment]
The issue is the 64-bit inode.
Busybox would need to be compiled with e.g. _FILE_OFFSET_BITS=64, but then it would need to be 64-bit as well (likely) since off_t etc would change, and wouldn't fit in an int anymore.

This intermittently breaks on Microsoft Azure AKS Kubernetes with the distroless/java image w/ debug.

**Comment by chanseokoh** [comment]
I've filed a bug against busybox: https://bugs.busybox.net/show_bug.cgi?id=11651

@donbowman Distroless is pulling in the [1.27.1 version](https://busybox.net/downloads/binaries/1.27.1-i686/busybox), and I wonder if recent binaries have fixed this issue. I have trouble reproducing this in-house, so is it possible for you to test the most recent 1.30.0 binary from https://busybox.net/downloads/binaries/?

**Comment by donbowman** [comment]
I've confirmed 1.30.0 from busybox.net has the same issue.
I believe the issue is uclibc. i've confirmed that 1.30.0 glibc works.

**Comment by chanseokoh** [comment]
The busybox dev is asking for more info for debugging: https://bugs.busybox.net/show_bug.cgi?id=11651#c5. If anyone can still reproduce this issue, please update the bug tracker. @donbowman

**Comment by donbowman** [comment]
done, i need to find a static strace and get a privileged container up to do this tho.

**Comment by donbowman** [comment]
```
/proc # strace ls -l
execve("/busybox/ls", ["ls", "-l"], 0x7ffcdc43ede8 /* 16 vars */) = 0
strace: [ Process PID=33 runs in 32 bit mode. ]
strace: WARNING: Proper structure decoding for this personality is not supported, please consider building strace with mpers support enabled.
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
getuid32()                              = 0
time([1551486393 /* 2019-03-02T00:26:33+0000 */]) = 1551486393 (2019-03-02T00:26:33+0000)
ioctl(0, TIOCGWINSZ, {ws_row=38, ws_col=120, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
brk(NULL)                               = 0x9768000
brk(0x9769000)                          = 0x9769000
lstat64(".", 0xffa6e374)                = 0
open(".", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
fstat(3, 0xffa6e378)                    = -1 EOVERFLOW (Value too large for defined data type)
close(3)                                = 0
write(2, "ls: can't open '.': Value too la"..., 58ls: can't open '.': Value too large for defined data type
) = 58
write(1, "total 0\n", 8total 0
)                = 8
exit(1)                                 = ?
+++ exited with 1 +++
```

**Comment by donbowman** [comment]
```
# ./strace_static_x86_64 -v -v ls -l /proc
num_quals=312
--- stopped by SIGSTOP ---
--- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=73, si_uid=0} ---
execve("/busybox/ls", ["ls", "-l", "/proc"], ["KUBERNETES_SERVICE_PORT=443", "KUBERNETES_PORT=tcp://noc-noc-18"..., "HOSTNAME=test", "SHLVL=1", "OLDPWD=/usr", "HOME=/home", "SSL_CERT_FILE=/etc/ssl/certs/ca-"..., "TERM=xterm", "KUBERNETES_PORT_443_TCP_ADDR=noc"..., "PATH=/usr/local/sbin:/usr/local/"..., "KUBERNETES_PORT_443_TCP_PORT=443", "KUBERNETES_PORT_443_TCP_PROTO=tc"..., "KUBERNETES_SERVICE_PORT_HTTPS=44"..., "KUBERNETES_PORT_443_TCP=tcp://no"..., "PWD=/tmp", "KUBERNETES_SERVICE_HOST=noc-noc-"...]) = 0
[ Process PID=76 runs in 32 bit mode. ]
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {c_iflags=0x500, c_oflags=0x5, c_cflags=0xbf, c_lflags=0x8a3b, c_line=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\x00\x12\x0f\x17\x16\x00\x00\x00"}) = 0
ioctl(1, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {c_iflags=0x500, c_oflags=0x5, c_cflags=0xbf, c_lflags=0x8a3b, c_line=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\x00\x12\x0f\x17\x16\x00\x00\x00"}) = 0
getuid32()                              = 0
time([1551486719])                      = 1551486719
ioctl(0, TIOCGWINSZ, {ws_row=38, ws_col=120, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {c_iflags=0x500, c_oflags=0x5, c_cflags=0xbf, c_lflags=0x8a3b, c_line=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\x00\x12\x0f\x17\x16\x00\x00\x00"}) = 0
brk(0)                                  = 0x9a97000
brk(0x9a98000)                          = 0x9a98000
lstat64("/proc", {st_dev=makedev(0, 259), st_ino=1, st_mode=S_IFDIR|0555, st_nlink=299, st_uid=0, st_gid=0, st_blksize=1024, st_blocks=0, st_size=0, st_atime=2019/03/02-00:23:48, st_mtime=2019/03/02-00:23:48, st_ctime=2019/03/02-00:23:48}) = 0
open("/proc", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, 0xffe905e8)                    = -1 EOVERFLOW (Value too large for defined data type)
close(3)                                = 0
write(2, "ls: can't open '/proc': Value to"..., 62ls: can't open '/proc': Value too large for defined data type
) = 62
write(1, "total 0\n", 8total 0
)                = 8
_exit(1)                                = ?
+++ exited with 1 +++
```

**Comment by chanseokoh** [comment]
@donbowman I saw your update on the busybox bug. Thanks for reporting. Let's see what the dev will say.

**Comment by chanseokoh** [comment]
I see the busybox bug got the lowest priority P5. If anyone is severely affected by this issue, I suggest to go to the busybox bug and increase awareness.

https://bugs.busybox.net/show_bug.cgi?id=11651

**Comment by donbowman** [comment]
the workaround is to use the gclibc version https://github.com/docker-library/busybox/tree/master/glibc

across the board i find a lot of things on kubernetes (e.g. helm charts) that use 'busybox' as an initcontainer that intermittently fail in azure because of this issue, its not just the debug distroless.

**Comment by chanseokoh** [comment]
@donbowman sounds like if this would be gone if we just pull in and install a busybox binary using gblic. Does busybox provide compiled binaries with gblic at https://busybox.net/downloads/binaries/? Doesn't seem like they do.

I kind of heard that Kubernetes *might* be using distroless for some part of its workings (although I'm not sure).

**Comment by sesto** [comment]
I am experiencing the same issue when running on GKE cluster
```
 Kernel Version:             4.14.94+
 OS Image:                   Container-Optimized OS from Google
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.3
 Kubelet Version:            v1.13.5-gke.10
 Kube-Proxy Version:         v1.13.5-gke.10
```
No issue running on Rancher 2.0 clusters
```
 Kernel Version:             4.4.0-119-generic
 OS Image:                   Ubuntu 16.04.6 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.5
 Kubelet Version:            v1.13.5
 Kube-Proxy Version:         v1.13.5
```

**Comment by drobinson123** [comment]
Could busybox be installed from the Debian package (busybox-static) instead of being fetched from busybox.net? ie:

```
diff --git WORKSPACE WORKSPACE
index 51aa06f..1c4100a 100644
--- WORKSPACE
+++ WORKSPACE
@@ -52,6 +52,7 @@ dpkg_list(
         # TODO: Remove when there is a security fix or dpkg_list finds the recent version
         "libc6=2.24-11+deb9u4",
         "base-files",
+        "busybox-static",
         "ca-certificates",
         "openssl",
         "libssl1.0.2",
diff --git base/BUILD base/BUILD
index b08b5cf..f02f93d 100644
--- base/BUILD
+++ base/BUILD
@@ -132,9 +132,15 @@ container_image(
     name = "debug",
     base = ":base",
     directory = "/",
-    entrypoint = ["/busybox/sh"],
-    env = {"PATH": "$$PATH:/busybox"},
-    tars = ["//experimental/busybox:busybox.tar"],
+    entrypoint = [
+        "/bin/busybox",
+        "sh",
+        "-i",
+    ],
+    env = {"PATH": "$$PATH:/bin/busybox"},
+    debs = [
+        packages["busybox-static"],
+    ],
 )
 
 container_test(
```

**Comment by chanseokoh** [comment]
@drobinson123 maybe yes, and that's a neat idea. But I heard the last time someone looked into the `busybox` Debian package, the version was way behind the current one fetched from busybox.net. What's the version of it?

**Comment by tnguyen1** [comment]
> A workaround is to do something like:
> 
> ```
> FROM amd64/busybox:1.30.0-glibc as busybox
> FROM gcr.io/distroless/java
> 
> COPY --from=busybox /bin/busybox /busybox/busybox
> RUN ["/busybox/busybox", "--install", "/bin"]
> ```
Thanks @donbowman for the workaround! BTW the following shorter syntax is also working which does not require an extra `FROM` instruction:
```
COPY --from=amd64/busybox:1.31.0 /bin/busybox /busybox/busybox
```
\--
HTH

**Comment by tristanz** [comment]
Should this issue still be open?  I still see this issue:

```
docker run --entrypoint=/busybox/sh --rm -it gcr.io/distroless/base:debug 
Unable to find image 'gcr.io/distroless/base:debug' locally
debug: Pulling from distroless/base
9ff2acc3204b: Already exists 
69e2f037cdb3: Already exists 
0ab175cd7cdc: Pull complete 
Digest: sha256:6f78124292427599fcef84139cdc9f4ab2d1851fe129b140c92b997f8fe4d289
Status: Downloaded newer image for gcr.io/distroless/base:debug
/ # ls
ls: can't open '.': Value too large for defined data type
```

**Comment by marcosimioni** [comment]
FYI same here, but only on my k8s cluster. Works fine on my local Docker. I see I'm running 4.x locally, while the cluster runs on a 5.x. Could that be somehow related?

```
user@ubuntu:~$ docker run --entrypoint=/busybox/sh --rm -it gcr.io/distroless/base:debug
/ # ls
bin      boot     busybox  dev      etc      home     lib      lib64    proc     root     run      sbin     sys      tmp      usr      var
/ # cat /proc/version
Linux version 4.15.0-70-generic (buildd@lgw01-amd64-057) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)) #79~16.04.1-Ubuntu SMP Tue Nov 12 14:01:10 UTC 2019
/ # uname -a
Linux 9c95011ee4f2 4.15.0-70-generic #79~16.04.1-Ubuntu SMP Tue Nov 12 14:01:10 UTC 2019 x86_64 GNU/Linux
/ # exit

user@ubuntu:~$ kubectl exec -it base-debug /busybox/sh
/ # ls
ls: can't open '.': Value too large for defined data type
/ # cat /proc/version
Linux version 5.0.0-29-generic (buildd@lgw01-amd64-039) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019
/ # uname -a
Linux base-debug 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 GNU/Linux
/ # 
```

**Comment by chanseokoh** [comment]
https://bugs.busybox.net/show_bug.cgi?id=11651

My interpretation of the link above is that this is fixed in recent BusyBox versions. (The actual bug was in uClibc that BusyBox uses. That is why using the glibc version works.) Although I have never tried, I expect that Debian 10-based Distroless images (`gcr.io/distroless/base-debian10:debug`) won't have this issue. Debian 9-based images probably don't get package updates, so I Debian 10 images are stuck with the buggy BusyBox binary.

But I see there is a workaround, if you still want to use the Debian 9-based images, which is to get the `glibc`-based BusyBox: https://github.com/GoogleContainerTools/distroless/issues/225#issuecomment-516738609 Maybe getting a recent BusyBox binary either from actual Debian 10 or from the official BusyBox site could also work.

**Comment by chanseokoh** [comment]
Huh, BusyBox released [1.31.0](https://busybox.net/downloads/binaries/) on Jun 10, which is the day after fixing the [uClibc issue](https://bugs.busybox.net/show_bug.cgi?id=11651#c13) on Jun 9, so perhaps that's fixed in 1.31.0. I can put up a PR to upgrade BusyBox.

**Comment by Sineaggi** [comment]
Is this confirmed fixed?
```
/ # busybox
BusyBox v1.31.0 (2019-06-10 15:13:14 CEST) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.
...
/ # ls
ls: can't open '.': Value too large for defined data type
```
From latest distroless java debug `gcr.io/distroless/java:11-debug`

**Comment by chanseokoh** [comment]
https://github.com/GoogleContainerTools/distroless/issues/225#issuecomment-557581462 is why the bug is fixed in 1.31.0, but maybe it's not fixed. I'll reopen https://bugs.busybox.net/show_bug.cgi?id=11651 and ask them.

**Comment by ribx** [comment]
I can reproduce the problem, too.
```busybox: 1.31.0
kernel: 4.19.59-gentoo
docker: 19.03.5```
After a restart of the docker daemon, it works as expected.

**Comment by kunal-bhatia** [comment]
Same issue :-

```
/ $ busybox
BusyBox v1.31.0 (2019-06-10 15:13:14 CEST) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

/ $ ls
ls: can't open '.': Value too large for defined data type
```

**Comment by chanseokoh** [comment]
@ribx @kunal-bhatia I urge you to go to https://bugs.busybox.net/show_bug.cgi?id=11651 and update there to make the BusyBox devs look into the case and fix it.

**Comment by den-is** [comment]
Issue still exists
That workaround has helped https://github.com/GoogleContainerTools/distroless/issues/225#issuecomment-516738609

**Comment by Alcatros** [comment]
> Issue still exists
> That workaround has helped [#225 (comment)](https://github.com/GoogleContainerTools/distroless/issues/225#issuecomment-516738609)

We have the same Issue, when we run this we get the error, it seems to be wrong but "always" wrong doesnt crash, but who knows what the real impact on this failure is.

The Workaround you posted above doesnt work for me, it says "textfile busy" when i try to execute the COPY Command to make a sublayer, did you test this? Thanks for a reply :-)!

$ export PERSISTENT_HASH="$(./tools/get_multifile_hash.sh $PERSISTENT_HASH_FILES)"
find: docker: Value too large for defined data type

**Comment by donbowman** [comment]
the workaround is fine.
are you sure you are using the workaround in the Dockerfile on build stage? textfile busy suggests its being run at run time to me.

**Comment by Alcatros** [comment]
> the workaround is fine.
> are you sure you are using the workaround in the Dockerfile on build stage? textfile busy suggests its being run at run time to me.

Well we are using kaniko to "build" our container but that shouldnt be an issue should it?

**Comment by chanseokoh** [comment]
@Alcatros it's confusing whether the error is
1. from the Kaniko binary `/kaniko/executor` (note Kaniko doesn't run Docker engine)
2. from a Docker engine running `Dockerfile`
3. when running an image built out of Kaniko/Docker

But I'll assume 1). This just looks like a Kaniko issue where it can't properly run `COPY --from=amd64/busybox:1.31.0 /bin/busybox /busybox/busybox`. And I think the fact that you can't run this COPY command is anyway unrelated to this issue. Maybe ask on the Kaniko repo?

**Comment by chanseokoh** [comment]
And I don't get why you use `gcr.io/kaniko-project/executor:latest` as a base image. Are you building another Kaniko image?

**Comment by alex1989hu** [comment]
We are also affected - upvote +1

**Comment by chanseokoh** [comment]
This is the [issue in BusyBox](https://github.com/GoogleContainerTools/distroless/issues/225#issuecomment-592034226). If you are affected, please go to the BusyBox bug report and upvote there.

**Comment by alex1989hu** [comment]
@chanseokoh 
This is not clear for me why it is working if we replace busybox in kaniko image with busybox. Different variant?

**Comment by chanseokoh** [comment]
Likely. The way I see it, this is a bug in BusyBox compiled with uclibc. Sounds like using a glibc BusyBox. And is Kaniko using a debug Distroless image? Why are you using a debug image?

**Comment by chanseokoh** [comment]
I think some people are reporting their issue on a wrong repository only after googling with the apparent error message "Value too large for defined data type", not realizing that this is the Distroless repo. I've updated the issue title and hidden some comments seemingly unrelated to Distroless.

**Comment by donbowman** [comment]
is there some compelling reason we can't use the glibc busybox in here? it works, its compatible, those that use the :debug for whatever reason are happy?
its +2 years open, the uclibc approach was designed for small embedded systems, it may never see the reason to fix, there could be other kernel changes coming it doesn't stay up to date w/.

**Comment by chanseokoh** [comment]
> is there some compelling reason we can't use the glibc busybox in here?

@donbowman I don't think there is. I think whatever approach that resolves this issue should be fine. Someone put up a [PR](https://github.com/GoogleContainerTools/distroless/pull/380) (which has merge conflicts) to get BusyBox from the Debian packages. However, it downgrades the version and misses some commands; maybe it is no longer a case with Debian 10, I don't know. Even so, it's for debug images, so it may not matter much. But maybe, just downloading the glibc version would be a simpler and easier way. Another one else suggested switching to ToyBox.

I think either solution can work. We appreciate community contributions. (I'm not going to work on this, BTW.)

**Comment by alex1989hu** [comment]
@chanseokoh: many people around who want to use `kaniko:debug`
Guys tracked down that `distroless` provided `busybox` causes the issue - which is part of `kaniko:debug` image:
https://github.com/GoogleContainerTools/kaniko/blob/0522fe2485c25f55d9d96a028058da0b180e0bec/deploy/Dockerfile_debug#L36-L41

Q: Why anybody wants to use debug image? 
A: I can only share my needs, but saw many others with the common need -> to let us able to build images with `kaniko:debug` securely (non-privileged). A great example is written here: https://gitlab.com/guided-explorations/containers/kaniko-docker-build.

Q: How I met this issue? 
A: Wanted to try out image build w/ `kaniko:debug` following the referenced GitLab guide. My kubernetes cluster runs on Talos.

Q: How I managed to solve?
A: Had to apply the already provided workaround https://github.com/GoogleContainerTools/distroless/issues/225#issuecomment-516738609

I would be happy to help in changing the `busybox`. Do you know any other maintainer who can assist us?

**Comment by chanseokoh** [comment]
@alex1989hu thanks for the detailed explanation. It's really good to know that Kaniko is based on Distroless; didn't know that.

> I  would be happy to help in changing the `busybox`. Do you know any other maintainer who can assist us?

Thanks a lot. I am the most active "moderator" (not "maintainer"); I can gladly assist you. What's your plan? I *think* downloading the precompiled glibc BusyBox is the easiest and straightforward fix.

**Comment by chanseokoh** [comment]
> which is part of `kaniko:debug` image:
> https://github.com/GoogleContainerTools/kaniko/blob/0522fe2485c25f55d9d96a028058da0b180e0bec/deploy/Dockerfile_debug#L36-L41

Unrelated, the way Kaniko fetches BusyBox is inexplicably convoluted. Why getting it from a Distroless image, while it can simply download it directly (which is what Distroless does)? Doesn't make much sense to me.

**Comment by alex1989hu** [comment]
/cc @tejal29 @tstromberg @samos123  what do you think? I think most of us wants to replace busybox but @chanseokoh points to a good question. Is it mandatory to use `distroless` provided busybox?

One of the kaniko related issue: https://github.com/GoogleContainerTools/kaniko/issues/985#issuecomment-596136870

**Comment by donbowman** [comment]
> > is there some compelling reason we can't use the glibc busybox in here?
> 
> @donbowman I don't think there is. I think whatever approach that resolves this issue should be fine. Someone put up a [PR](https://github.com/GoogleContainerTools/distroless/pull/380) (which has merge conflicts) to get BusyBox from the Debian package. However, it downgrades the version and misses some commands; maybe it is no longer the case with Debian 10, I don't know. Even so, it's for debug images, so it may not matter much. But maybe, just downloading the glibc version would be a simpler and easier way. Another person suggested switching to ToyBox.
> 
> I think either solution can work. We appreciate community contributions. (I'm not going to work on fixing this myself, BTW.)

actually its not just debug, i believe the java distroless has busybox in it for non-debug.

**Comment by donbowman** [comment]
so If I update https://github.com/GoogleContainerTools/distroless/pull/380 to not conflict, and use current busybox from busybox.net (w/ glibc), all are good w/ that? I can take a look.

**Comment by chanseokoh** [comment]
> i believe the java distroless has busybox in it for non-debug.

No, all non-debug images do not have busybox. Particularly Java images have tests for this. 
https://github.com/GoogleContainerTools/distroless/blob/bd106244193c116853063dd5e7625d8fcdde5045/java/testdata/java11_debian10.yaml#L15-L17

> so If I update #380 to not conflict, and use current busybox from busybox.net (w/ glibc), all are good w/ that?

If you get the glibc version from busybox.net, I think we can forget about #380. (#380 is for getting busybox from Debian.) Thanks for your help.

**Comment by chanseokoh** [comment]
Instead of waiting for BusyBox to fix [Bug 11651](https://bugs.busybox.net/show_bug.cgi?id=11651), we switched from using uClibc BusyBox to musl-libc BusyBox (#513). Previously this thread talked about using glibc BusyBox, but I think it doesn't matter to use musl as long as we can resolve this issue.
