### ISSUE TITLE
readme.md docs are ambiguous on weather distorts java is production ready?

### ISSUE THREAD

**Issue by asaikali** [GoogleContainerTools/distroless#233]
Currently the readme.md file relevant section produced below states in one section that distroless/java is not production ready but the jib project is suggesting that it be used without reference to distroless/java being not production ready. 

Maybe a good idea to clarify what is considered production ready and what is not. I see both distroless/java and distroless/cc in the base images list and in the not recommended for production are there any language specific distroless images that are considered production ready?

> * Pick the right base image for your application stack.
>   We publish the following distroless base images on `gcr.io`:
>     * [gcr.io/distroless/base](base/README.md)
>     * [gcr.io/distroless/java](java/README.md)
>     * [gcr.io/distroless/cc](cc/README.md)
> 
> * The following images are also published on `gcr.io`, but are considered experimental and not recommended for production usage:
>     * [gcr.io/distroless/python2.7](experimental/python2.7/README.md)
>     * [gcr.io/distroless/python3](experimental/python3/README.md)
>     * [gcr.io/distroless/nodejs](experimental/nodejs/README.md)
>     * [gcr.io/distroless/java](java/README.md)
>     * [gcr.io/distroless/java/jetty](java/jetty/README.md)
>     * [gcr.io/distroless/cc](cc/README.md)
>     * [gcr.io/distroless/dotnet](experimental/dotnet/README.md)

**Comment by dlorenc** [comment]
#232 should address this. Java should be considered production ready.
