### ISSUE TITLE
Java 11 and future Java version support

### ISSUE THREAD

**Issue by anuraaga** [GoogleContainerTools/distroless#236]
I noticed a closed bug about Java 9 here and one about Java 10 in [jib](https://github.com/GoogleContainerTools/jib/issues/550) but didn't find an open issue here so figured it'd be good to track it.

From the jib issue, it sounds like Java 10 will be skipped in favor of Java 11 LTS. This is good news, but I was wondering if there's also a version support plan going forward? LTS-only, LTS + latest non-LTS, or something similar? If distroless always supports the latest Java, at least for 6 months, it means people can use it while staying at the cutting edge of Java :)

**Comment by barmic** [comment]
What is the plan? Do you think use https://adoptopenjdk.net/ and there API?

**Comment by jabrena** [comment]
One idea to consider: 

`jib` could allow using complete OpenJDK builds or Java Runtime Images to save memory.

Example:
https://github.com/ev3dev-lang-java/openjdk-ev3/blob/master/scripts/zip.sh

Results:

https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk11_build_ev3_linux/

Complete JDK: 265mb
JRI: 22mb 

Juan Antonio

**Comment by arashbi** [comment]
is there any jdk 11 image at the moment?

**Comment by chanseokoh** [comment]
Java 11 images (`gcr.io/distroless/java:11` and `gcr.io/distroless/java:11-debug`) are now available, in parity with the Java 8 images (`gcr.io/distroless/java:8` and `gcr.io/distroless/java:8-debug`). The `latest` and `debug` continue to point to the Java 8 images (i.e., `8` and `8-debug`, respectively).

Like the Java 8 images, the Java 11 images unpack the headless OpenJDK JRE Debian package (`openjdk-11-jre-headless`). However, I noticed the size of the 11 images are a bit larger than the 8 images.

```
gcr.io/distroless/java   8                   9c0bc85b4448        49 years ago        119MB
gcr.io/distroless/java   11                  a4338971ab0a        49 years ago        189MB
```
