### ISSUE TITLE
OpenJDK distribution source and security patches

### ISSUE THREAD

**Issue by dokky** [GoogleContainerTools/distroless#238]
Hello,

General question what is the source of OpenJDK distribution? 
What is security patches release timeline?

**Comment by lathama** [comment]
Package should be https://packages.debian.org/stretch/openjdk-8-jdk and changelog at http://metadata.ftp-master.debian.org/changelogs//main/o/openjdk-8/openjdk-8_8u181-b13-1~deb9u1_changelog but distroless can allow you to build images in any way you want. You can build distroless images for more recent versions of openjdk if you want.

**Comment by dokky** [comment]
Thank you!
Can I assume that distroless will pick up a new patch in a short period, a day for example?

**Comment by lathama** [comment]
I can's speak on behalf of Google but as it is used internally at Google we can assume that the images will be updated quickly.

**Comment by dlorenc** [comment]
I don't know that we have any timelines we can promise, but the basic process is that we get notified when a patch becomes available to a package present in these images via the container analysis API:
https://cloud.google.com/container-analysis/api/reference/rest/

We then update the packages and send a PR soon.

**Comment by evanj** [comment]
The Debian snapshot in `WORKSPACE` is currently 2018-07-19 on Master, so it is almost certainly missing the latest OpenJDK security fix. PR #239 should include it though, but I didn't double check the version of the package that ends up actually installing.

**Comment by donmccasland** [comment]
debian snapshot and openjdk distribution has been updated.

**Comment by chanseokoh** [comment]
FTR: we just set up GitHub Actions to automate pulling in new deb packages updated in the Debian snapshot upstream: #537.
