### ISSUE TITLE
distroless/java should set default output encoding to UTF-8

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/distroless#253]
From https://github.com/GoogleContainerTools/jib/issues/1227 it seems that distroless/java's default file encoding is picked up as US-ASCII.  The Docker `openjdk` images [had the same problem](
https://github.com/docker-library/openjdk/issues/32) which was solved by setting `LANG=C.UTF-8`.  For some reason that doesn't make a difference with `distroless/java`:
```
$ docker run -e LANG=C.UTF-8 -it --rm issue-jib-utf8:0.0.1
env: {PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt, HOSTNAME=825d06a20ca4, TERM=xterm, LANG=C.UTF-8, HOME=/home}
sun.jnu.encoding: ANSI_X3.4-1968
file.encoding: ANSI_X3.4-1968
Locale.getDefault(): en_US
Charset.defaultCharset: US-ASCII
Hello ???
```

**Comment by briandealwis** [comment]
A workaround is to explicitly pass `-Dfile.encoding=UTF-8`.

**Comment by briandealwis** [comment]
It seems the missing piece is `/usr/lib/locale`.  If I include a copy of this directory from `openjdk:8-slim`, which provides `C.UTF-8`, and set `LANG=C.UTF-8` then all is well. 

`/usr/lib/locale` is provided by the `libc-bin` package.

**Comment by chanseokoh** [comment]
There's still something itching me. My workstation does have `/usr/lib/local/C.UTF-8`.

```
$ ls /usr/lib/locale/C.UTF-8
LC_ADDRESS  LC_COLLATE  LC_CTYPE  LC_IDENTIFICATION  LC_MEASUREMENT  LC_MESSAGES/  LC_MONETARY  LC_NAME  LC_NUMERIC  LC_PAPER  LC_TELEPHONE  LC_TIME
```
`libc-bin` is installed too.
```
$ dpkg -l | grep libc-bin
ii  libc-bin                                          2.24-12                                  amd64        GNU C Library: Binaries
```
However, https://github.com/GoogleContainerTools/jib/issues/1227#issuecomment-437078159 shows that it doesn't work even if I have `/usr/lib/locale/C.UTF-8`. (On the other hand, JDK 11 works fine.)

**Comment by ledroide** [comment]
I have tried this workaround in a Dockerfile, but it seems it is not enough to solve the issue : 
```dockerfile
FROM gcr.io/distroless/java:11-debug
COPY --from=debian:9.11 /usr/lib/locale /usr/lib/locale
ENV LANG=en_US.UTF-8
```
But in java, sun.jnu.encoding is still "ANSI_X3.4-1968"
Maybe some other files are still missing ?

**Comment by chanseokoh** [comment]
The workaround is to pass `-Dfile.encoding=UTF-8` to the JVM when running your Java application. You could update your `ENTRYPOINT` (or `CMD` as needed), or use the `JAVA_TOOL_OPTIONS` env variable.

**Comment by ledroide** [comment]
@chanseokoh : Still trying with this "enforced" dockerfile : 
```dockerfile
ARG TAG_SUFFIX=""
FROM gcr.io/distroless/java:11${TAG_SUFFIX}
COPY --from=debian:9.11 /usr/lib/locale /usr/lib/locale
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_NUMERIC=en_US.UTF-8
ENV LC_TIME=en_US.UTF-8
ENV LC_MONETARY=en_US.UTF-8
ENV LC_PAPER=en_US.UTF-8
ENV LC_NAME=en_US.UTF-8
ENV LC_ADDRESS=en_US.UTF-8
ENV LC_TELEPHONE=en_US.UTF-8
ENV LC_MEASUREMENT=en_US.UTF-8
ENV LC_IDENTIFICATION=en_US.UTF-8
ENV JAVA_TOOL_OPTIONS='-Dfile.encoding="UTF-8" -Dsun.jnu.encoding="UTF-8"'
ENV _JAVA_OPTIONS='-Xmx256m -Dfile.encoding="UTF-8"'
COPY locale /etc/default/locale
COPY printencoding-0.0.1-SNAPSHOT.jar /app/printencoding.jar
WORKDIR /app
ENTRYPOINT ["/usr/bin/java", "-Dfile.encoding=UTF-8", "-Dsun.jnu.encoding=UTF-8", "-jar"]
```
with this _/etc/default/locale_ file - that is missing in original distroless/java:11 image : 
```bash
LANG="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
```
We also have created a tiny binary _printencoding.jar_ that displays our java variables.

Still **"ANSI_X3.4-1968"** for _sun.jnu.encoding_ :
```bash
docker run -t --rm tmp/distroless-java:11-unicode printencoding.jar
```
```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Picked up _JAVA_OPTIONS: -Xmx256m
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding;    UTF-8
sun.jnu.encoding: ANSI_X3.4-1968
Default Encoding: UTF8
```
The value of _sun.jnu.encoding_ should be "UTF-8" in order to accept, for instance, files uploads with chinese or european file names.

What else can we try ?

**Comment by chanseokoh** [comment]
Oh, sorry. You are talking about `sun.jnu.encoding`. Not sure about this property, but the prefix makes me suspect this is an internal implementation detail. For example, I saw IBM VM has `ibm.system.encoding`, so depending on this SUN JRE-specific property doesn't sound good for portability either. Anyways, I'll do some quick research on this.

BTW, you don't need to mess up with the environment variables or the locale directory. For example,

```Dockerfile
FROM gcr.io/distroless/java:11-debug
SHELL ["/busybox/sh", "-c"]
RUN echo $'\
public class A {\n\
    public static void main(String... args) {\n\
        System.out.println("file.encoding=" + System.getProperty("file.encoding"));\n\
        System.out.println("sun.jnu.encoding=" + System.getProperty("sun.jnu.encoding"));\n\
        System.out.println("LANG=" + System.getenv("LANG"));\n\
        System.out.println("\u65E5");\n\
    }\n\
}' > /A.java
ENTRYPOINT ["java", "/A.java"]
```

```
$ docker build -t test .
...
Successfully built b9c2883f3ff9
Successfully tagged test:latest

chanseok$ docker run --rm test
file.encoding=ANSI_X3.4-1968
sun.jnu.encoding=ANSI_X3.4-1968
LANG=null

chanseok$ docker run --rm -e JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 test
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
file.encoding=UTF-8
sun.jnu.encoding=ANSI_X3.4-1968
LANG=null
日
```

**Comment by chanseokoh** [comment]
Indeed, `sun.jnu.encoding` is an [implementation detail](http://mail.openjdk.java.net/pipermail/jdk8-dev/2012-November/001610.html) and not a public interface that you shouldn't really care about.

This [bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8003228) give some more information too. I think the value should be dependent on platforms. For example, if on Mac, it should always be `UTF-8`, regardless of `file.encoding`.

@ledroide I'll do some more research later, but if you hit a real issue, then perhaps you should file a bug against Oracle JDK. Maybe like setting `-Dfile.encoding=UTF-8` should also change `snu.jnu.encoding` properly.

**Comment by chanseokoh** [comment]
@ledroide actually, copying `/usr/lib/locale` is another very good workaround, and perhaps Distroless should have this by default. I made it work. See the following `Dockerfile`. In this case, you don't need to give `-Dfile.encoding=UTF-8` either.

```Dockerfile
FROM gcr.io/distroless/java:11-debug
COPY --from=debian:9.11 /usr/lib/locale /usr/lib/locale
SHELL ["/busybox/sh", "-c"]
ENV LANG=C.UTF-8
RUN echo $'\
public class A {\n\
    public static void main(String... args) {\n\
        System.out.println("file.encoding=" + System.getProperty("file.encoding"));\n\
        System.out.println("sun.jnu.encoding=" + System.getProperty("sun.jnu.encoding"));\n\
        System.out.println("LANG=" + System.getenv("LANG"));\n\
        System.out.println("\u65E5");\n\
    }\n\
}' > /A.java
ENTRYPOINT ["java", "/A.java"]
```

Check this out:
```
$ docker build -t test .
...
Successfully built e1b202f876d1
Successfully tagged test:latest

$ docker run --rm test
file.encoding=UTF-8
sun.jnu.encoding=UTF-8
LANG=C.UTF-8
日
```

**Comment by ledroide** [comment]
@chanseokoh : Thanks a lot for your answer.
There was obviously something that disturbed java encoding in my over-configured dockerfile, but I could not figure out which one.

Here is my new dockerfile that now works fine : 
```dockerfile
ARG TAG_SUFFIX=""
FROM gcr.io/distroless/java:11${TAG_SUFFIX}
COPY --from=debian:9.11 /usr/lib/locale /usr/lib/locale
ENV LANG=C.UTF-8
COPY printencoding-0.0.1-SNAPSHOT.jar /app/printencoding.jar
WORKDIR /app
ENTRYPOINT ["/usr/bin/java", "-jar"]
```
And the output of our own test code : 
```bash
$ docker run -t --rm tmp/distroless-java:11-unicode printencoding.jar
Default Locale:   en
Default Charset:  UTF-8
file.encoding;    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8
```

**Comment by briandealwis** [comment]
I don't understand why the `C.UTF-8` is in `libc-bin` rather than `locales-all` or some smaller package, as `libc-bin` pulls in additional binaries that just aren't necessary.  I wonder if we can just pull out the files in `/usr/lib/locale`.

**Comment by chanseokoh** [comment]
> I wonder if we can just pull out the files in `/usr/lib/locale`.

It's easy to [exclude files when pulling in a package](https://github.com/GoogleContainerTools/distroless/issues/508#issuecomment-623485680). I forgot all the details of this issue, but reading it through again, it sounds like the solution is to put certain files under `/usr/lib/locale` and set `LANG=C.UTF-8`. Need to verify `libc-bin` provides the relevant files in all combinations: Java 8/11 and Debian 9/10.

**Comment by chanseokoh** [comment]
> It's easy to [exclude files when pulling in a package](https://github.com/GoogleContainerTools/distroless/issues/508#issuecomment-623485680).

I was wrong about this. The example in the link was when using the `pkg_tar` rule. The [`container_image`](https://github.com/bazelbuild/rules_docker#container_image-1) rule doesn't have a feature to exclude files added through the `deb` attribute.

Now I get why we left this issue open for a long time. `libc-bin` brings in a lot of [unwanted files](https://packages.debian.org/buster/amd64/libc-bin/filelist) (particularly the files under `/usr/bin/...` and `/usr/sbin/...`). It's not trivial to find a way to add only some files from a `.deb`.

**Comment by petermylemans** [comment]
See PR for a proposed fix by extracting only the /usr/lib/locale from the debs in a separate build rule. 

I'm not sure whether the go and python stacks also suffer from this issue. Should that be the case, the fix would better be done in the base image and not the java_base.

For now it is done for both java_base (for build-your-own jre using jlink) and its derivatives (java 8 and java 11).

**Comment by jtheuer** [comment]
Thanks for the fix! Forgive me the stupid question: How can I found our what jib releases contain the fix?

**Comment by chanseokoh** [comment]
@jtheuer this was an issue in the Distroless image and independent of Jib releases. Jib just uses `gcr.io/distroless/java` as a base image by default, and because Distroless fixed the issue, re-running Jib with the latest Distroless will do.
