### ISSUE TITLE
Add a Base for Static Go Binaries

### ISSUE THREAD

**Issue by dlorenc** [GoogleContainerTools/distroless#256]
gcr.io/distroless/base would contain:

tzdata
cacerts
passwd
nsswitch
/tmp
netbase (for GRPC)

It would specifically not contain:
glibc
openssl

**Comment by wmark** [comment]
That's already covered with `gcr.io/distroless/static`, albeit without *netbase* – which is not always needed.

What's not in said image but needed, and indeed referenced by the *Go* stdlib:
- `/etc/mime.types`
- `/etc/services`

**Comment by tallclair** [comment]
@wmark I believe gcr.io/distroless/static is intended to cover this use case, in which case I think we should add those files to the image.

**Comment by wmark** [comment]
More often than not—and it's indeed the default—binaries rely on *libc*, therefore I wouldn't equate "static" with "go binary". Anecdotally, most terminal apps I write in Go are not static for many reasons.

In any case, are you okay adding those two files to images `/static` (as suggested to OP) and `/base` and thereby addressing and closing this issue?

I am no fan of images shipping with *openssl* (for there are many alternatives), but I feel save for the 3.1 MiB we can agree on this.

**Comment by riking** [comment]
Fixed by #259

**Comment by chanseokoh** [comment]
Thanks for the reminder! Closing.
