### ISSUE TITLE
Adding NodeJS v10.x

### ISSUE THREAD

**Issue by MerlinDMC** [GoogleContainerTools/distroless#261]
I would like to add NodeJS 10.14.1 into the selection.

What would be the preference?
- Bump `//experimental/nodejs`
- Create additional `//experimental/nodejs10`

I personally like to have to ability to select v8 or v10 based on project history but I'm not sure how much I like having `//experimental/nodejs10` as an image 😄

**Comment by naddison36** [comment]
Personally, I think `//experimental/nodejs` should be bumped to version 10. If people want a node 8 version they can reference an old node 8 image. eg `FROM gcr.io/distroless/nodejs@sha256:5dcd0a88aa8b57a80e685c8439e8d2ace04f1c0d7e321a766a673269adb63d35`

The other thing to consider is node 8 is now in maintenance mode and will be end-of-life (EOL) at the end of 2019. Node 10 is now in active long term support (LTS) and is not EOL until April 2021
https://github.com/nodejs/Release

**Comment by lathama** [comment]
You can use Bazel to build your own images or a multi-build with Dockerfile to get these setups today if required.

**Comment by naddison36** [comment]
So I forked the repo and upgraded the WORKSPACE file to use nodejs version 10 https://github.com/naddison36/distroless/commit/e81fab46d96ba7dbe3aed78678c18262a6ebec32

How do I use bazel to build a nodejs image? I've never used bazel before and my guesses didn't work

Thanks

**Comment by Downchuck** [comment]
What is it that's keeping node in "experimental" status?

**Comment by jbergstroem** [comment]
Was trying out distroless and couldn't figure out why there was no $LATEST_LTS version available. At least this issue points to more people asking the same question.

**Comment by maxday** [comment]
Hello @MerlinDMC,
I am also interested in using node10, did you succeed in building the image ?

Hello @lathama
Do you know when gcr.io/distroless/nodejs won't be in experimental mode any more and considered safe for production usage ?

Thanks !
Max

**Comment by elliot** [comment]
Closed by #397
