### ISSUE TITLE
Support PHP distroless

### ISSUE THREAD

**Issue by PKuebler** [GoogleContainerTools/distroless#268]

**Comment by lathama** [comment]
Please detail what you are asking. Please detail what a PHP environment might look like for your query. Are you assuming the inclusion of a webserver like Apache HTTPD?

**Comment by sn00p** [comment]
I guess could be  great to have just php-fpm like php:7.2-fpm-alpine or similar

**Comment by lathama** [comment]
Try https://github.com/spiral/roadrunner if set on using Distroless

**Comment by sn00p** [comment]
@lathama It's too complicated in our case, we just need a backend part in most of the cases. But thanks for link, didn't know about this, could be useful.

**Comment by donmccasland** [comment]
sounds like we can close this.

**Comment by MatellioRahul** [comment]
can you please provide base php distroless image ?

**Comment by piotrkardasz** [comment]
You can take a look at #1010 and https://github.com/piotrkardasz/php-distroless and test following tags https://hub.docker.com/r/piotrkardasz/php-distroless/tags

**Comment by deulizealand** [comment]
> You can take a look at #1010 and https://github.com/piotrkardasz/php-distroless and test following tags https://hub.docker.com/r/piotrkardasz/php-distroless/tags

any example on how to run the application ?
