### ISSUE TITLE
Remove cloudbuild.yaml

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/distroless#286]
It looks like the file was introduced as a workaround because the legacy `docker_push` rule stopped working. (Correct me if I'm wrong.) With the new rules (PR: #280), it works again in my testing.

**Comment by chanseokoh** [comment]
But looks like there's an automatic publish hook using it (https://github.com/GoogleContainerTools/distroless/pull/283#issuecomment-457736388), so I guess `cloudbuild.yaml` should stay for a while.

**Comment by chanseokoh** [comment]
A deviation that `cloudbuild.yaml` producing additional tags: https://github.com/GoogleContainerTools/distroless/pull/297

**Comment by donmccasland** [comment]
We are using cloudbuild and triggers to automatically build and publish images.  We will not be changing that.
