### ISSUE TITLE
Make Java images container-friendly by default

### ISSUE THREAD

**Issue by saturnism** [GoogleContainerTools/distroless#289]
set default container env var `JAVA_TOOL_OPTIONS="-XX:+UseContainerSupport"`  similar to https://hub.docker.com/r/adoptopenjdk/openjdk11/

**Comment by briandealwis** [comment]
According to [JDK-8196595](https://bugs.openjdk.java.net/browse/JDK-8196595), `UseContainerSupport` was introduced in Java 10 (so not applicable to `:8`), and is enabled by default on Linux.

But we should enable necessary settings to make the `:8` image more container-friendly.

**Comment by chanseokoh** [comment]
> `UseContainerSupport` ... and is enabled by default on Linux.

So we don't need it? Then why do almost all JDK images set these env variables (https://github.com/GoogleContainerTools/distroless/issues/276#issuecomment-460375014)?

**Comment by chanseokoh** [comment]
Multiple sources say `UseContainerSupport` is true by default, and `-XX:-UseContainerSupport` is there to disable it for those who want. So I also think it's unnecessary to set the option.
