### ISSUE TITLE
Add a Groovy example

### ISSUE THREAD

**Issue by mattmoor** [GoogleContainerTools/distroless#29]
I believe the blocker I hit before should be resolved by: https://github.com/bazelbuild/rules_groovy/issues/8

**Comment by dlorenc** [comment]
I think this is fixed now, right?

**Comment by tejal29** [comment]
Are you still working on this or should we close this issue?

**Comment by lathama** [comment]
I feel that this issue got lost in time. @dlorenc can you close this?
