### ISSUE TITLE
Use latest Java 8 (191) for better containerization support 

### ISSUE THREAD

**Issue by anthonydahanne** [GoogleContainerTools/distroless#293]
Hello !

Current Java 8 version in distroless/java is 1.8 build 181 : 

```
$ docker pull gcr.io/distroless/java
Using default tag: latest
latest: Pulling from distroless/java
Digest: sha256:f488c213f278bc5f9ffe3ddf30c5dbb2303a15a74146b738d12453088e662880
Status: Image is up to date for gcr.io/distroless/java:latest
$ docker run  --entrypoint='java'  gcr.io/distroless/java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

Unfortunately, this version is not the latest (202 might be the latest), but even worse, does not include latest containerization fixes added in 191 [1] (that is, btw, [available on Debian project](https://packages.debian.org/sid/openjdk-8-jre-headless), the place I believe distroless/java is getting OpenJDK from)

[1]: https://www.oracle.com/technetwork/java/javase/8u191-relnotes-5032181.html, look for "Java Improvements for Docker Containers"

**Comment by loosebazooka** [comment]
Right, but that's in the `sid` distribution, which is the [unstable debian distribution](https://www.debian.org/releases/sid/). When debian moves that into debian 9(stretch) we'll pick it up.

But as you can see, stretch currently [points to 181 on jre-headless.](https://packages.debian.org/stretch/openjdk-8-jre-headless)

**Comment by anthonydahanne** [comment]
ah ok, makes sense !
let me know if you want me to close this ticket or keep it open as a reminder !

**Comment by chanseokoh** [comment]
Let's leave this open. Not sure if 191 or 202 will be backported to stretch or not. I anticipate the next Debian 10 (buster) will have it, and we may want to move our base to buster at some point.

**Comment by chanseokoh** [comment]
Perhaps we should just switch to AdoptOpenJDK (#298).

**Comment by chanseokoh** [comment]
@anthonydahanne Java 8 images with 8u212 will be auto-published and available soon.
