### ISSUE TITLE
What would it take to add "apk" extraction to `docker_build`

### ISSUE THREAD

**Issue by mattmoor** [GoogleContainerTools/distroless#30]
In the pursuit of tiny images, `udeb` came up, but wasn't sufficient for the JRE.

We should consider whether simply using APK provides smaller footprints.

Here's where `pkg_tar` is extracting the deb's data: https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/pkg/build_tar.py#L147

**Comment by mattmoor** [comment]
@dlorenc FYI

**Comment by dlorenc** [comment]
For java specifically, here's another example of installing a JRE without a package manager, and stripping out lots of parts:
https://github.com/frol/docker-alpine-oraclejdk8/blob/master/Dockerfile

**Comment by dlorenc** [comment]
I don't think APKs and debs will mix and match very well due to the glibc/musl difference, but it might still be worth exploring.

**Comment by mattmoor** [comment]
Yeah, I have started to introduce the nuance of "minimal" vs. "small" in my talking points. 
 Essentially, Alpine is smaller, but not minimal.  What we're doing is minimal, but not at small.

Ultimately, if we have users with the requirement "small at all costs", who aren't concerned about compatibility with glibc, then this route might be an appealing alternative to glibc and debs, but it would require a completely new image stack.

I wonder if in the limit Bazel's cross compilation story will be what we want to key off of here.

**Comment by donmccasland** [comment]
Closing old bugs
