### ISSUE TITLE
distroless/java missing libjpeg.so.62

### ISSUE THREAD

**Issue by RobMaskell** [GoogleContainerTools/distroless#300]
**Description of the issue**: The docker images build ok with Jib, but I get an exception thrown when the container runs. The application is a spring boot 2.1.x app that runs ok in the IDE against java 11.

**Expected behavior**: No exception

**Steps to reproduce**: Jib a spring boot 2.1.x app that uses image handling parts of java 11 and attempt to run the container on your local docker.

**Environment**: Elementary Linux / Java 11 / Gradle / Spring boot 2.1.x

**`jib-gradle-plugin` Configuration**: 
```groovy
sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

bootRun {
  systemProperties = System.properties // needed for intellij
  systemProperties.remove("java.endorsed.dirs")
}

	jib {
		from.image 'gcr.io/distroless/java:11'
		to.image project.getParent().getName() + "/" + bootJar.getBaseName()
		container({
			useCurrentTimestamp = true
			ports = ['80']
			jvmFlags = ['-Djava.security.egd=file:/dev/./urandom', '-XX:+UseG1GC']
		})
		
	}
```

**Log output**: 

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataLoader': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-openjdk-amd64/lib/libjavajpeg.so: libjpeg.so.62: cannot open shared object file: No such file or directory`

`Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-openjdk-amd64/lib/libjavajpeg.so: libjpeg.so.62: cannot open shared object file: No such file or directory`

**Comment by loosebazooka** [comment]
Wonder if we're missing other dependencies from java11 jre headless as well?

**Comment by chanseokoh** [comment]
Probably this is the `libjpeg62` package. No idea about other dependencies. We could look at the package metadata.

**Comment by chanseokoh** [comment]
`openjdk-8-jre-headless` already depended on `libjpeg62-turbo`. It is not a new dependency in Java 11.

```
Package: openjdk-11-jre-headless
Depends: ca-certificates-java, java-common (>= 0.28), libcups2, liblcms2-2 (>= 2.2+git20110628), libjpeg62-turbo (>= 1.3.1), libfontconfig1, libnss3 (>= 2:3.17.1), util-linux (>= 2.26.2-4), libasound2 (>= 1.0.16), libc6 (>= 2.14), libfreetype6 (>= 2.2.1), libgcc1 (>= 1:3.4), libpcsclite1 (>= 1.3.0), libstdc++6 (>= 4.1.1), libx11-6, libxext6, libxi6, libxrender1, libxtst6, zlib1g (>= 1:1.1.4)
```

```
Package: openjdk-8-jre-headless
Depends: ca-certificates-java, java-common (>= 0.28), libcups2, liblcms2-2 (>= 2.2+git20110628), libjpeg62-turbo (>= 1.3.1), libfontconfig1, libnss3 (>= 2:3.17.1), util-linux (>= 2.26.2-4), libc6 (>= 2.14), libfreetype6 (>= 2.2.1), libgcc1 (>= 1:3.0), libpcsclite1 (>= 1.3.0), libstdc++6 (>= 4.1.1), libx11-6, libxext6, libxi6, libxrender1, libxtst6, zlib1g (>= 1:1.1.4)
```

[The package description says "the libjpeg-turbo JPEG library is a library for handling JPEG files."](https://packages.debian.org/sid/libjpeg62-turbo) I think we should add this to both Java 8 / Java 11 images.

Rather, one thing I noticed is that `libasound2` is a new dependency in Java 11, which contains the library for [ALSA (Advanced Linux Sound Architecture)](https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture). It provides the API for sound card device drivers, so chances are that we don't need it for container usage. I'd not add that until we hear from people that it's needed.

I'll add the `libjpeg62-turbo`. Luckily, it depends only on `libc6`.

**Comment by RobMaskell** [comment]
Thanks @chanseokoh happy to test this on my build, can I do that now or do I need to wait for anything to get released?

**Comment by chanseokoh** [comment]
Once #304 is merged, the new image will be automatically built and available at `gcr.io/distroless/java:11`.

If you are impatient, you could try building the image yourself locally. You will need to set up `bazel` though.
1. Clone the repo.
1. Set up `bazel` (and anything extra if needed).
1. `$ bazel run //java:java11` (or `//java:java11_debug`) and the image will be built and pushed into your Docker daemon as `bazel/java:11`. Building takes a lot of time.

**Comment by RobMaskell** [comment]
I can wait for that, no probs, will comment here on how the test goes

**Comment by chanseokoh** [comment]
New images with `libjpeg.so.62` published: https://pantheon.corp.google.com/gcr/images/distroless/GLOBAL/java?gcrImageListsize=30 You can test this out.

**Comment by RobMaskell** [comment]
Yup seems to be working now, thanks @chanseokoh
