### ISSUE TITLE
Jetty start.jar should be in the entrypoint

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/distroless#308]
The setup of the jetty image weird: it inherits the ENTRYPOINT from its base image (`java -jar`) and sets its CMD to `/jetty/start.jar`.  So a normal `docker run gcr.io/distroless/java/jetty` works great.  But Jetty supports different command-line options and even allows configuring new modules on the fly, it would be more helpful for the `ENTRYPOINT` to be `java -jar /jetty/start.jar` with CMD.  

We currently run the following
```sh
$ docker run gcr.io/distroless/java/jetty /jetty/start.jar --help
$ docker run gcr.io/distroless/java/jetty /jetty/start.jar --version
```

whereas with `ENTRYPOINT=java -jar /jetty/start.jar` would also the more natural looking:
```sh
$ docker run gcr.io/distroless/java/jetty --help
$ docker run gcr.io/distroless/java/jetty --version
```

Of course the wrench in the works is #295 but so be it.

**Comment by chanseokoh** [comment]
Makes sense, and this is a very easy fix. However, I'm afraid this is a breaking change.
