### ISSUE TITLE
Unneeded multistage build in python example

### ISSUE THREAD

**Issue by dragetd** [GoogleContainerTools/distroless#309]
https://github.com/GoogleContainerTools/distroless/blob/3507da42b7c2cbe2f1a17ca38f21659898623860/examples/python3/Dockerfile#L5

Why is a multistage build used here? Couldn't the python script be directly added to the distroless image?

**Comment by lathama** [comment]
I created a PR with a better example or you can see https://lathama.net/git/lathama/Dockerfiles/src/branch/master/distroless/cherrypyexample/Dockerfile for more.

**Comment by dragetd** [comment]
This makes a lot more sense! Thank you for this example. :D

But then again: If you copy *all* site-packages, (`/usr/local/lib/python3.6/site-packages`) you are also copying the (potentially unneeded?) pip-related packages if I understand correctly.

So one would basically have to isolate the dependencies in requirements.txt (or pipenv) and their deps from the rest of python packages to have 'minimal' container in the sense of the distroless project, or? (maybe I am missing something here)

**Comment by lathama** [comment]
There could be some kilobytes of unused libraries copied over but a huge advance in minimal containers.

**Comment by dragetd** [comment]
Alright!

I'd love to give it a spin myself with pipenv instead of venv + pip maybe if nobody else does, but sometime later.

Thanks for the efforts! -> Close
