### ISSUE TITLE
Community mailing list/chat room/group for discussion

### ISSUE THREAD

**Issue by lathama** [GoogleContainerTools/distroless#311]
Two questions:
A) What flags can we use to skip builds for documentation only changes like #310 as an example.

B) Is there a community mailing list, chat room, or group that we can join to discuss items?

**Comment by chanseokoh** [comment]
A) I don't really get it. All the projects I've been working on always build even on doc-only changes, and I think I'm happy about it.

B) AFAIK, there's no such thing and this repo is the only channel.

**Comment by lathama** [comment]
Thanks, I had some issues on k/k where a doc update was lost when prow was down. Just asking, no worries.

I would enjoy a communication platform outside of issues/PRs for Distroless. Email mailing list group would be simple.

**Comment by lathama** [comment]
Travis builds are failing right now and it would be great to have a path to discussion about this outside of issues and PRs.

**Comment by blhagadorn** [comment]
Hey all, did we ever come to some concensus around a place to discuss? Somewhere on k8s slack or elsewhere? Would love to discuss distroless if possible anywhere @lathama

**Comment by lathama** [comment]
@blhagadorn we did not come to any consensus on chat or mailing list. I suggest a mailing list as a stop gap. Here is a simple "users" list at https://groups.google.com/forum/#!forum/distroless-users

**Comment by blhagadorn** [comment]
Ok that works, I have also asked the mods to make a channel in the Kubernetes slack. Would love to see more traction around distroless

**Comment by blhagadorn** [comment]
Currently getting `You do not have permission to access this content. (#418)` FYI

**Comment by lathama** [comment]
@blhagadorn thanks, the defaults were very restrictive. Sorry for the trouble. Testing in an incognito browser and it appears to be opened up now.

**Comment by blhagadorn** [comment]
No problem thank you for setting it up!

**Comment by donmccasland** [comment]
Hey there, I've been given the task of doing release management for distroless and we had just decided to start a slack channel on this.  Thanks for being ahead of me on this!

**Comment by lathama** [comment]
@donmccasland I just got home but will try to connect with you Thursday.

**Comment by donmccasland** [comment]
https://github.com/kubernetes/community/pull/4206

**Comment by donmccasland** [comment]
@lathama awesome
