### ISSUE TITLE
How to add grpc-health-prober (or similar tool) based on one of the stock images

### ISSUE THREAD

**Issue by diemtvu** [GoogleContainerTools/distroless#319]
I want to add [gRPC health check](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/) to my service (in Java). But that instruction requires the container contain the grpc_health_probe (and probably shell environment to run). Is there simple way to do so?

**Comment by chanseokoh** [comment]
Hi @diemtvu, I have never used `grpc_health_probe`, but according to the dock, I think probably you just add the `grpc_health_probe` binary yourself and configure Kubernetes to call it? I see installing the binary into a container and configuring Kubernetes is pretty well documented in this [example](https://github.com/grpc-ecosystem/grpc-health-probe/tree/1329d682b4232c102600b5e7886df8ffdcaf9e26#example-grpc-health-checking-on-kubernetes). I don't think you'll ever need to run a shell.

**Comment by diemtvu** [comment]
In that example, you need to build the docker image with `grpc_health_probe`, which not doable if I'm using  distroless image like `gcr.io/distroless/java:8`. For now, I have to use `openjdk:8-jre-alpine` instead, which lost all the benefit of distroless.

**Comment by chanseokoh** [comment]
Sorry @diemtvu, I didn't get. Why is it not doable? I think you could do

1. Download the binary and do `chmod +x`
1. Create `Dockerfile`:
   ```
   FROM gcr.io/distroless/cc:debug
   COPY grpc_health_probe* /bin/grpc_health_probe
   ```
1. `$ docker build -t my-distroless .`

**Comment by diemtvu** [comment]
I can build the image, but cannot run it. I.e, the command /bin/grpc_health_probe cannot be executed, I guess because of the lack of shell environment.

**Comment by chanseokoh** [comment]
Looks like you have a misunderstanding of what a shell does. A shell isn't needed to run a program. For example, the Java distroless has an executable `/usr/bin/java` (the JVM binary), and programs don't need a shell to execute. A shell is a type of UI for humans.

If you cannot run the `grpc_health_probe`, then there must be a different reason.

**Comment by chanseokoh** [comment]
To give you a better insight, a shell program is no special in that it's yet another executable (`/bin/sh`) not really different from `/bin/ls`, `/bin/grpc_health_probe`, or `/usr/bin/java`. It's just that, while the `/bin/ls` program will print the list of files to stdout, the `/bin/sh` program is written in a way that it enters into an infinite loop to start accepting user input through the UI called "command line". And one of the useful features of the shell program is that, when the user types a name of another program like `/bin/ls`, it will fork a new child process for that.

So, as much as you can execute `/bin/sh` or `/usr/bin/java`, you should be able to execute `/bin/grpc_health_probe`. I'll close this issue, but if you still have difficulty executing `/bin/grpc_health_probe` for some reason, feel free to re-open the issue.
