### ISSUE TITLE
Update java:8 openjdk to openjdk 8u191+ (latest is 8u202)

### ISSUE THREAD

**Issue by saturnism** [GoogleContainerTools/distroless#324]
currently java:8 image uses 8u181, which can be made cgroup memory aware (distroless image already turned on this option). however, 8u181 is not cgroup cpu aware. I.e., JVM will see host cpu cores rather than the cgroup limits.

8u191+ have +UseContainerSupport enabled by default and is both cgroup memory & cpu aware.

**Comment by chanseokoh** [comment]
I'll close this as a dup of #293.
