### ISSUE TITLE
java: add libtcnative for native tomcat bridge

### ISSUE THREAD

**Issue by HazCod** [GoogleContainerTools/distroless#325]
Hello,

When using e.g. Spring Boot (or any other framework that uses the tomcat library), performance can be greatly improved when using the native tomcat bridge libtcnative (uses Apache Portable Runtime).

Can this be added to the distroless/java image?

**Comment by chanseokoh** [comment]
Thanks for the feedback @HazCod.

I've briefly looked into some docs, and I feel this library is too specific to be in Distroless, as it is only relevant with Tomcat, which Distroless doesn't care about.

Another supporting reason for my hesitation is that it is easy to install. As long as you can drop a library file and let Tomcat find it, I think it should work.
   - Officially, it is the usual `./configure && make && make install`: https://tomcat.apache.org/tomcat-8.5-doc/apr.html, although you can't do this on Distroless, of course.
   - Alternatively, [this SO answer](https://stackoverflow.com/a/8717883/1701388) says it just amounts to drop a shared library file (`.so`).
   - Looking into the [`libcnative` Debian package](https://packages.debian.org/stretch/amd64/libtcnative-1/filelist), indeed it is basically just two library files (one static, and the other shared). But almost certainly you won't need a static library.

**Comment by HazCod** [comment]
So in essence, I could do away with the following;
```
FROM debian:<version> AS builder
RUN apt install --yes libcnative

FROM distroless-java
COPY --from=builder /usr/lib/x86_64-linux-gnu/libtcnative-1.so /libcnative.so
```

What is the used debian versioning?

**Comment by chanseokoh** [comment]
Ah, the multi-stage build is a very good option. That's for adding another detailed example.

We pin to a specific Debian 9 (stretch) snapshot. (We periodically update the pointer to the snapshot, so it moves over time.) Then we get all the package info from the snapshot and get the package versions to download from, e.g., http://ftp.debian.org/debian/pool/main/t/tomcat-native/. But honestly, I think there will be few changes to Debian 9 snapshots, especially for `libtcnative` with the upcoming Debian 10 (buster). I think you can just use `debian:stretch`. I even think `debian:buster` may just work fine.

**Comment by chanseokoh** [comment]
> When using e.g. Spring Boot (or any other framework that uses the tomcat library), performance can be greatly improved when using the native tomcat bridge libtcnative (uses Apache Portable Runtime).

However, it is also true that Tomcat is very popular and used by many frameworks including Spring Boot. It is nice to have good support for Spring Boot, so I'm open for discussion. You said "greatly improved", but is there any reference or statistics that evidence the considerable performance improvement?

**Comment by HazCod** [comment]
Reading through [this presentation](https://events.static.linuxfound.org/sites/events/files/slides/TomcatOpenSSL.pdf), it seems Tomcat 9 already greatly improves performance (sometimes better than the APR bridge) by using openssl.

**Comment by chanseokoh** [comment]
Aha! Thanks for the ref. Yeah, sounds like APR isn't going to be much needed going forward.

**Comment by HazCod** [comment]
Thanks for the assistance @chanseokoh !
