### ISSUE TITLE
Update policy?

### ISSUE THREAD

**Issue by hazcod** [GoogleContainerTools/distroless#326]
Hello,

I see no reference of how often the images are rebuilt, and thus how fast we can expect security updates for libc/jvm/... to come in for the same tag.

How often is this done?

**Comment by chanseokoh** [comment]
I can't give an authoritative answer, but I remember this comment: https://github.com/GoogleContainerTools/distroless/issues/238#issuecomment-419225907

As for JVM, we pull the OpenJDK (jre-headless) package from Debian stretch. With the upcoming Debian Buster, it's hard to tell if there will be more OpenJDK package updates to stretch. For example, for Java 8, we have been stuck with [8u181](https://github.com/GoogleContainerTools/distroless/issues/238#issuecomment-419225907). And it's even a possibility that Debian 10 may drop OpenJDK 8 and we are seriously considering switching to AdoptOpenJDK (#298). However, I can't say we will work on that in the near future.

**Comment by HazCod** [comment]
Supposing we go for the latest & greatest, distroless would receive updates for OpenJDK 11.
But the question is how often are the debian:buster images updates, and do you automatically rebuild on every upstream image change?

**Comment by Tetradeus** [comment]
We are facing an ssl issue with openjdk 11.0.1 fixed in 11.0.2.
https://bugs.openjdk.java.net/browse/JDK-8210005

We are now stuck and have to build our own image. 

Considering using AdoptOpenJDK would be really great.

**Comment by chanseokoh** [comment]
@Tetradeus Distroless is shipping openjdk 11.0.5: #420 Check out the lastest image.

**Comment by Tetradeus** [comment]
@chanseokoh thanks for the info. I just looked at a misleading comment in jre_ver.bzl, sorry for the inconvenience.

**Comment by chanseokoh** [comment]
We just set up GitHub Actions to automate pulling in new deb packages updated in the Debian snapshot upstream: #537. I will close this as a dup of #537.
