### ISSUE TITLE
NodeJS image : web server not accessible

### ISSUE THREAD

**Issue by LM1LC3N7** [GoogleContainerTools/distroless#328]
Hello,

I have successfully created a docker image containing flood (a web interface for rtorrent).
But if I start this image without exposing publicly the port 3000, the web server is not accessible by the reverse proxy (traefik) nor from the host by using the container IP (ERR_CONNECTION_REFUSED).

If I expose it publicly, then the web server is still only accessible from internet, not from traefik nor localhost.

I try to create another container for TryGhost/Ghost, same problem. The web server is started and is waiting for connections on 0.0.0.0, but the connection is refused from the docker host or the proxy container.

Any help about it? Thanks 😄

**Comment by LM1LC3N7** [comment]
**Flood Dockerfile**

```bash
#
# Multi-stage Dockerfile
#


#
# Stage 1:
# ----- Building flood -----
#

FROM node:8-stretch as flood-build

COPY rootfs/app/flood/config.js /app/flood/config.js

RUN echo \
 && echo "[*] Installing flood dependencies" \
 && apt-get update && apt-get install -y \
    python \
    make \
    g++ \
    git \
    curl \
    tar \
 && echo \
 && echo "[*] Installing flood" \
 && echo \
 && mkdir -p /app/flood && cd /app/flood \
 && mv /app/flood/config.js /tmp \
 && git clone https://github.com/jfurrow/flood.git . \
 && mv /tmp/config.js /app/flood \
 && npm install \
 && echo \
 && echo "[*] Building flood assets" \
 && npm run build \
# && npm prune --production \
 && npm cache clean --force


#
# Stage 2:
# ----- Creating final image -----
#
FROM gcr.io/distroless/nodejs
ENV HOME=/app/food

COPY --from=flood-build /app/flood /app/flood
COPY --from=flood-build /usr/bin/curl /usr/bin/curl

WORKDIR /app/flood

VOLUME /app/flood/flood-db

EXPOSE 3000

LABEL description="flood interface for rTorrent running on distroless" \
      maintainer="LM1LC3N7 <my@email.com>"

CMD ["server/bin/start"]

```

**Comment by chanseokoh** [comment]
Not sure on which platform/infrastructure you are running this image, but at least if you want to make this work when running the image on your local machine, I think you'd want to add `-p 3000:3000` when running `docker run`. I assume the frontend inside image is listening on the `0.0.0.0:3000`. (I don't know much about Traefik.) You'd able to connect to the frontend from your local machine with `curl localhost:3000`.

**Comment by LM1LC3N7** [comment]
The host is a CentOS 7.

For all of my services I don't expose publicly ports and only use local docker network.
There is only traefik (a proxy) that expose his ports.

For example I have a gitlab not exposing his ports and still being joinable through traefik.

**Comment by LM1LC3N7** [comment]
I have an alpine version with almost the same Dockerfile working (without exposing ports).

**Comment by chanseokoh** [comment]
Ah, OK. Basically, you run `docker run` on some remote host (CentOS 7). I see `--network=proxy`, and I guess `proxy` is the name of a network you defined/created. Unfortunately, I have no expertise on this domain of network with Docker. Do you think this is the problem of Distroless? For me, that seems unclear (but again, I don't have much knowledge on this subject.). Do you find any error logs?

**Comment by LM1LC3N7** [comment]
I think this is caused by distroless because a container almost identical (same service based on alpine) with the same docker run command is working.

**Comment by chanseokoh** [comment]
In this case, it's not feasible to replicate your environment, especially the network stack and with Traefik, so I think you need to perform some diagnosis and provide as much information as possible, including relevant error logs.

**Comment by LM1LC3N7** [comment]
I understand.

Here what I tried.

Starting the distroless version:

```
$ docker run \
  --name="flood-distroless" \
  --detach \
  lmilcent/flood:distroless
Flood server starting on http://0.0.0.0:3000
```

Starting the alpine version:

```
$ docker run \
  --name="flood-alpine" \
  --detach \
  lmilcent/flood:alpine
Flood server starting on http://0.0.0.0:3000
```


On the host:

```
$ docker inspect flood-distroless | grep IPAddress
"IPAddress": "172.17.0.3"

$ wget http://172.17.0.3:3000
wget: can't connect to remote host (172.17.0.3): connection refused.

$ docker inspect flood-alpine | grep IPAddress
"IPAddress": "172.17.0.4"

$ wget http://172.17.0.4:3000
Connecting to 172.17.0.4:3000
index.html
```

**Comment by chanseokoh** [comment]
Could you check the Docker daemon log and the Traefik log to see if you find anything relevant? The OS network log may (or may not) have some info too.

And maybe this is helpful for troubleshooting: https://success.docker.com/article/troubleshooting-container-networking

**Comment by chanseokoh** [comment]
And perhaps for the OS log, you may have to check it both inside and outside the container. `distroless/nodejs:debug` has a shell at `/busybox/sh` you can use to explore the inside.

**Comment by LM1LC3N7** [comment]
I tried the debug image and found out that DNS queries are sent (shown in docker and iptables logs) from the distroless container.

The distroless container never succeed in contacting the local network, but can do it with Google.com...

```bash
# wget <server public up>
Cannot connect to remote host

# wget google.com
Connecting to google.com
index.html
```

**Comment by chanseokoh** [comment]
My gut feeling is that something's not working properly with the Docker container networking through the user-defined `proxy` network for some reason. What does `docker network inspect proxy` say? I wonder if you can test this with a simpler user-defined network that doesn't use Traefik to narrow down the scope. I would also try `ping localhost`, `ping 0.0.0.0`, `ifconfig -a` (on the host and in the container), `ip addr show`, etc. to gather more info.

**Comment by LM1LC3N7** [comment]
Also:

* Start a new clean distroless container :

```
$ docker run -ti  --name test --rm gcr.io/distroless/nodejs:debug
>
```

* Open sh and try to ping the gateway and a local service (my blog) trough internet

```
$ docker exec -ti test sh
# nc 172.17.0.1
```

Nothing is working.

**Comment by chanseokoh** [comment]
`nc` requires both host and port when opening a connection through TCP.

**Comment by LM1LC3N7** [comment]
Of course sorry I didn't write it here but I tried on ports 22 and 80.

**Comment by chanseokoh** [comment]
I see. It works on my env, so I think there's something specific about your env that's causing the issue.

From my host, when using the default bridged network when running docker as you did:
```
host$ nc localhost 22
SSH-2.0-OpenSSH_7.9 GoogleMDI-2.0
^C
host$ ifconfig docker0
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.9.1  netmask 255.255.255.0  broadcast 192.168.9.255
        inet6 fe80::42:1fff:fe30:2fab  prefixlen 64  scopeid 0x20<link>
        ether 02:42:1f:30:2f:ab  txqueuelen 0  (Ethernet)
        RX packets 865118  bytes 3960006520 (3.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1340449  bytes 10165814684 (9.4 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
host $ docker run --rm -it --entrypoint /busybox/sh gcr.io/distroless/java:debug
/ # nc 192.168.9.1 22
SSH-2.0-OpenSSH_7.9 GoogleMDI-2.0
^Cpunt!

/ # exit
host$
```
A suspect, e.g., a proxy in your env is blocking something?

**Comment by chanseokoh** [comment]
I've also tried a real example with the NodeJS image.

```Dockerfile
FROM node:8.15.0 AS build-env
ADD . /app
WORKDIR /app

FROM gcr.io/distroless/nodejs
COPY --from=build-env /app /app
WORKDIR /app
CMD ["hello_http.js"]
```

```
$ docker build -t my-nodejs .

$ docker run --rm --name my-nodejs-run my-nodejs
Server running at http://127.0.0.1:8000/

$ docker inspect my-nodejs-run | grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "192.168.9.2",
                    "IPAddress": "192.168.9.2",

$ curl http://192.168.9.2:8000
Hello World
```

**Comment by LM1LC3N7** [comment]
Thank you for your time!

It can be an error on my side but I don't know what and why. I continue to investigate.

**Comment by LM1LC3N7** [comment]
I found the error, my bad :confounded:

The Dockerfile was contening an error I didn't saw:

```bash
ENV HOME=/app/food
```

Correct line:
```bash
ENV HOME=/app/flood
```

But I don't understand why this error was blocking the container network.

Thanks all for your time and fast responses!

**Comment by chanseokoh** [comment]
Thanks for the update!
