### ISSUE TITLE
Put a `nobody` user into /etc/passwd

### ISSUE THREAD

**Issue by thockin** [GoogleContainerTools/distroless#332]
Having a named, non-root user and group in the base image would make non-root use-cases easier.  It seems like a pretty common practice to say "USER nobody:nobody" in a Dockerfile.

**Comment by HazCod** [comment]
Indeed, especially when people do not configure user namespace remapping.


What I do for the moment is copying over `/etc/shadow`, `/etc/group` and `/etc/passwd` from an alpine image where I remove every user expect root and nobody + disable login shells for everyone.
```
FROM alpine:latest AS builder
RUN sed -i -r "/^(root|nobody)/!d" /etc/passwd /etc/shadow /etc/group \
    && sed -i -r 's#^(.*):[^:]*$#\1:/sbin/nologin#' /etc/passwd

FROM gcr.io/distroless/java:11
COPY --from=builder /etc/passwd /etc/shadow /etc/group /etc/
USER nobody
```

**Comment by chanseokoh** [comment]
Just for those who haven't realized: you can use a number and not put anything into `/etc/passwd` or `/etc/group`.

```
USER 65543:65543
```

The Linux kernel just sees these numbers. The names are purely cosmetic that various tools map for human consumption.

**Comment by thockin** [comment]
Some apps get unhappy when they can't resolve UIDs/GIDs.

**Comment by chanseokoh** [comment]
@thockin I'm personally curious. What's the app that's causing an issue to you? Does the app not accept numbers?

**Comment by thockin** [comment]
I hit this with SSH, which was not running `distroless` but convinced me
that this is not a case of universal "just use numbers" as a solution :)

So I built my own templates to use `USER nobody:nobody`.  Switching that
from Alpine to distroless broke.  That's what motivated this.  If we can
get people to switch, it's a net positive for the world, so we should
reduce friction in any way possible.

**Comment by chanseokoh** [comment]
#335 merged. The new images will be auto-published soon. Thanks @thockin!

**Comment by HazCod** [comment]
Do note that /bin/bash was added as a shell instead of /sbin/nologin, and not uid 1000.

**Comment by chanseokoh** [comment]
Hmm... although `/bin/bash` doesn't exist and Distroless has been adding `/bin/bash` for root as well, that's a good point. It's easy to change it to `/sbin/nologin` (which doesn't exist either).

But I think using [65534 for `nobody` is common](http://www.linfo.org/uid.html).

**Comment by chanseokoh** [comment]
Filed #337.

**Comment by HazCod** [comment]
Thanks! Can we add a USER directive aswel, or will that interfere with the COPY?

**Comment by chanseokoh** [comment]
Sorry @HazCod, I didn't really get it, but if you were asking how your `Dockerfile` would look like with the new images with `nobody`, you no longer need a multi-stage build or `COPY` in regarding https://github.com/GoogleContainerTools/distroless/issues/332#issuecomment-476101270. You would probably just do
```Dockerfile
FROM gcr.io/distroless/java:11
USER nobody:nobody
```
and that's it.

**Comment by HazCod** [comment]
@chanseokoh I mean having a `USER nobody:nobody` in `gcr.io/distroless/java` itself, so people will no longer have to specify it manually.
Every file copied into the container using `COPY` will also automatically inherit the user ownership.

**Comment by chanseokoh** [comment]
@HazCod ah, I was sure I was missing something. I had written some thoughts on this: https://github.com/GoogleContainerTools/distroless/issues/306#issuecomment-466113438. Personally I think we are fine with running as root.
