### ISSUE TITLE
Docker Inside Docker (DinD)

### ISSUE THREAD

**Issue by rajivml** [GoogleContainerTools/distroless#334]
HI,

We are using Alpine-Java8 Container image to package our Spring Boot Apps which will eventually run on top of GKE. 

The problem we are facing is, spring-cloud-sleuth-gcp library internally uses GRPC and Alpine-Java8 container doesn't have inbuilt support for GRPC and we have tried many approaches but nothing worked.
https://github.com/spring-cloud/spring-cloud-sleuth/issues/1265#issuecomment-475181770

One alternative to overcome this issue is to use google's distroless java8 container image instead of Alpine. 
But in one of our modules we have an use case where we are building docker images from within a docker container (DIND) running on top of GKE and in order to achieve this we are spawning docker and container daemons on the main docker container

But google's distroless java container unlike Alpine doesn't have support for running background processes/daemons nor does it has shell so that we can pull in other packages and right now this is a blocker for us to start using distroless instead of Alpine.

Please find the scripts attached, which we are using to build the base docker image along with the docker and container daemons running which assists us in building docker images based out of s2i plugin.

Command which is used to trigger s2i build from a docker image:
s2i build /path/where/the/source/code/resides seldonio/seldon-core-s2i-python3:0.4 gcr.io/dave-225414/host/issue-summarization:0.3 --loglevel=2 --env MODEL_NAME="IssueSummarization" --env PERSISTENCE="0" --env SERVICE_TYPE="MODEL" --env API_TYPE="REST"

Please advise us on how can we achieve the same functionality(DIND) using distroless Container Image.

Main Docker Image Code:
```

# Alpine Linux with OpenJDK JRE
FROM docker.io/openjdk:8-jre-alpine

USER root

#create working directory
RUN ["mkdir", "-p","/app"]
WORKDIR /app

#install curl tar docker
RUN apk add --no-cache curl
RUN apk add --no-cache tar
RUN apk add --no-cache docker

# install s2i
RUN (curl -L https://github.com/openshift/source-to-image/releases/download/v1.1.13/source-to-image-v1.1.13-b54d75d3-linux-amd64.tar.gz | tar -zxf - ./s2i)

#Move s2i to path
RUN ["cp", "./s2i", "/usr/local/bin"]

#Move to working directory
WORKDIR /app

# copy JAR into image
COPY ["maven/xxx-1.0.0-SNAPSHOT.jar", "xxxx.jar"]

#copy entrypoint.sh script
COPY ["entrypoint.sh", "/app"]

#provide executable permission to script
RUN ["chmod", "a+x", "/app/entrypoint.sh"]

#Expose port 8084
EXPOSE 8084

#https://github.com/docker/docker/blob/master/project/PACKAGERS.md#runtime-dependencies
RUN set -eux; \
	apk add --no-cache \
		btrfs-progs \
		e2fsprogs \
		e2fsprogs-extra \
		xfsprogs \
		xz \
# pigz: https://github.com/moby/moby/pull/35697 (faster gzip implementation)
		pigz \
	; \
# only install zfs if it's available for the current architecture
# https://git.alpinelinux.org/cgit/aports/tree/main/zfs/APKBUILD?h=3.6-stable#n9 ("all !armhf !ppc64le" as of 2017-11-01)
# "apk info XYZ" exits with a zero exit code but no output when the package exists but not for this arch
	if zfs="$(apk info --no-cache --quiet zfs)" && [ -n "$zfs" ]; then \
		apk add --no-cache zfs; \
fi

# set up subuid/subgid so that "--userns-remap=default" works out-of-the-box
RUN set -x \
	&& addgroup -S dockremap \
	&& adduser -S -G dockremap dockremap \
	&& echo 'dockremap:165536:65536' >> /etc/subuid \
	&& echo 'dockremap:165536:65536' >> /etc/subgid

#Environment variable for docker host
ENV DOCKER_HOST "tcp://127.0.0.1:2375"

# Define docker volume
VOLUME /var/lib/docker

# run application with this command line
ENTRYPOINT ["sh", "/app/entrypoint.sh"]
CMD ["java", "-jar", "-Dspring.profiles.active=dev", "xxxxx.jar"]


EntryPoint.sh Code:

#!/bin/sh

# Start docker daemon
dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 &

# start container daemon
containerd --config /var/run/docker/containerd/containerd.toml --log-level info &

# This will exec the CMD from Dockerfile, i.e. "java -jar"
exec "$@"
```

**Comment by chanseokoh** [comment]
Hi @rajivml,

Theoretically this should be doable, e.g., using a multi-stage builds. (You should not use `alpine` because generally binaries are incompatible between `alpine` and other common Linux distros). For example, the s2i binary seems to be the easiest one to install, as it seems like a single, statically linked binary.

```Dockerfile
# Don't use alpine, as explained above.
FROM debian:stretch AS preparer
RUN apt-get update && apt-get install curl <and whatever>

# install s2i
RUN (curl -L https://github.com/openshift/source-to-image/releases/download/v1.1.13/source-to-image-v1.1.13-b54d75d3-linux-amd64.tar.gz | tar -zxf - ./s2i)

FROM gcr.io/distroless/java
COPY --from=preparer /path/to/in/prepare/s2i /usr/local/bin/s2i
```

I see you also need `/bin/sh`to run the shell script. You could try [Busybox](https://busybox.net/).
> EntryPoint.sh Code:
> ```
> #!/bin/sh
> ```

However, technically you would be able to copy whatever files/binaries/config files you need including dockerd and such, I think the task will become really tedious to make it right and the process may be fragile. You could also hit the case not all the dependencies (including transitive dependencies) are there in distroless and you would have to find and install them manually. For example, some application requires various shared libraries (`.so` files) and you end up copying them manually from the `preparer` image to distroless. So honestly, I think I'd better go with another image that has a package manager and a shell installed.

**Comment by rajivml** [comment]
Thanks for the immediate reply. I was looking at distroless just because it's smaller in size similar to Alpine so that it's easy to build and test things and also since we are heavily relying on google stack we are rest assured that what ever libraries we pick in future will work seamlessly.

Am using shell just to trigger the below background processes, is there a way to trigger the same without 
the shell ?

# Start docker daemon
dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 &
# start container daemon
containerd --config /var/run/docker/containerd/containerd.toml --log-level info &

One other alternative which I looked at was kaniko, because I read at multiple places that running background processes inside a docker container isn't a good practice as kubernetes doesn't have control/visibility on those background processes, but I found, even kaniko doesn't have support for s2i

https://github.com/GoogleContainerTools/kaniko

**Comment by chanseokoh** [comment]
> Am using shell just to trigger the below background processes, is there a way to trigger the same without
the shell ?

Hmm... create a Java program that forks the two `dockerd` and `containerd` child processes and executes the given arguments as a last step? Or, install some simple language interpreter binary for which you can write a simple script to do the said task easily? But then, this sounds no less simple than having `/bin/sh` and writing a shell script for that.

> I read at multiple places that running background processes inside a docker container isn't a good practice

Yeah, now you said it, it is often said this is [not a good practice](https://cloud.google.com/solutions/best-practices-for-building-containers#package_a_single_app_per_container)  (although [some folks don't always agree](https://github.com/just-containers/s6-overlay#the-docker-way)).

BTW, I still don't get why you want DinD, probably because I don't fully get your use case. Do you have to build an image dynamically at runtime? Can't you build an app (a python app in this case?) and just copy it over to distroless using a multi-stage build for example?

**Comment by rajivml** [comment]
This is my use case, we have some services running on top of GKE and one of the service is deployment service whose job is package the code uploaded by the enduser as a docker image so that the resulting docker image can be deployed on to kubernetes as a webservice

So to build images based out of app uploaded by the user, we use s2i build tool which takes source code and a base python/java docker image as input and emits an final docker image with code packaged into it in a particular format, here s2i is just a docker build and for the docker build to happen docker and container daemons has to be running .

And at a time on a pod multiple builds can also happen in parallel.

Hope u get some clarity on usecase now, plz let me know if things are not yet clear.

So, what would be the right architecture for this usecase , would kaniko/distroless work here?

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by chanseokoh** [comment]
Thanks. That's very clear. It's a very interesting use case. @GoogleContainerTools/container-tools @GoogleContainerTools/java-tools any advice on this (a service running on Kubernetes that buidls a Docker image from source)?

**Comment by patflynn** [comment]
this does seem like a good use-case for Kaniko.  Running Docker in Docker for user-provided inputs seems like a big security concern.

**Comment by rajivml** [comment]
So, is it possible to run s2i builds from kaniko today ? I have seen multiple people requesting for the same and it isn't possible today. Plz, let me know if it's not the case and some steps on how can we achieve this. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by patflynn** [comment]
@rajivml perhaps you should ask this question on the kaniko or buildpacks repos.  We're definitely not experts in this area.

If you don't care about security presumably you could run docker in a separate container. It shouldn't have to run in the same container as your Java process.

**Comment by rajivml** [comment]
@patflynn since we are building a SAAS offering based on google cloud Infra, security is equally important. Can you please elaborate on what kind of security and performance issues we may run into

**Comment by patflynn** [comment]
@rajivml we're not experts in the area, but this bug: https://github.com/kubernetes/kubernetes/issues/1806 is probably a good place to start getting context on this.

**Comment by chanseokoh** [comment]
@rajivml I'm sure you've the answers by now. I'll close the issue.
