### ISSUE TITLE
buildifier.sh does not work at all

### ISSUE THREAD

**Issue by thockin** [GoogleContainerTools/distroless#336]
I have a known lint error in base/BUILD.

When I run ./buildifier.sh, I get no output and a success error code.

When I run buildifier -mode=check $(find . -name 'BUILD*' -o -name 'WORKSPACE*' -type f), I get a flag on base/BUILD but a success error code (0).

buildifier.sh is checking for a non-success error code, so it will never work.

Aside:

As a casual contributor, it's scary to be told "Go wget and run this binary". It would be nicer if that was more transparent (and in fact if it "just worked" from HEAD -- even a docker run in a script...)

**Comment by chanseokoh** [comment]
I see you're a Googler. I kind of remember something wonky when working in corp env because it was picking up an internal `buildifier` binary.

I think the `CONTRIBUTING` doc should list the requirement to download and install the right buildifier.

**Comment by thockin** [comment]
Indeed, if I specifically set PATH=., it does find it.

IMO this should be captured in a `docker run` or something that isolates
the builds here from the user's random environment.  Feel free to close
this, I guess.

Thanks.

**Comment by briandealwis** [comment]
The builds downloads its own copy of `container-structure-test`, so it should be able to setup its own copy of buildifier too.
