### ISSUE TITLE
Can we publish the list of distroless supported architectures?

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/distroless#346]
Hi,

We are trying to use distroless as the base image for kubernetes images (See details [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md)) These containers can run in different architectures (am64, arm32v6,arm64v8,ppc64le, s390x).

I couldn't find any resource giving the full list of distroless supported architectures, so I think maybe I should file this issue. Can we have an official list of distroless supported architectures?

I also found issue #222. Is there any plans on supporting the following architectures: am64, arm32v6,arm64v8,ppc64le, s390x  ?

**Comment by tallclair** [comment]
See this comment: https://github.com/GoogleContainerTools/distroless/pull/259#issuecomment-447986989

We're just using distroless:static in Kubernetes, which doesn't have any binary components, so doesn't need multi-architecture builds

**Comment by yuwenma** [comment]
@tallclair Thanks Tim. Then I'm good to move forward. Will keep this issue open to track further discussions about publishing an official architecture list.

**Comment by chanseokoh** [comment]
FTR: https://github.com/bazelbuild/rules_docker/issues/300

X-ref: #406 #569

**Comment by rpsene** [comment]
@chanseokoh not arch agnostic:

![Screen Shot 2020-08-18 at 15 20 43](https://user-images.githubusercontent.com/20800562/90550583-83100380-e166-11ea-9034-176a7b5e2303.png)

**Comment by chanseokoh** [comment]
Yup, certainly, the image configuration contains platform information. What I'm telling you is that, everything else except the image metadata are most likely platform-agonistic.

**Comment by jonjohnsonjr** [comment]
The actual contents of the image aren't platform specific -- I assume the config file values are just a historical curiosity.

I ran into something similar in https://github.com/google/go-containerregistry/issues/751 where we accidentally were omitting those fields and it worked for everything except for windows... if rules_docker allows us to just drop the architecture, that might be enough to get container runtimes to be happy?
