### ISSUE TITLE
Include JVM instrumentation binaries in the distroless/java image

### ISSUE THREAD

**Issue by mikaelstaldal** [GoogleContainerTools/distroless#350]
It would be useful to include the JVM instrumentation binaries in the distroless/java image. They are really small (approx. 10 KiB each). You cannot use them from outside of the container to connect to a JVM in the container, so you have to use `docker exec` to run them from within the container.

- `jcmd`
- `jinfo`
- `jmap`
- `jstack`
- `jstat`

**Comment by briandealwis** [comment]
Maybe suitable for the `:debug` image.

**Comment by mikaelstaldal** [comment]
I would prefer to have them in the main/production image as well, they are useful for instrumenting a JVM in production. The increase of the image size would be minimal, they are only 62016 bytes in total (for Java 11).

But having them in the debug image is better than nothing.

**Comment by mikaelstaldal** [comment]
(`jps` is probably not very useful since you usually only have one JVM process with PID 1.)

**Comment by patflynn** [comment]
without a way to ssh into the container, how would you use the tools?

Perhaps this would be a good use-case for ephemeral containers
<https://github.com/kubernetes/enhancements/issues/277> if/when they become
available.

**Comment by mikaelstaldal** [comment]
You can use them with `docker exec`. I have tried to add them do a custom image based on `distroless/java` and then it works to do `docker exec`.

**Comment by mikaelstaldal** [comment]
Not sure if this would work with ephemeral containers, since those tools only works within the **same** container.

**Comment by patflynn** [comment]
ah duh. of course. I should not comment on issues so early in the morning. 

I was thinking that the [process namespace sharing](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/pod-pid-namespace.md), would make ephemeral containers potentially support your use-case, but I haven't looked into it at all closely.

**Comment by mikaelstaldal** [comment]
Not sure if process namespace sharing would help, I don't know exactly how those tools connect to the JVM process.

**Comment by mikaelstaldal** [comment]
And it would be nice to be able to use this even when not using Kubernetes.

**Comment by patflynn** [comment]
+1 to including these tools in :debug.  Internally we tend not to need them because we expose most of the same data through other means.   I believe a lot of external server stacks publish diagnostics on specific urls or with JMX.

**Comment by mikaelstaldal** [comment]
It is not only about getting stats, it is also about instrumenting with `jcmd`, like starting/stopping Flight Recording.

**Comment by varundhall** [comment]
Any idea when this will be introduced?

**Comment by lazystone** [comment]
I would not like to have additional tools in base distroless java image. I like it to be as small as possible. If you need those for debugging/profiling - create new image and use it.

**Comment by donmccasland** [comment]
@chanseokoh can you comment on this one?

**Comment by chanseokoh** [comment]
If we add these tools, I think it should be to `:debug` images as others mentioned. And yes, I think it is useful to include them. But doing this work is a fairly low priority, since as others pointed out, it's easy for one to create a custom image with such tools.
