### ISSUE TITLE
Update openssl to 1.1.1 to support TLS1.3

### ISSUE THREAD

**Issue by yegle** [GoogleContainerTools/distroless#353]
Can we get openssl 1.1.1 in the image so that binaries that depend on OpenSSL can get TLS 1.3 support?

**Comment by yegle** [comment]
Possibly related: https://github.com/GoogleContainerTools/distroless/issues/326

**Comment by briandealwis** [comment]
openssl is still at 1.1.0 in stretch

https://tracker.debian.org/pkg/openssl

**Comment by yegle** [comment]
Sounds like you should maintain additional versions that maps to Debian's stable/testing? I.e. `gcr.io/distroless/base:stable` and `gcr.io/distroless/base:testing`.

The current testing (Buster) is entering full freeze and the next stable release is imminent. It probably a good idea to at least start the planning of using packages from Debian Buster.

**Comment by kalexmills** [comment]
It sounds like maintaining additional versions of the base image which point to stable/sid upstreams could potentially be used to resolve #364 as well.

**Comment by yegle** [comment]
FYI Debian Burster was promoted from testing to stable today. When should we expect the distroless to be updated to the versions in Debian Burster?

**Comment by donmccasland** [comment]
We have now released debian10 based images.  

openssl is still at 1.1.0 in stretch

https://tracker.debian.org/pkg/openssl

**Comment by chanseokoh** [comment]
We just set up GitHub Actions to automate pulling in new deb packages updated in the Debian snapshot upstream: #537.
