### ISSUE TITLE
Consider having the default distroless tags use non-root user by default

### ISSUE THREAD

**Issue by dprotaso** [GoogleContainerTools/distroless#374]
Continuing the discussion from https://github.com/GoogleContainerTools/distroless/pull/368

**Comment by Renz2018** [comment]
How about add java:8-nonroot and java:11:nonroot???

**Comment by evanj** [comment]
The switch to debian10 would actually be an opportunity to introduce this change, since it is going to break compatibility anyway?

**Comment by yegle** [comment]
Please re-consider or at least document if you want to make nonroot the default.

To have a binary listen to a privileged port, you have to `RUN setcap "cap_net_bind_service=+ep" $YOUR_BINARY`. Due to https://github.com/moby/moby/issues/35699, `COPY` a file with capability from an image during multi-stage build won't work. The only workaround is to bundle `setcap` binary in your final image and run it in the build step.

See also rant: https://mobile.twitter.com/miekg/status/1095035943294259202

**Comment by chanseokoh** [comment]
@yegle it is an interesting Docker bug, but you can always put `USER 0:0` if you really have to. Also most runtimes allow overriding the default user set in the container. What is the real issue in your use case?

**Comment by yegle** [comment]
You'll have to bundle additional binary (`setcap` and it's shared objects) if:
- you use `:nonroot`
- your binary needs additional capability (e.g. listening to port <1024)

Which kind of defeated the purpose of using distroless (additional binary not used at runtime = added security risk etc.)

See https://github.com/yegle/stubby-docker/commit/e0baae16d3a8cee50c49a98b18f2b2cae772e932 for more context. The binary in the commit is a DNS server and have to listen to port 53. This commit doesn't actually work.

**Comment by chanseokoh** [comment]
Sorry, I still don't get it.

```
FROM gcr.io/distroless/base # default user is root
```

will basically be equivalent to

```Dockerfile
FROM gcr.io/distroless/base:nonroot
USER 0:0
```

How not using `:nonroot` alone solves the problem that you have to copy `setcap`? As you said, due to the bug, even if you use an image where the default user is root, the capabilities are not carried over. For example,

```Dockerfile
FROM debian:buster AS build_env
RUN setcap 'cap_net_bind_service=+ep' /bin/ls && getcap /bin/ls

FROM debian:buster
COPY --from=build_env /bin/ls /my-ls
```

```
$ docker build -t test .
Step 2/4 : RUN setcap 'cap_net_bind_service=+ep' /bin/ls && getcap /bin/ls
...
/bin/ls = cap_net_bind_service+ep

$ docker run --rm test getcap /my-ls
<no output>
```

I'm confused. Maybe I'm missing something? And the only difference between `:nonroot` and `:latest` is the default user set in the container image, which you can set whatever you want in `Dockerfile`, so I don't see any connection from `:nonroot` to the capability issue.

**Comment by yegle** [comment]
I was saying for people who do want to utilize `:nonroot` image and run the process as non-root user, they have to bundle a `setcap` binary with their image.

In my example of running a DNS server in docker and provide the DNS service to other containers in the same Docker network, I have to use port 53. My option would be:
1. Use `base-debian10:latest`, but it's not there (See https://github.com/GoogleContainerTools/distroless/issues/436)
2. Use `base-debian10:nonroot` with `USER 0:0`, then again what's the point of using nonroot if you choose to run the process as root anyway?
3. Use `base-debian10:debug`, which is essentially option 1 but with additional shell
4. Use `base-debian10:nonroot`, bundle a `setcap` binary, and set the capability when building the final image.

Does this makes sense now...?

**Comment by chanseokoh** [comment]
> Use `base-debian10:nonroot` with `USER 0:0`, then again what's the point of using nonroot if you have to run the process as root anyway?

The discussion here is about making `:latest` point to `:nonroot` (and probably `:nonroot` will be gone afterwards). This non-root image (already) subsumes the conceptual "root image"; they are just identical except the some metadata about the image indicating runtimes should run the image with some particular user if not overridden. There's nothing you will lose when Distroless makes this switch. You'll have to use `USER 0:0` for `:latest` (not for `:nonroot`) anyways after that.

After all, considering everything, I genuinely think this can't be an argument against not making `:latest` point to `:nonroot`. For people who really need to run the image as root, they can do it easily with `USER 0:0`. And this is pretty much intended.

**Comment by yegle** [comment]
Wait...What...

No I don't want to run my binary as root. I just want to use `:nonroot`, but want to be able to `setcap`. Yes this would be the same regardless which image I use, but the distroless image doesn't have package manager, does that mean I need to copy `setcap` and its shared objects from a burster image?

I'm totally fine with `:latest` being `:nonroot`. It would be more useful if you also have an image `:nonroot-with-setcap`, to make some people's life easier.

**Comment by chanseokoh** [comment]
> I'm totally fine with `:latest` being `:nonroot`.

Cool! Looks like I can take this as a definite answer that you actually do not have any objection on this issue. I initially thought you were opposing, as you had asked for "reconsideration" on this matter. Switching the default won't affect your situation, after all.

> It would be more useful if you also have an image `:nonroot-with-setcap`, to make some people's life easier.

Definitely, this is something conceivable, but to be completely honest, I think this isn't really the right direction for Distroless (or any other similar base images) to take and maintain it, for a number of reasons. But primarily, this `setcap` issue (https://github.com/moby/moby/issues/35699) should really be fixed at the root. Actually, looking at the bug, they seem to agree that this should be resolved at the Docker level in today's environment, and indeed, they are actively working on this ([draft PR here](https://github.com/moby/moby/pull/40087)) to resolve the issue.

> I need to copy `setcap` and its shared objects from a burster image?

That is one way to do it. Another option I can think of is rebasing (https://github.com/google/image-rebase or https://github.com/codahale/docker-rebase), and this may be an easier approach to some people. [Another workaround](https://github.com/moby/moby/issues/35699#issuecomment-458532099) I found is to import a tarball, and perhaps this may also prove easier. I believe many people have hit this issue, so there may be more workarounds, I don't know.

**Comment by chanseokoh** [comment]
Oops, I totally forgot crane for rebasing: https://github.com/google/go-containerregistry/blob/master/cmd/crane/rebase.md

**Comment by JonathanParra** [comment]
Inquiry: Is it possible to, in an image or Dockerfile using Distroless, besides the ':nonroot' tag, also define a 'USER nonroot'? This is because, when scanning images with Trivy, it does not detect root, and as a consequence, it generates a HIGH vulnerability.

**Comment by loosebazooka** [comment]
I'm not sure I understand the problem? Can you elaborate? The users are in all images. The tag is just setting the default user.

**Comment by rudfoss-rr** [comment]
Sorry for reopening an old thread, but I've run into what I believe is the same issue as @JonathanParra. Our Trivy scan reports:

```shell
Dockerfile (dockerfile)

Tests: 20 (SUCCESSES: 19, FAILURES: 1)
Failures: 1 (HIGH: 1, CRITICAL: 0)

AVD-DS-0002 (HIGH): Specify at least 1 USER command in Dockerfile with non-root user as argument
```

For this container:

```Dockerfile
FROM gcr.io/distroless/nodejs24-debian12:nonroot

WORKDIR /app
COPY --from=build /app .

CMD ["app.js"]
```

It seems Trivy does not detect this as a non-root container. Or am I maybe missing something?
