### ISSUE TITLE
TensorFlow on Distroless

### ISSUE THREAD

**Issue by GaniMarquez** [GoogleContainerTools/distroless#379]
I'm getting this error whenever I try to run my golang application that runs a TF model under the hood.
```
error while loading shared libraries: libtensorflow.so: cannot open shared object file: No such file or directory
```

Can someone kindly explain to me why this happens even if I copy `libtensorflow.so` to the container using distroless with the correct path as what I have in my non-distroless containers?

**Comment by chanseokoh** [comment]
I have no idea, but have you tried the `LD_LIBRARY_PATH` environment variable?
