### ISSUE TITLE
CUDA-10.1 distroless image

### ISSUE THREAD

**Issue by edowson** [GoogleContainerTools/distroless#381]
I'd like to create a CUDA-10.1 distroless image, based on the `gcr.io/distroless/python3` base image, so that I can run `tensorflow-gpu-v2.0.0-beta1`. 

(I've already created and tested `tensorflow-cpu` distroless image and that works fine.)

The problem I'm running into is that the `gcr.io/distroless/python3` base image doesn't have an `apt-get` package manager to download and install the CUDA libraries. 

`apt` also has a bunch of dependencies like: `adduser, gpgv | gpgv2 | gpgv1, libapt-pkg5.90 (>= 1.9.1), ubuntu-keyring, libc6 (>= 2.15), libgcc1 (>= 1:3.0), libgnutls30 (>= 3.6.6), libseccomp2 (>= 1.0.1), libstdc++6 (>= 5.2)`

What would the recommended approach be to get the CUDA libraries into the `gcr.io/distroless/python3` distroless image? It is quite tedious to manually copy library files, since there are so many dependencies.

**Comment by chanseokoh** [comment]
I don't know if this will help, but I too was one of those curious of what it would take to have `dpkg` and `apt` into Distroless. The other day, I tried it purely for experimental purposes:

https://github.com/chanseokoh/distroless-with-package-manager

Although it was painful, but I managed to do it. But then, I realized once you have a package manager installed, it is not so much different from other distros like `ubuntu`, so at that point, I find no good reason to stick to Distroless.

Alternatively, I have seen people using multi-stage Docker build to copy, for example, shared libraries (or any other necessary files) from `debian:stretch` (from which Distroless pulls packages as of now).

https://github.com/GoogleContainerTools/distroless/issues/325#issuecomment-475255266

This works if you know what library files you need (can be determined from the changes brought by `apt-get install` for example).

Hope this helps.

**Comment by donmccasland** [comment]
seems like we've got an answer to this question.  specifically it is antithetical to distroless to add a package manager.  You have two options:
- multistage builds
- forking and adding packages with bazel

**Comment by Talador12** [comment]
I think this is worth reopening. GPU images are becoming more important and there has to be some way to build a distroless image, or at least as minimal as possible to support CUDA and ROCm
