### ISSUE TITLE
Updating to Debian 10 (buster)

### ISSUE THREAD

**Issue by evanj** [GoogleContainerTools/distroless#385]
Before I attempt to spend some time to implement this: Can a maintainer provide some guidance about what the "ideal" way to manage this should be? In particular: do we want to maintain both debian9 and debian10 based images? Do we want to switch the default? My proposal:

* Produce sets of images tagged with both `debian9` and `debian10` respectively. E.g. something like `gcr.io/distroless/base:debian9` and `gcr.io/distroless/base:debian10`.
* Leave the default as debian9, at least for now.

Any thoughts? This will also at least partially address #364 and possibly a few others.

**Comment by chanseokoh** [comment]
@donmccasland @sharifelgamal Debian 10 "buster" released in July

**Comment by chanseokoh** [comment]
Oh, wait. I heard Buster doesn't have `openjdk-8` anymore.

**Comment by evanj** [comment]
Looks like it is only [`openjdk-11`](https://packages.debian.org/buster/openjdk-11-jre)? Is that problematic? With the current Java image naming convention, this could just add `gcr.io/distroless/java:11-debian10`?

**Comment by loosebazooka** [comment]
I believe the distroless philosophy is to stay on a single latest version, so naming is something that'll probably have to be worked on a little.

**Comment by evanj** [comment]
I have an example of the sort of thing I am thinking about in https://github.com/GoogleContainerTools/distroless/pull/391. Feedback welcomed!

**Comment by donmccasland** [comment]
Hey folks,

I'm glad we've got some interest going on this.  I'd suggest we get a bug
going to track our progress and final decisions about it.

Because we don't have a solid deprecation plan and process for these
images, I'd like us to plan on producing both a Debian 9 and Debian 10 for
a period of time while clearly indicating somewhere that Debian 9 will
eventually be gone.

**Comment by chanseokoh** [comment]
I guess we will not have distroless/java:8 for Debian 10, unless we get Java 8 from elsewhere.

**Comment by evanj** [comment]
My experimental PR #391 was merged, so this is partially fixed. We now need to get them published. I've opened #398 which I think will cause the `//base` images to be published. If this approach is acceptable, I'll go ahead and do the same thing for the Python and Java images, and we can work on the other ones in a similar way. I don't use the other images, so I may need help with those.

**Comment by evanj** [comment]
I've done a bit more work on this. This time, I pushed the experimental images to my own GCR project. Please don't use these in production, since I'm likely to delete this project eventually. If you do want to use one, you can copy it into your own registry. However, at the moment if it helps, I've published the following images.

The only blocker for adding -debian10 images for everything else this point is time and testing :) I don't use the other images, but I'm happy to add them when I find some more time to fiddle with this, or after these few changes get merged.

gcr.io/distroless-dev/base-debian10
gcr.io/distroless-dev/cc-debian10
gcr.io/distroless-dev/python3-debian10
gcr.io/distroless-dev/python2.7-debian10

**Comment by donmccasland** [comment]
We're delivering these images now.

**Comment by stuartgunter** [comment]
It's great to see the `-debian10` images being published! I see this is confined to a subset of the distroless images though.

Are there plans to update the `distroless/java` images to debian10 as well?

**Comment by evanj** [comment]
See #413 !
