### ISSUE TITLE
Security update for distroless java

### ISSUE THREAD

**Issue by barmic** [GoogleContainerTools/distroless#387]
Hello,

If I understand you follow Debian packaging. Debian have publish [security upgrade](https://www.debian.org/security/2019/dsa-4486) 3 days ago (more infos in [openjdk update](https://openjdk.java.net/groups/vulnerability/advisories/2019-07-16)).

If I see [GCR](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java?gcrImageListsize=15) it seems to distroless don't apply the update.

Do you have any plan for apply this update ? Or did you have documentation how can I create a PR for it ?

**Comment by chanseokoh** [comment]
Ah, thanks for letting us know. I think I can pull the security update to both `gcr.io/distroless/java:8` and `gcr.io/distroless/java:11`. I'll check that.

FTR:

https://www.debian.org/security/2019/dsa-4485

> For the oldstable distribution (stretch), these problems have been fixed in version 8u222-b10-1~deb9u1.

https://www.debian.org/security/2019/dsa-4486

> For the stable distribution (buster), these problems have been fixed in version 11.0.4+11-1~deb10u1.

**Comment by chanseokoh** [comment]
Unfortunately, I can only upgrade Java 8 from 8u212 to 8u222. Looks like the backported openjdk-11 did not make into any channel for stretch. (Correct me if you can find the 11.0.4 package for stretch.)

**Comment by barmic** [comment]
openjdk-11 is present in version 11.0.4 in [stretch-backports](https://packages.debian.org/stretch-backports/openjdk-11-jdk). Can you get it from this channel ?

**Comment by chanseokoh** [comment]
Huh, I will check the backports channel again. Thanks for looking into it.

**Comment by chanseokoh** [comment]
Oh, 11.0.4 wasn't in the Jul-23 snapshot, but it's in Jul-25. We can upgrade Java 11 too.

**Comment by chanseokoh** [comment]
The updated images will become live within a few hours at most.
