### ISSUE TITLE
Better NodeJS usage example

### ISSUE THREAD

**Issue by luistrigueiros** [GoogleContainerTools/distroless#401]
I would like to see a better NodeJS with a package.json that builds for example a simple Express app.

Thank you, kindly
   Luis Oscar Trigueiros

**Comment by blhagadorn** [comment]
Hey @luistrigueiros I made a PR to address your issue, does this help more with your understanding?
https://github.com/GoogleContainerTools/distroless/pull/408

**Comment by luistrigueiros** [comment]
Thank you this is very cool
