### ISSUE TITLE
distroless-nodejs for Production

### ISSUE THREAD

**Issue by prabaharang** [GoogleContainerTools/distroless#418]
As per the [documentation ](https://github.com/GoogleContainerTools/distroless)on distroless, the `distroless-nodejs` is in the experimental stage and it's not recommended for production usage. Is there any specific reason/concern the `nodejs` image is not ready for production?

**Comment by jugatsu** [comment]
The same question goes for Python images as well )

**Comment by bsuv** [comment]
@chanseokoh @dlorenc any updates on the above question?

**Comment by zurfluh** [comment]
I too am interested in additional information on the "experimental" status.--whether this classification still applies and what is missing for production readiness.

**Comment by edvasqueza** [comment]
5 months and still no updates, I guess we can't use them in production

**Comment by sleepycat** [comment]
So this is what you get using Google's own vulnerabilty scanner when you build an image based on the latest from `gcr.io/distroless/nodejs`. Note the dates on the vulns. I hope that helps people's decision making process.
![Screenshot from 2020-04-01 17-11-45](https://user-images.githubusercontent.com/109692/78191753-a9960200-7444-11ea-8a8c-5f783548f4aa.png)

**Comment by AndreasKlein** [comment]
Hi everyone, I have loooked at the CVEs and most seemed to be connected to debian 9, so I rebuild the nodejs12 with debian10. Here is the result, which looks a lot better.

![image](https://user-images.githubusercontent.com/2118704/90595932-2d7f3980-e1ee-11ea-9415-6e0f29a7d7ad.png)

Is there any reason, why we should just build the nodejs images with both debian 9 and 10, just like most of the other images? 
I can probably provide a PR.

A general question for the contributors: What else would be needed to get the nodejs images from experimental to ready-for-production? (Maybe @chanseokoh)

**Comment by AndreasKlein** [comment]
Any updates on this @chanseokoh @dlorenc @donmccasland  ?

**Comment by chanseokoh** [comment]
At this stage, I think it's safe to move nodejs out of experimental. I can review a PR if anyone is interested in doing so. Hopefully a simple renaming.

And I can review a PR to add nodejs-debian10 too.

**Comment by AndreasKlein** [comment]
I'll try to jump on it later today

**Comment by AndreasKlein** [comment]
@chanseokoh  https://github.com/GoogleContainerTools/distroless/pull/573

**Comment by chanseokoh** [comment]
Fixed by #576. (Some minor doc changes by #578 and #579.)
