### ISSUE TITLE
Security JDK update for Java 11

### ISSUE THREAD

**Issue by barmic** [GoogleContainerTools/distroless#420]
Hello,

Debian publish a [security update of openjdk-11](https://www.debian.org/security/2019/dsa-4546).
Can you update image to Java 11.0.5?

Thank you very much for the work!

**Comment by chanseokoh** [comment]
Thanks for letting us know. Is this available in the stretch security backport channel?

**Comment by chanseokoh** [comment]
Looks like 11.0.5 did not make into the stretch-backports. Hope they will backport this to stretch, but I have no idea if they will do it soon or ever.

https://packages.debian.org/search?suite=stretch-backports&searchon=names&keywords=openjdk-11-jre-headless
https://packages.debian.org/search?suite=buster&searchon=names&keywords=openjdk-11-jre-headless

**Comment by barmic** [comment]
We can found this intersting page to view all informations about this package in debian:
https://tracker.debian.org/pkg/openjdk-11

We can that this package go from testing to stable in 2 days. The oldstable have less than one year, we can hope this will be updated. Maybe should wait 1 or 2 days to have the update.

Thank you for reactivity

**Comment by barmic** [comment]
The package seems to be accepted in stretch-backport. It will be available in repository soon.

cf: https://tracker.debian.org/pkg/openjdk-11

**Comment by chanseokoh** [comment]
Doesn't seem like it will make into stretch-backport today. I'll check it next week.

**Comment by barmic** [comment]
It's deployed! :tada: https://packages.debian.org/search?suite=stretch-backports&searchon=names&keywords=openjdk-11-jre-headless

**Comment by chanseokoh** [comment]
Thanks for monitoring this. #424 also upgraded Java 8 from 8u222 to 8u232. I believe merging a PR will automatically publish new images and they will become live soon.
