### ISSUE TITLE
Upgrade Jetty to more recent version

### ISSUE THREAD

**Issue by fhoeben** [GoogleContainerTools/distroless#422]
The Jetty version in the Jetty base image is quite old.
Can it be upgraded to 9.4.22.v20191022?

https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.22.v20191022/jetty-distribution-9.4.22.v20191022.tar.gz

**Comment by chanseokoh** [comment]
Fixed by #424. I believe merging a PR will automatically publish new images and they will become live soon.

**Comment by mwyrembl** [comment]
Is it possible to do that again and update the distroless Jetty image to version 9.4.38?
