### ISSUE TITLE
Impossible to add files in /etc

### ISSUE THREAD

**Issue by maxday** [GoogleContainerTools/distroless#438]
Hello,

It seems that I can't add files to /etc 
(I want to add certificates in /etc/ssl/certs)

Here is the observed behaviour with the dive tools : we can see that all files are under "a dot-prefix root" and if I want to copy to /etc/ssl/certs, docker creates a new folder.

To reproduce :

```
FROM gcr.io/distroless/nodejs
COPY sample.txt /etc/ssl/certs
```

Here is the dive inspection result
<img width="1611" alt="Screen Shot 2019-11-28 at 5 08 34 PM" src="https://user-images.githubusercontent.com/864493/69833431-d4a3e700-1201-11ea-8fc0-9dc942ef4f1f.png">

**Comment by chanseokoh** [comment]
From my quick test, files do get added. Perhaps `dive` is buggy in displaying image contents.

```Dockerfile
FROM gcr.io/distroless/nodejs:debug
COPY sample.txt /etc/ssl/certs
ENTRYPOINT ["/busybox/cat", "/etc/ssl/certs/sample.txt"]
```

```
$ cat <<EOF > sample.txt
> I am sample.txt.
> EOF
$ docker build -t test .
...
Successfully built 0916e44a7a9a
Successfully tagged test:latest
$ docker run --rm test
I am sample.txt.
```

**Comment by jonjohnsonjr** [comment]
I believe tar will normalizes file paths (see the `--absolute-names` flag). I'm guessing docker handles this fine (`./etc` vs `etc`) but dive doesn't?
