### ISSUE TITLE
Is it possible to maintain a distroless base image for a custom jre build with jlink?

### ISSUE THREAD

**Issue by pragmasoft-ua** [GoogleContainerTools/distroless#439]
Custom jre built with jlink provides substantial image size reduction

In [Our custom base image](https://github.com/pragmasoft-ua/spring-boot-base-docker-image) we're trying to use distroless base as a base image for jlink, but it seems is missing important libraries, which are java specific, like fontconfig, as e.g. was reported here #321

Can't we make a distroless java dependency hierarchy two level instead of one level, ie instead of

base -> java

make it

base -> java-base -> java

where java-base includes required native libs but does not include jre itself?

**Comment by chanseokoh** [comment]
This is an interesting idea and worth considering.

Just FTR, documenting how I can build a "java-base" ("base" with necessary libraries for JRE but that does not include the JRE) useful for `jlink`:

1. Fork the repo: `git clone https://github.com/GoogleContainerTools/distroless.git`
2. Install `bazel` ([Linux instructions](https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu)). For example,
   ```
   $ wget https://github.com/bazelbuild/bazel/releases/download/1.2.1/bazel-1.2.1-installer-linux-x86_64.sh
   $ chmod +x bazel-1.2.1-installer-linux-x86_64.sh
   $ ./bazel-1.2.1-installer-linux-x86_64.sh --user
   ```
3. Modify `java/BUILD` to exclude the JRE Debian package.
   ```diff
   diff --git a/java/BUILD b/java/BUILD
   index 42bd8c3..b57aefa 100644
   --- a/java/BUILD
   +++ b/java/BUILD
   @@ -37,7 +37,7 @@ cacerts_java(
            DISTRO_PACKAGES[distro_suffix]["fontconfig-config"],
            DISTRO_PACKAGES[distro_suffix]["libexpat1"],
            DISTRO_PACKAGES[distro_suffix]["libfontconfig1"],
   -        DISTRO_PACKAGES[distro_suffix][jre_deb],
   +        #DISTRO_PACKAGES[distro_suffix][jre_deb],
        ],
        # We expect users to use:
        # cmd = ["/path/to/deploy.jar", "--option1", ...]
   ```
4. Build Java images:
   ```
   # Builds and pushes bazel/java:java8_debian9 to local Docker.
   $ bazel run //java:java8
   $ bazel run //java:java11           # bazel/java:java11_debian9
   $ bazel run //java:java11_debian10  # bazel/java:java11_debian10
   ```

**Comment by chanseokoh** [comment]
Contributions are welcome.
