### ISSUE TITLE
Remove unnecessary files from jetty image

### ISSUE THREAD

**Issue by verglor** [GoogleContainerTools/distroless#444]
I have realised that there is useless 13MB [`demo-base`](https://www.eclipse.org/jetty/documentation/9.4.x/startup-base-and-home.html#demo-base) directory in `/jetty` directory of [gcr.io/distroless/java/jetty](gcr.io/distroless/java/jetty) image.

Since it is desirable to have images as small as possible I suggest that this directory should be removed and probably it should be investigated if there is any other unnecessary stuff that can be removed.

Official [jetty](https://hub.docker.com/_/jetty) alpine image does not contain `demo-base` directory and is 36% smaller.

**Comment by chanseokoh** [comment]
Makes sense. #445 will remove this. I think this is obvious, but could you confirm that `demo-base` is completely useless?

Once #445 is merged, the images will be published automatically in a short time frame.

**Comment by chanseokoh** [comment]
> Once #445 is merged, the images will be published automatically in a short time frame.

This used to work, but it has been reported this is no longer the case (#452).
