### ISSUE TITLE
java debug image size increasing

### ISSUE THREAD

**Issue by floriankoch** [GoogleContainerTools/distroless#447]
with https://github.com/GoogleContainerTools/distroless/pull/446 , the full openjdk is included in the debug image to get the debug binarys.

This increases the size from 196 to 423 MB!

Is it neccesary include the full jdk with alls sources, modules etc. ?
maybe its better to only include the binarys itself (only a few (~5) MB)? 

What do you think?

I tested this manuelly and it does work

**Comment by chanseokoh** [comment]
> I tested this manuelly and it does work

How did you test this? Was there a slimmed-down `.deb` package without sources and modules? Or, did you just extract some binaries manually?

**Comment by floriankoch** [comment]
I used a multi-stage docker build, and copied the files over

**Comment by chanseokoh** [comment]
It's easy to specify [file exclusion rules](https://github.com/GoogleContainerTools/distroless/issues/508) from a `.deb` (`openjdk-XX-jdk-headless` in this case), so I think at least we could easily drop some obvious files (src or doc).

**Comment by floriankoch** [comment]
you are correct , i prepare a PR

**Comment by chanseokoh** [comment]
But I think you will be blocked by #509.

**Comment by chanseokoh** [comment]
@floriankoch #509 fixed

**Comment by chanseokoh** [comment]
> It's easy to specify [file exclusion rules](https://github.com/GoogleContainerTools/distroless/issues/508) from a `.deb` (`openjdk-XX-jdk-headless` in this case)

Sorry, I was wrong about this. The example in the link was when using the `pkg_tar` rule. The [`container_image`](https://github.com/bazelbuild/rules_docker#container_image-1) rule doesn't have a feature to exclude files added through the `deb` attribute.

**Comment by chanseokoh** [comment]
See #551 and #552 for an implementation idea.
