### ISSUE TITLE
gcr.io/distroless/java-debian10 not avaliable

### ISSUE THREAD

**Issue by hhofchina** [GoogleContainerTools/distroless#448]
Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.8.0:build (default) on project td-provider: Tried to pull image manifest for gcr.io/distroless/java-debian10:latest but failed because: Failed to fetch "latest" from request "/v2/distroless/java-debian10/manifests/latest". | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new: 404 Not Found

**Comment by chanseokoh** [comment]
#435 is an attempt to publish this. However, note that #435 adds only Java 11 on Debian 10.

**Comment by chanseokoh** [comment]
#435 is merged. The Java-11-on-Debian-10 images will automatically go live soon.

**Comment by chanseokoh** [comment]
We added Java 11 on Debian 10 a while ago with #435. Debian buster (which Distroless depends on) has dropped Java 8, so Distroless isn't going to have Java 8 on 10 either. Closing.
