### ISSUE TITLE
Python2.7 and 3 Production Readiness

### ISSUE THREAD

**Issue by rnikoopour** [GoogleContainerTools/distroless#455]
Hi all,

Is there a timeframe for promoting the Python base containers from `experimental` to `production ready`?

**Comment by adriantorrie** [comment]
Also, what are the acceptance criteria to move from experimental to production.

The info would help guide any willing contributors...

**Comment by chanseokoh** [comment]
Given the experimental period, I think it's OK to get out of `/experimental`. (Probably Python 3 only, as Python is dead.) NodeJs recently did the same: https://github.com/GoogleContainerTools/distroless/issues/418#issuecomment-682005927
