### ISSUE TITLE
Build reproducibility: images depend on where they are built

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/distroless#458]
UID and GID of some directories are build environment-dependent. See https://github.com/GoogleContainerTools/distroless/issues/456#issuecomment-577864699 and https://github.com/GoogleContainerTools/distroless/issues/456#issuecomment-577859858.

Is it possible that the build runs a tar zip-up on the environment where Bazel runs, and it doesn't clear the UID and GID information?

**Comment by chanseokoh** [comment]
> See [#456 (comment)](https://github.com/GoogleContainerTools/distroless/issues/456#issuecomment-577864699) and [#456 (comment)](https://github.com/GoogleContainerTools/distroless/issues/456#issuecomment-577859858).

So I think these are from `cacerts/extrach.sh`, and looking at https://github.com/GoogleContainerTools/distroless/pull/551#discussion_r457647403, maybe it's an easy fix to just add `--owner=0 --group=0` when tarring up?

**Comment by petermylemans** [comment]
The rabbit hole goes even deeper: 
Python 2 default for TAR format: GNU
Python 3.8 default for TAR format: PAX

==> we should probably fix those at the archive generation level tar.open(format=tarfile.GNU_FORMAT)

That is why building distroless with PY2 or PY3 results in different digests ;) 

Anyway, let's first fix the owner issues first.
