### ISSUE TITLE
Node.js images should not include 'npm'

### ISSUE THREAD

**Issue by ashutosh49** [GoogleContainerTools/distroless#461]
Since gcr.io/distroless/nodejs invokes `node` directly, and there have been vulnerabilities reported for packages used by the `npm` cli, it would probably be better to not include the `npm` cli in gcr.io/distroless/nodejs.

For instance, https://www.npmjs.com/advisories/1184 was reported for `https-proxy-agent` (used by NPM before 6.13.1 (the fixed version seems to be included after Node.js 10.18.0)

Also this would reduce the size of the image since the size of `node_modules` in `npm` is about 25MB.

**Comment by HofmannZ** [comment]
I like this, anyone working on it? 🚀

**Comment by hamza1311** [comment]
How would one invoke a `npm script` from these containers then? Think of running `npm run start` in next.js application.

**Comment by yanniks** [comment]
@hamza1311 you wouldn't. Im not an expert in next.js, but `npm start` usually triggers another command as defined in `package.json`. Instead of calling `npm start`, you would then call that other command directly.

**Comment by jbergstroem** [comment]
I would really like to see this as well. Guessing it would have to be under a different tag to avoid breaking current usage?

> How would one invoke a `npm script` from these containers then? Think of running `npm run start` in next.js application.

You shouldn't. Just do `node dist/index.js` instead. Faster, less dependencies.
