### ISSUE TITLE
Examples not usable with Bazel as container base target isn't usable in other WORKSPACE

### ISSUE THREAD

**Issue by gertvdijk** [GoogleContainerTools/distroless#465]
IIUC, the `examples/` folder shows how to use the distroless images in two ways: with Dockerfile and with Bazel.

I'm interested in the latter use case, as my project is using Bazel too. The examples are not usable, because they will only work in distroless's own WORKSPACE. For example, Java:

https://github.com/GoogleContainerTools/distroless/blob/76c76a13d6bed32db25b88c2f2ff2ea52df52c82/examples/java/BUILD#L5-L10

The base image dependency `//java:java11`, (referencing the distroless repo itself) is really cool I think, because it will not rely on the GCR image repository, but builds the container from source! Howerver, this won't work in another project as `@distroless//java:java11`, because it's missing the references to the dependencies in the WORKSPACE.

As a solution, _either_:

- Make the examples an actual MWE by having each of them a separate WORKSPACE. This requires in the distroless main repo a separate `.bzl` file for loading these into the Bazel workspaces:
  - [`@debian_stretch`](https://github.com/GoogleContainerTools/distroless/blob/76c76a13d6bed32db25b88c2f2ff2ea52df52c82/WORKSPACE#L27)
  - [`@debian_stretch_backports`](https://github.com/GoogleContainerTools/distroless/blob/76c76a13d6bed32db25b88c2f2ff2ea52df52c82/WORKSPACE#L36)
  - [`@debian_stretch_security`](https://github.com/GoogleContainerTools/distroless/blob/76c76a13d6bed32db25b88c2f2ff2ea52df52c82/WORKSPACE#L45)
  - [`@package_bundle`](https://github.com/GoogleContainerTools/distroless/blob/76c76a13d6bed32db25b88c2f2ff2ea52df52c82/WORKSPACE#L52)
  - ... and all the other required for use.
- Simply depend on the published image @ GCR via `container_pull()` instead of the Bazel target.

I'm more than happy to work on a PR if you think this is useful and something that maintainers are willing to maintain.

**Comment by chanseokoh** [comment]
Unfortunately, I'd say this is out of scope of this repo at this point, for a similar reason as in https://github.com/GoogleContainerTools/distroless/issues/463#issuecomment-587566386. We don't have enough resources to maintain this kind of work for Bazel use cases.

And don't assume that code related to Debian packages will stay forever in this repo. We've explored the possibility of ditching Debian and getting binaries/packages from another distro, and once that happens, we will just gut out such code. Not that we will switch anytime soon.

We really welcome external contributions, as this repo is now primarily driven by the community. However, I think this request/contribution is out of scope. I'll close this issue, and I'm sure you understand.

**Comment by gertvdijk** [comment]
> We don't have enough resources to maintain this kind of work for Bazel use cases.

Even examples how to use the distroless (published) images as base? (point 2 in my initial post)

If so, then I'd vote to delete the Bazel stuff in the examples OR mark all of them explicitly that it's used for internal/testing purposes with comments. Because as-is now, it looks like this is/should be maintained. WDYT?

**Comment by chanseokoh** [comment]
> Even examples how to use the distroless (published) images as base? (point 2 in my initial post)

Sorry, I was only talking about the work to make these Bazel rules under examples work in a completely unrelated Bazel workspace and keep supporting it for public consumption.

> If so, then I'd vote to delete the Bazel stuff in the examples OR mark all of them explicitly that it's used for internal/testing purposes with comments. 

Good idea. Filed #468.
