### ISSUE TITLE
wrong sha for artifact

### ISSUE THREAD

**Issue by cristifalcas** [GoogleContainerTools/distroless#471]
The file from [here](https://github.com/GoogleContainerTools/distroless/blob/e95325f428f6c0892f128348ae6d62a47ac7135c/package_manager/package_manager.bzl) has now a different sha256: 02aa2a062de01ce216fa795f470fe6bf2c90a7898c89df2941ab160c65119fc4

This is breaking bazel now.

**Comment by chanseokoh** [comment]
#469 fixes it (temporarily). Sync with master, and it will build (for now).

But I'll file up another PR soon, so I recommend you sync with master tomorrow again to conclusively settle this down. Sorry for the trouble.
