### ISSUE TITLE
published dpkg_parser no longer has the expected sha

### ISSUE THREAD

**Issue by kevingessner** [GoogleContainerTools/distroless#472]
The version of `dpkg_parser.par` for `package_manager` appears to have changed unexpectedly upstream.  

The sha in today's master:

https://github.com/GoogleContainerTools/distroless/blob/e95325f428f6c0892f128348ae6d62a47ac7135c/package_manager/package_manager.bzl#L12

No longer matches the file:

```
 > curl https://storage.googleapis.com/distroless/package_manager_tools/0e7095cc1ac3e084a1d76f86c36f8ec38483eb24/dpkg_parser.par | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 86894  100 86894    0     0   466k      0 --:--:-- --:--:-- --:--:--  471k
02aa2a062de01ce216fa795f470fe6bf2c90a7898c89df2941ab160c65119fc4  -
```

This is causing all our non-clean builds to fail.  Was this published artifact updated to a new version on purpose or accidentally?  It should be rolled back and the new version published in a new path.

**Comment by chanseokoh** [comment]
Closing as dup of #471.
