### ISSUE TITLE
dpkg_parser.par returning 403's

### ISSUE THREAD

**Issue by robbertvanginkel** [GoogleContainerTools/distroless#474]
While using 4745c1aa5ad24c379218890c0185088a618a21a8, the download for `dpkg_parser.par` is returning 403's:

```
13:30:59 WARNING: Download from https://storage.googleapis.com/distroless/package_manager_tools/548be30ea343ebf1e3729e1334b8adca8957e0c1/dpkg_parser.par failed: class java.io.IOException GET returned 403 Forbidden
```

```
$ wget https://storage.googleapis.com/distroless/package_manager_tools/548be30ea343ebf1e3729e1334b8adca8957e0c1/dpkg_parser.par
--2020-02-19 14:06:43--  https://storage.googleapis.com/distroless/package_manager_tools/548be30ea343ebf1e3729e1334b8adca8957e0c1/dpkg_parser.par
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.6.80, 2607:f8b0:4005:80a::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.6.80|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-02-19 14:06:43 ERROR 403: Forbidden.
```

https://github.com/GoogleContainerTools/distroless/blob/4745c1aa5ad24c379218890c0185088a618a21a8/package_manager/package_manager.bzl#L5-L10

Have these permissions intentionally changed, breaking people using older versions of distroless?

**Comment by chanseokoh** [comment]
Sorry for the trouble. I accidentally messed up with the bucket, so these binaries are gone. Sync with master and it should build successfully. If you must build from old source, use any of the existing binaries, e.g., https://storage.cloud.google.com/distroless/package_manager_tools/1b8448ea6f55db64ea3c1956d4dd1b9c47166a8c/dpkg_parser.par

**Comment by robbertvanginkel** [comment]
We have copies of the binaries from an internal cache. Would you be willing to re-upload those to the same bucket given that the sha's match to verify integrity?

**Comment by chanseokoh** [comment]
Sure, if you can correctly map URLs to binaries, I can do that.

**Comment by chanseokoh** [comment]
(... and if the number of binaries is small.)

**Comment by robbertvanginkel** [comment]
[dpkg_parser.par.tar.gz](https://github.com/GoogleContainerTools/distroless/files/4227879/dpkg_parser.par.tar.gz) for https://storage.googleapis.com/distroless/package_manager_tools/548be30ea343ebf1e3729e1334b8adca8957e0c1/dpkg_parser.par

**Comment by chanseokoh** [comment]
Done.

```
$ curl https://storage.googleapis.com/distroless/package_manager_tools/548be30ea343ebf1e3729e1334b8adca8957e0c1/dpkg_parser.par | sha256sum -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 78521  100 78521    0     0  1236k      0 --:--:-- --:--:-- --:--:-- 1236k
2ca62e67ce4d79a3f4072908559beef9f9c15e1a0f8dbc72a92c046f7c0c9df6  -
```

**Comment by robbertvanginkel** [comment]
Thank you!
