### ISSUE TITLE
Python 3 missing type support

### ISSUE THREAD

**Issue by mneil** [GoogleContainerTools/distroless#482]
The python 3 image raises a SyntaxError: invalid syntax when you are writing Python with type hints.

```
class PolicyManager():
    kind: str
    specs: List[types.Spec]
```

Raises
```
plugin_kind: str
               ^
SyntaxError: invalid syntax
```
Anyone know what is required to add type support to python?

**Comment by chanseokoh** [comment]
`gcr.io/distroless/python3-debian10` runs a newer version on Debian 10 buster, so try that.

```
$ docker run --rm gcr.io/distroless/python3 --version
Python 3.5.3
$ docker run --rm gcr.io/distroless/python3-debian10 --version
Python 3.7.3
```
