### ISSUE TITLE
Distroless image for nodejs doesn't specify debian version

### ISSUE THREAD

**Issue by krishnadurai** [GoogleContainerTools/distroless#485]
**Clarification Required**

The current image for nodejs does not mention the Debian version it is built on:
gcr.io/distroless/nodejs

There is no image named gcr.io/distroless/nodejs-debian10.

Languages golang, java and python have a `-debain10` based image.

Which version of Debian is the nodejs image using?

Can we have a `-debian10` based nodejs image?

**Comment by chanseokoh** [comment]
We need community contributions for this. Shouldn't be difficult. I can give pointers if anyone is willing to contribute.

**Comment by krishnadurai** [comment]
@chanseokoh Do we have a doc which we can refer to? I can give this a shot.

**Comment by chanseokoh** [comment]
@krishnadurai compare [nodejs BUILD](https://github.com/GoogleContainerTools/distroless/blob/70b8c7f2d41a844d310c23e0695388c916a364ed/experimental/nodejs/BUILD#L5-L13) and [python3 BUILD](https://github.com/GoogleContainerTools/distroless/blob/70b8c7f2d41a844d310c23e0695388c916a364ed/experimental/python3/BUILD#L39-L71). That is, you just need to have an additional `container_list` rule listing right deb packages for the `deb` attribute.

If some Debian 10 packages you need don't seem available, add them in [WORKSPACE](https://github.com/GoogleContainerTools/distroless/blob/70b8c7f2d41a844d310c23e0695388c916a364ed/WORKSPACE#L273-L376). (Note there is [another list for Debian 9](https://github.com/GoogleContainerTools/distroless/blob/master/WORKSPACE#L51-L160), which you probably don't need to change.)

Check `./test.sh` to get the idea for building and testing. And `bazel ... run //experimental/nodejs:nodej` will build and load an image to your local Docker daemon. You should use recent Bazel versions.

**Comment by chanseokoh** [comment]
Feel free to joint the Distroless Slack channel (inside [Kubernetes Slack]( https://slack.k8s.io/)) if you need help.

**Comment by krishnadurai** [comment]
@chanseokoh thanks for the guidance here. I'll try this once.

**Comment by AndreasKlein** [comment]
Hi @krishnadurai has there been any work done on this?

**Comment by chanseokoh** [comment]
Fixed by #573.

(FTR: release issues introduced by #573 were fixed by #574 and #575.)
