### ISSUE TITLE
package_manager dpkg_src rule assumes main, cannot specify contrib/nonfree

### ISSUE THREAD

**Issue by gilbahat** [GoogleContainerTools/distroless#486]
Hi,

there should be a variable/option to specify a package category class, e.g. main/contrib/nonfree as part of the dpkg_src rule, without having to resort to specifying a direct path to Packages.gz. this seems like a noted omission from the rule.

**Comment by chanseokoh** [comment]
Hi @gilbahat,

Please don't use `dpkg_src` in your project. It's an internal component, and we may remove the rule in the future. You shouldn't be using it. We won't implement this, sorry.

**Comment by aisbaa** [comment]
I quite like dpkg_src dpkg_list and would love to use it outside this project. Do you know if there is a project that fulfils aims to solve this?
