### ISSUE TITLE
Identifying distroless images based on OCI image

### ISSUE THREAD

**Issue by garethr** [GoogleContainerTools/distroless#487]
I'd like to be able to identify that an image is distroless (or based on distroless) by just looking at the image - likely either the filesystem or the OCI manifest data.

Looking through the Bazel build files I don't see anything that could be used for this purpose today?

I though this could be either:

* An image annotation
* A file dropped on disk (could be an extra line in `/etc/os-release`)

I'd be happy to send a pull request to do this I think, if this sounds useful.

**Comment by chanseokoh** [comment]
> * A file dropped on disk (could be an extra line in `/etc/os-release`)

We do supply some information in `/etc/os-release`, like `PRETTY_NAME="Distroless"`.

```
$ docker run --rm -it --entrypoint /busybox/cat gcr.io/distroless/java:debug /etc/os-release
PRETTY_NAME="Distroless"
NAME="Debian GNU/Linux"
ID="debian"
VERSION_ID="9"
VERSION="Debian GNU/Linux 9 (stretch)"
HOME_URL="https://github.com/GoogleContainerTools/distroless"
SUPPORT_URL="https://github.com/GoogleContainerTools/distroless/blob/master/README.md"
BUG_REPORT_URL="https://github.com/GoogleContainerTools/distroless/issues/new"
```

The code is [here](https://github.com/GoogleContainerTools/distroless/blob/70b8c7f2d41a844d310c23e0695388c916a364ed/package_manager/util.py#L39-L54). Is this enough?

**Comment by garethr** [comment]
Ah ha, I'd missed that. Thanks, much appreciated.
