### ISSUE TITLE
jksutil test fails on some machine

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/distroless#492]
A user on the Distroless Slack channel tried to build images on a VM (Ubuntu 18.04) and reported that the test running `cacerts/jksutil/test_jks.sh` (`bazel test //cacerts/jksutil:test_sh`) fails at [this assertion](https://github.com/GoogleContainerTools/distroless/blob/5a3fb2008b568007623d444a27dafe171f0dd005/cacerts/jksutil/test_jks.sh#L38-L39).

```
+ assert::file_contains .../distroless/_tmp/36fb293d2d5d07bbda5640420b36a61e/keytool_output 'Certificate fingerprint (SHA1): 36:79:CA:35:66:87:72:30:4D:30:A5:FB:87:3B:0F:A7:7B:B7:0D:54'
+ grep -qF 'Certificate fingerprint (SHA1): 36:79:CA:35:66:87:72:30:4D:30:A5:FB:87:3B:0F:A7:7B:B7:0D:54' .../distroless/_tmp/36fb293d2d5d07bbda5640420b36a61e/keytool_output
+ return 2
```

Obviously, the generated `keytool_output` file doesn't contain the expected string.
```
Keystore type: JKS
Keystore provider: SUN
Your keystore contains 5 entries
cn=amazonrootca1,o=amazon,c=us, Jan 1, 1970, trustedCertEntry,
Certificate fingerprint (SHA-256): 8E:CD:E6:88:4F:3D:87:B1:12:5B:A3:1A:C3:FC:B1:3D:70:16:DE:7F:57:CC:90:4F:E1:CB:97:C6:AE:98:19:6E
cn=digicertassuredidrootca,ou=www.digicert.com,o=digicertinc,c=us, Jan 1, 1970, trustedCertEntry,
Certificate fingerprint (SHA-256): 3E:90:99:B5:01:5E:8F:48:6C:00:BC:EA:9D:11:1E:E7:21:FA:BA:35:5A:89:BC:F1:DF:69:56:1E:3D:C6:32:5C
cn=globalsign,ou=globalsignrootca-r2,o=globalsign, Jan 1, 1970, trustedCertEntry,
Certificate fingerprint (SHA-256): CA:42:DD:41:74:5F:D0:B8:1E:B9:02:36:2C:F9:D8:BF:71:9D:A1:BD:1B:1E:FC:94:6F:5B:4C:99:F4:2C:1B:9E
cn=globalsign,ou=globalsignrootca-r3,o=globalsign, Jan 1, 1970, trustedCertEntry,
Certificate fingerprint (SHA-256): CB:B5:22:D7:B7:F1:27:AD:6A:01:13:86:5B:DF:1C:D4:10:2E:7D:07:59:AF:63:5A:7C:F4:72:0D:C9:63:C5:3B
cn=verisignuniversalrootcertificationauthority,ou=verisigntrustnetwork+ou=(c)2008verisign\,inc.-forauthorizeduseonly,o=verisign\,inc.,c=us, Jan 1, 1970, trustedCertEntry,
Certificate fingerprint (SHA-256): 23:99:56:11:27:A5:71:25:DE:8C:EF:EA:61:0D:DF:2F:A0:78:B5:C8:06:7F:4E:82:82:90:BF:B8:60:E8:4B:3C
```

@chrismcbride any idea off the top of your head?

**Comment by chrismcbride** [comment]
I was able to reproduce this on Macbook running zulu openjdk 12. The default keytool list [output](https://gist.github.com/chrismcbride/041f760d718f637e5af7b768af9e775f) shows SHA256 fingerprints. On my openjdk 8 linux machine it shows SHA1 fingerprints. I imagine at some point the default keytool output was changed.

So instead I changed the test to use [verbose output](https://gist.github.com/chrismcbride/a5ee795d0e693185b63f1d7c00866dd2) which contains both SHA1 and SHA256 fingerprints.
