### ISSUE TITLE
Update Node to latest 10.x version

### ISSUE THREAD

**Issue by bishtawi** [GoogleContainerTools/distroless#497]
The distroless NodeJS docker image `gcr.io/distroless/nodejs` is still on 10.16.3. It should be updated to the latest 10.x version. Currently that is [10.20.1](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.20.1).

Would also like to see a 12.x docker image, but looks like theres already a PR opened for that.

**Comment by x80486** [comment]
On a side note, is it possible to get the tagging right for the Node.js images? So far it's only `latest` / `debug`.

**Comment by chanseokoh** [comment]
Fixed by #556.
