### ISSUE TITLE
grpc binding for glic is missing in Nodejs

### ISSUE THREAD

**Issue by jtfogarty** [GoogleContainerTools/distroless#498]
The Kubeflow project is updating all of it's docker images to distroless but it appears that grpc binding for glic is missing in the nodejs distroless image.  

The PR for this is [#4881](https://github.com/kubeflow/kubeflow/pull/4881)

@krishnadurai

**Comment by chanseokoh** [comment]
What exactly is "grpc binding for glic"? Is "glic" a typo of glibc? What's the issue/error you are hitting without it? What Debian packages or shared library likes need to be added for this to work? Is there any relevant doc?

**Comment by chanseokoh** [comment]
Closing due to no updates from the user.
