### ISSUE TITLE
OpenSSL <1.1.1d security issue

### ISSUE THREAD

**Issue by yegle** [GoogleContainerTools/distroless#501]
I just saw https://www.openssl.org/news/secadv/20200421.txt, confirmed Debian 10 have fixed it in 1.1.1d-0+deb10u3 and went to rebuild every of my images that are based on distroless, only to find the dpkg snapshot was from Febrary.

https://github.com/GoogleContainerTools/distroless/blob/3289f7c3f7f6752b6c6d9e4e8cf2b45e22da02d2/WORKSPACE#L375-L380

Can we at least update the security repo's snapshot frequently?

**Comment by chanseokoh** [comment]
We solicit community contributions.

> confirmed Debian 10 have fixed it in 1.1.1d-0+deb10u3

However, the link says 1.1.1d is affected by the issue and users should upgrade to 1.1.1g. Where did you see Debian 10 have fixed this in 1.1.1d-0+deb10u3?

> OpenSSL version 1.1.1d, 1.1.1e, and 1.1.1f are affected by this issue.  ... Affected OpenSSL 1.1.1 users should upgrade to 1.1.1g

**Comment by floriankoch** [comment]
https://www.debian.org/security/2020/dsa-4661

**Comment by chanseokoh** [comment]
> I prepare a PR tomorrow morning

@floriankoch thank you very much!

**Comment by yegle** [comment]
Do we have a longer term solution instead of people sending one-off PRs to update it?

We'll need to update it each time any of the included packages are updated, preferably in hours not in days.

**Comment by chanseokoh** [comment]
I heard that there used to be some kind of monitoring system for security updates (or package updates, I don't know). I don't know how much automation the system provided, but I guess at least it notified some people and they should have been able to keep the images up-to-date probably at a reasonable pace, supposedly. Apparently, the system (whatever it was) is no longer working, and I also wonder what happened or why.

Anyways, what is clear is that now this repo is primarily driven and maintained by the community that depend on it. Theoretically someone in the community who cares about this repo could set up and run a monitoring system somewhere that automatically files a PR to update snapshots when new packages come out. But I suppose it is easier said than done, and honestly, it is hard to expect that anyone in the community will contribute their resources to set up such a system.

**Comment by floriankoch** [comment]
@chanseokoh  is there a log where the package versions are listed? How can i check if the openssl version is "correct"!?

**Comment by chanseokoh** [comment]
I think you'll just download the package metadata being used (https://snapshot.debian.org/archive/debian-security/20200421T135239Z/dists/buster/updates/main/binary-amd64/Packages.gz), unzip it, and check the version of `openssl`.

Another idea that came off on top of my head is to temporarily specify the package version in `dpkg_list()` and try rebuilding.

```diff
 dpkg_list(
     name = "package_bundle_debian10",
     packages = [
         "libc6",
         "base-files",
         "ca-certificates",
-        "openssl",
+        "openssl=1.1.1d-0+deb10u3",
```

**Comment by chanseokoh** [comment]
> Another idea that came off on top of my head is to temporarily specify the package version in `dpkg_list()` and try rebuilding.

But there's a caveat to this. This does verify that the list of packages we pulled with `dpkg_src()` contains `1.1.1d-0+deb10u3`, but in general, it doesn't guarantee that the same version will be used when we take out the version string. For example, the reason we specify a [version for stretch `libc6`](https://github.com/GoogleContainerTools/distroless/blob/54afbf9c067b0f35d8f5f3fbeae94b4daa2f5dbe/WORKSPACE#L51-L53) is that, without the version string, a different version will be used. (For some weird reason, the stretch "security" channel that takes precedence over "main" provides a lower `glibc` version than the `gblic` version from the "main" channel for some unknown weird reason.)

In any case, I think your PR pulls in `1.1.1d-0+deb10u3` and this is the version being used now. Again, thank you very much!

**Comment by chanseokoh** [comment]
We just set up GitHub Actions to automate pulling in new deb packages updated in the Debian snapshot upstream: #537.
