### ISSUE TITLE
Locally building dpkg_parser breaks previous method of external image builds.

### ISSUE THREAD

**Issue by psigen** [GoogleContainerTools/distroless#506]
In #477, a change was made to build the `dpkg_parser.par` file locally instead of fetching it from an external repository.

However, a number of projects used the prebuilt binary, exported through `//package_manager:package_manager.bzl`, to import `dpkg_list` and `dpkg_src` and use them in other workspaces.  As far as I can tell, #477 completely deleted this file, and I can't find a replacement for the functionality or documentation on an alternative strategy.

Examples of this approach are detailed in previous issues and some public forums:
- #371, #201, #176
- http://engblog.yext.com/post/customizing-distroless-with-bazel
- https://groups.google.com/forum/#!topic/bazel-discuss/26msQimSvVk

It is also seemingly in active use in a number of projects:
- https://github.com/GoogleContainerTools/base-images-docker/blob/master/WORKSPACE#L97
- https://github.com/kubernetes/kops/blob/master/WORKSPACE#L88
- https://github.com/bitnami-labs/bazel_containers/blob/master/WORKSPACE#L43
- https://github.com/stackb/distroless-bazel/blob/master/debian.bzl#L2
- https://github.com/scionproto/scion/blob/master/WORKSPACE#L110
- https://github.com/jfrog/jfrog-distroless/blob/master/WORKSPACE#L26

Is there a migration path or upcoming documentation around using `dpkg_list` and `dpkg_src` as an external dependency from another workspace using the new local build mechanism?

---

#### Additional Notes 

- It seems like there was a previous proposal to refactor the entirety of the `dpkg_` functionality, but it's a bit unclear if the replacement is working/active-maintained: #96
  - https://github.com/bazelbuild/rules_pkg
- [rules_docker](https://github.com/bazelbuild/rules_docker) seems to have its own `package_managers` installation mechanism -- should we switch to using this?
  - https://github.com/bazelbuild/rules_docker/tree/master/docker/package_managers

**Comment by chanseokoh** [comment]
I know what I'm going to tell you will disappoint you, but regrettably, we don't have the luxury to answer or respond to this kind of questions or requests that are unrelated to our efforts to build and publish up-to-date Distroless runtime images. This repo is primarily driven and maintained by the community that depends on it. Even keeping the Distroless images reasonably up-to-date is the very [challenge](https://github.com/GoogleContainerTools/distroless/issues/501#issuecomment-617525661) that repo is facing, and keeping the images up-to-date still needs a continued flow of external contributions from the user community. I've been soliciting external contributions (while I try to make a lot of contributions too as a user), works like #477 is crucial to ease the pain of building this repo from source to expand the potential base for external contribution.

Please note that this dpkg_ stuff is an [internal library](https://github.com/GoogleContainerTools/distroless/issues/463#issuecomment-587566386), and you should just not depend on any internal code that will constantly change. Just as #477 broke you, we may break it again going forward.

> * It seems like there was a previous proposal to refactor the entirety of the `dpkg_` functionality, but it's a bit unclear if the replacement is working/active-maintained: #96
>   
>   * https://github.com/bazelbuild/rules_pkg
> * [rules_docker](https://github.com/bazelbuild/rules_docker) seems to have its own `package_managers` installation mechanism -- should we switch to using this?
>   
>   * https://github.com/bazelbuild/rules_docker/tree/master/docker/package_managers

I absolutely have no idea about these repos, but if you can use one of them and it works, you should switch, I guess. I see at least they are under the [bazelbuild](https://github.com/bazelbuild) org, so maybe these are meant to be for public consumption?

**Comment by psigen** [comment]
Alright, that's fine.  I'll migrate back off of distroless, glad we caught the limitation early.

Maybe we can document that this is an unsupported use case in the `//package_managers` `README.md`, and clearly spell out that this behavior is unsupported?

I'm clearly not the only one making this mistake -- some of the other places I found it being used are  another repo within this very organization and a Kubernetes SIG projects: it's been in use unofficially since at least 2017.
