### ISSUE TITLE
Why no .dockerignore in the examples ?

### ISSUE THREAD

**Issue by asafyish** [GoogleContainerTools/distroless#517]
I was doing a local "docker build" and saw the context that is sent to the docker daemon is huge (2.4 gb) and takes a couple of seconds (Macbook 16), when I created a dockerignore with
.git and target folders, it was reduced to around 100 kb which makes much more sense.

Can create PR if it's ok .. it's just a dockerignore file with couple of lines.

**Comment by chanseokoh** [comment]
That makes sense. Will accept your PR. Thanks for considering contribution!

**Comment by chanseokoh** [comment]
Fixed by #518.
