### ISSUE TITLE
Python does have xz in its standard library

### ISSUE THREAD

**Issue by MarkusTeufelberger** [GoogleContainerTools/distroless#53]
https://docs.python.org/3/library/lzma.html

Just read the comment in cacerts.sh (https://github.com/GoogleCloudPlatform/distroless/blob/master/cacerts/extract.sh) that you wanted to write this in Go or Python - so in case you want to write this as a standalone script, it is easily possible since Python 3.3.

**Comment by dlorenc** [comment]
Ah yeah, that's only possible in python 3.3 or higher which is still experimental in bazel. I haven't actually tried the python 3 bazel support so it's possible this would just work, but I didn't want to chase down too many experimental paths.

**Comment by dlorenc** [comment]
Closing this, we have no plans to upgrade the bazel tools themselves to Python 3 until that is the default for bazel.
