### ISSUE TITLE
How do I upgrade distroless images to include `libpq.so`?

### ISSUE THREAD

**Issue by perfectmak** [GoogleContainerTools/distroless#533]
Hello,
I'm using a distroless image to execute a binary that requires `libpq.so`, but since it is not included in any of the distroless, how do I get to include it? Is there a guide somewhere that I can follow to do this?

**Comment by chanseokoh** [comment]
Here it is: https://github.com/GoogleContainerTools/distroless/issues/325#issuecomment-475255266

I am closing the issue, but out of curiosity, what is the library for, and why do you need it?

**Comment by perfectmak** [comment]
Thanks @chanseokoh. To answer you question, I'm deploying an application that intereacts with PostgreSQL and it needs that library to interact with the PostgreSQL server.

**Comment by i0n** [comment]
Here's an image using distroless-cc that includes libpq5 etc. Works as a tiny container for rust based programs with that dependency (diesel migrations etc). Or you could use bazel...
