### ISSUE TITLE
Python tests taking too much time, often causing TIMEOUT on Travis builds

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/distroless#534]
> Yeah, Python tests (2 and 3) always take the most time. But I haven't bothered to figure out why.

Last I looked: they run a TON of commands in the container, and some combination of Bazel/Docker/the container structure test tool takes FOREVER to start/tear down the container each time. This would be substantially faster if we rewrote it so it started the container ONCE, then run a bunch of separate commands. I made this worse because as I found issues with Debian10, I added MORE command tests to those targets ... oops.

_Originally posted by @evanj in https://github.com/GoogleContainerTools/distroless/pull/531#issuecomment-643453887_

**Comment by chanseokoh** [comment]
It also timed a lot in #516, so I had to add `--test_timeout=900` in https://github.com/GoogleContainerTools/distroless/pull/516/commits/e51f4787616a9267e0f5303594e8b02b897efa64. Looking at the Python tests, there are a ton of import testing. Given the trouble, they don't seem to deserve separate tests.

**Comment by evanj** [comment]
Hm. Some of those tests ARE useful: the ones that import modules that depend on various C libraries did find issues while adding Debian10 support. However, it could probably be ONE test that tries to load all of them? Hmm this gives me an idea; let me see if I can make something work...

**Comment by chanseokoh** [comment]
> However, it could probably be ONE test that tries to load all of them?

That's what I did. I didn't remove them but merged into one test.
