### ISSUE TITLE
Suggestion: better version and update management

### ISSUE THREAD

**Issue by petermylemans** [GoogleContainerTools/distroless#537]
When going through the code, I've noticed that package manager is not always selecting the most up to date version with respect to the chosen snapshot. Currently this seems to be solved by pinning the version of specific libraries in the WORKSPACE file, but this looks a bit error prone as an approach.

My proposal:
 * Introduce a versions file per package bundle (deb9 and deb10) to clearly see what versions are being used. For example: https://github.com/petermylemans/distroless/blob/versions/package_bundle_debian10.versions
 * Introduce a better version selection algorithm based on https://github.com/theclimatecorporation/python-dpkg 

To fully complete the solution, I would suggest to make a kind of bot/github action that takes the latest snapshot from debian 9 / 10, regenerate the version files and see if there is a difference. If so, the bot can send a PR for review.

**Comment by chanseokoh** [comment]
> When going through the code, I've noticed that package manager is not always selecting the most up to date version with respect to the chosen snapshot. Currently this seems to be solved by pinning the version of specific libraries in the WORKSPACE file, but this looks a bit error prone as an approach.

Exactly. You got it absolutely right.

I think your proposal is a great idea. @evanj @ LouisStAmouryou may also be interested in this. (PR #538 already filed.)

> Introduce a versions file per package bundle (deb9 and deb10) to clearly see what versions are being used.

I'm afraid this introduces another maintenance burden. I think you are saying these versions are auto-generated, but I'd like to confirm there is no manual update process for the version.

> To fully complete the solution, I would suggest to make a kind of bot/github action that takes the latest snapshot from debian 9 / 10, regenerate the version files and see if there is a difference. If so, the bot can send a PR for review.

This is a great idea. I love it.

**Comment by chanseokoh** [comment]
> When going through the code, I've noticed that package manager is not always selecting the most up to date version with respect to the chosen snapshot. Currently this seems to be solved by pinning the version of specific libraries in the WORKSPACE file, but this looks a bit error prone as an approach.

Exactly. You got it absolutely right.

I think your proposal is a great idea. @evanj @LouisStAmour may also be interested in this. (PR #538 already filed.)

> Introduce a versions file per package bundle (deb9 and deb10) to clearly see what versions are being used.

I'm afraid this introduces another maintenance burden. I think you are saying these versions are auto-generated, but I'd like to confirm there is no manual update process for the version.

> To fully complete the solution, I would suggest to make a kind of bot/github action that takes the latest snapshot from debian 9 / 10, regenerate the version files and see if there is a difference. If so, the bot can send a PR for review.

This is a great idea. I love it.

**Comment by petermylemans** [comment]
> I'm afraid this introduces another maintenance burden. I think you are saying these versions are auto-generated, but I'd like to confirm there is no manual update process for the version.

The idea would be to have these auto generated at build time (no manual edit required), but **checked** in. This make sure that when there is an update to e.g. the snapshot version, the versions files are automatically regenerated and you see the diff in the version files.

Based on this, you could even generate release notes automatically by comparing version files between different git commits / tags.

The main benefit that I see with this approach is also for code reviewing changes to the dpkg_src (e.g. newer snapshot version). The exact package updates would show up as diffs in the version files. There are some examples in the last commits of my PR #538 to fix the ca-certificates version.

**Comment by evanj** [comment]
This is a great idea. This would also help to work around the limitations of the current dpkg rules, which just take the "first" package they find, rather than doing what dpkg actually does, which is sort version numbers and take the "latest". Being able to inspect a diff might allow us to notice when this is doing the "wrong thing", and take an "older" version, which it does occasionally.

I have MANUALLY done diffs like this by running Bazel, then using a bash loop with `dpkg info` (or whatever the right command is), then re-running Bazel with the change, and diffing the output. It would be GREAT to automate this.

**Comment by petermylemans** [comment]
I also have the shell script running with a github action on my fork to auto create pull requests like e.g. https://github.com/petermylemans/distroless/pull/2 

See also https://github.com/petermylemans/distroless/actions. It failed today due to a 404 on debian snapshots though. But the script is working now on my machine. Maybe let this run for a bit and I can send a second PR with the automation after stabilization?

**Comment by chanseokoh** [comment]
Automating this with GitHub Action is a really cool idea. I am certainly interested in setting it up in this repo once it's stabilized. That said, I'm curious why it failed with 404.

**Comment by petermylemans** [comment]
Aha, because it is the 1st of july. https://snapshot.debian.org/archive/debian/?year=2020;month=07 was probably empty when the script ran. Let me go fix that.

**Comment by petermylemans** [comment]
@chanseokoh looks like Github doesn't allow to push workflow definitions through PR. I should have known that this might be considered a privileged action.

I didn't have any issues apart from the 1ste of July bug described above. So if you're interested, you can try to set it up for this repo. The file below is pretty self explanatory. The create-pull-request plugin is also smart enough to reuse an existing pull request and force push changes in case a PR remains open for some time: this will combine patches as long as the PR remains open.

Github Action that runs every night, can be defined as follows (taken from my forked repository): 

```
name: update-snapshots
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 3.2.0

    - name: Run update script
      run: ./updateWorkspaceSnapshots.sh
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: "Bumping packages to latest stable versions"
        title: "Bumping packages to latest stable versions"
        body: "Bumping packages to latest stable versions"
        branch: "update-snapshots"
```

**Comment by chanseokoh** [comment]
The deb package update is now fully automated using GitHub Actions! We will see how it goes very soon. Thank you very much for your amazing contribution @petermylemans! This wouldn't have been possible without all the non-trivial works you did.

**Comment by evanj** [comment]
As someone who fiddled with at least a few of these manual updates, thank you! This is really a great improvement.
