### ISSUE TITLE
AttributeError: 'HTTPMessage' object has no attribute 'getheader' in Python3

### ISSUE THREAD

**Issue by jonnyyu** [GoogleContainerTools/distroless#541]
I ran into error message above when using Python3.

I see `six` is used, does dpkg_parser suppose to support python3?

The issue seems like, getheader() is python2 only, maybe the fix is replace it with get() in 
https://github.com/GoogleContainerTools/distroless/blob/b39fc536a3e846dd32d8c825bb8b32cb27809c27/package_manager/dpkg_parser.py#L131

and there're other 2 places

**Comment by chanseokoh** [comment]
I am a Python newbie, so I don't really understand the implication of using `six` and Python 2 or 3. However, it sounds like `get()` sounds OK _if_ it works for both Python 2 and 3. Can you confirm? And we appreciate external contributions as this repo is primarily maintained and driven by the community.

At the moment, [`CONTRIBUTING.md`](https://github.com/GoogleContainerTools/distroless/blob/master/CONTRIBUTING.md#how-to-build-and-test) suggests `--host_force_python=PY2`. I'd like to know if this works.

**Comment by jonnyyu** [comment]
ok, unfortunately, my environment is a Python3 docker image. 
I made a PR:
https://github.com/GoogleContainerTools/distroless/pull/543

**Comment by chanseokoh** [comment]
Fixed by #543.
