### ISSUE TITLE
How to build dpkg_parser when use distroless as bazel rules extension?

### ISSUE THREAD

**Issue by jonnyyu** [GoogleContainerTools/distroless#542]
Hi,

I need use `dpkg_src` and `dpkg_list` from `distroless` in my project to create customized distroless image.

I can do a simple `bazel build //...` in my project root perfectly, until PR: https://github.com/GoogleContainerTools/distroless/pull/477, it becomes not straight forward to me. 

The 1st build after cloning project repo is always fail quickly with 

```
dpkg_parser command failed: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/Users/xxxx/.cache/bazel/_bazel_xxxx/abf0a3d83a4b1d722a32424a453d5c05/external/distroless/bazel-bin/package_manager/dpkg_parser.par, ...)": No such file or directory
```

From notes in dpkg_parser.py, I need run `bazel build //package_manager:dpkg_parser.par` before using `dpkg_src`. But that means I need goto `/Users/xxxx/.cache/bazel/_bazel_xxxx/abf0a3d83a4b1d722a32424a453d5c05/external/distroless/` to run the command, but there're some difficulties.
1. The folder doesn't exist before 1st build.
2. hard code this path is a hack, so I'm hesitate to add this logic.

Is there any better way to handle this? ideally the dpkg_parser.par is added as a dependency so it will be built automatically without extra pre-command. 

Thanks!

**Comment by chanseokoh** [comment]
> I can do a simple `bazel build //...` in my project root perfectly, until PR: #499, it becomes not straight forward to me

FTR: it is after #477, not #499 

> Is there any better way to handle this? ideally the dpkg_parser.par is added as a dependency so it will be built automatically without extra pre-command.

Unfortunately, there does not seem a better way to this (unless `dpkg_parser` is hosted outside of Distroless, I think). This seems like a frequent issue in Bazel. Please see https://github.com/GoogleContainerTools/distroless/issues/434#issuecomment-634989961 and the answer below.

**Comment by chanseokoh** [comment]
Basically, there's a circular dependency (kind of a chicken-and-egg problem): in order to set up a Distroless build, you need dpkg_parser. However, dpkg_parser can be built only after Distroless is fully set up.

**Comment by chanseokoh** [comment]
> hard code this path is a hack, so I'm hesitate to add this logic.

Oh, forgot to answer this. You'll find the binary [through the `bazel-bin/` symlink](https://github.com/GoogleContainerTools/distroless/blob/b39fc536a3e846dd32d8c825bb8b32cb27809c27/package_manager/dpkg.bzl#L10).
