### ISSUE TITLE
OpenSSL: verify error:num=20:unable to get local issuer certificate

### ISSUE THREAD

**Issue by rueian** [GoogleContainerTools/distroless#545]
Hi, I just bumped into the OpenSSL error `verify error:num=20:unable to get local issuer certificate` when using the latest `gcr.io/distroless/base-debian10:debug` image.

Reproduce procedure:

```
▶ docker run -it --rm gcr.io/distroless/base-debian10:debug
Unable to find image 'gcr.io/distroless/base-debian10:debug' locally
debug: Pulling from distroless/base-debian10
6729630f5ebf: Pull complete
e2745900642c: Pull complete
d18ce7e3cfbf: Pull complete
Digest: sha256:add8a7f47ea6b5690e79ff3826b2ab8c83ef751fd59478128de4e50f2667af0e
Status: Downloaded newer image for gcr.io/distroless/base-debian10:debug


/ # openssl s_client -connect api.push.apple.com:443
CONNECTED(00000003)
depth=1 CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = api.push.apple.com, OU = management:idms.group.533599, O = Apple Inc., ST = California, C = US
verify return:1
---
Certificate chain
 0 s:CN = api.push.apple.com, OU = management:idms.group.533599, O = Apple Inc., ST = California, C = US
   i:CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
 1 s:CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
   i:C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
---
Server certificate
-----BEGIN CERTIFICATE-----
...
```

I noticed that the ca-certificates was updated by the PR #538. Is that the cause of this error?

**Comment by chanseokoh** [comment]
Yeah, I think #538 updated Distroless to use the latest ca-certificates provided by Debian. However, I get the same result when using Debian.

```
$ docker run --rm -it debian:buster
# apt-get update && apt-get install -y openssl
...
# openssl s_client -connect api.push.apple.com:443
CONNECTED(00000003)
depth=1 CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = api.push.apple.com, OU = management:idms.group.533599, O = Apple Inc., ST = California, C = US
verify return:1
---
Certificate chain
 0 s:CN = api.push.apple.com, OU = management:idms.group.533599, O = Apple Inc., ST = California, C = US
   i:CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
 1 s:CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
   i:C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
```
If you think this is an issue, I suggest you file a bug against Debian.

**Comment by chanseokoh** [comment]
Closing as this is not an issue in Distroless.

**Comment by tompson** [comment]
I understand that this is not an Distroless issue - was there already an issue filed against Debian?

what is the suggested solution/workaround to this issue?

**Comment by chanseokoh** [comment]
I didn't file a bug, but I can tell you how to do: https://www.debian.org/Bugs/

I reckon a workaround would be to find different ca certificates and put them into your image. Haven't tried it myself, but it should work.

**Comment by chanseokoh** [comment]
Or maybe take a look at these:

https://stackoverflow.com/a/22871737/1701388
https://stackoverflow.com/q/11558177/1701388
http://lessons.livecode.com/m/4069/l/53405-how-do-i-use-push-notifications-with-ios

**Comment by tompson** [comment]
ok, I guess I will have to go the way again of creating my own custom image, it was so nice to just use the default distroless image in JIB like

```
jib {
	from {
		image = "gcr.io/distroless/java:11"
	}
	to {
...
```

**Comment by chanseokoh** [comment]
FTR, some links that may be relevant:

http://metadata.ftp-master.debian.org/changelogs/main/c/ca-certificates/unstable_changelog
https://bugzilla.redhat.com/show_bug.cgi?id=1845988
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596
https://serverfault.com/a/1022458
https://github.com/dotnet/dotnet-docker/issues/1897#issuecomment-674187165
https://github.com/dotnet/dotnet-docker/issues/2145#issuecomment-669217855

**Comment by fzyzcjy** [comment]
Thanks very much!

**Comment by mabrarov** [comment]
@fzyzcjy,

I believe that set of trusted CA certificates is a part of the application configuration, i.e. it should be defined / specified during run-time, i.e. on container / POD level and not on image level.

I use approach described in [mabrarov/docker-compose-init-container](/mabrarov/docker-compose-init-container) to generate JKS keystore with trusted CA certificates and to pass that keystore into a Spring Boot based Java application.

**Comment by fzyzcjy** [comment]
@mabrarov Thanks for the reply! Sorry I do not fully see how you did it in mabrarov/docker-compose-init-container. could you please explain a bit?

**Comment by rueian** [comment]
Hi @fzyzcjy 

You can use init container to insert trusted CA cert at the end of `/etc/ssl/certs/ca-certificates.crt`.

**Comment by mabrarov** [comment]
@fzyzcj,

> Sorry I do not fully see how you did it in mabrarov/docker-compose-init-container. could you please explain a bit?

It uses init container ([OpenShift](https://github.com/mabrarov/docker-compose-init-container/blob/master/openshift/template.yml#L104), [Docker Compose](https://github.com/mabrarov/docker-compose-init-container/blob/master/docker-compose/docker-compose.yml#L25)) which calls [this shell script](https://github.com/mabrarov/docker-compose-init-container/blob/master/init-image/src/main/resources/rootfs/run.sh). `gen_trust_store` function of the script uses Java keytool to include specified CA certificates (mounted into init container using volume) into a new JKS keystore. The generated keystore then is shared b/w init container and main container using [OpenShift (K8s) volume](https://github.com/mabrarov/docker-compose-init-container/blob/master/openshift/template.yml#L85) or [Docker volume](https://github.com/mabrarov/docker-compose-init-container/blob/master/docker-compose/docker-compose.yml#L91).
