### ISSUE TITLE
Eliminate code duplication between cacerts/cacerts.bzl and locale/locale.bzl

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/distroless#552]
`locale/locale.bzl` is introduce in #551 and almost same as [`cacerts/cacerts.bzl`](https://github.com/GoogleContainerTools/distroless/blob/5a5744efd2be5d9edb84fabd407e0f883a27dc8b/cacerts/cacerts.bzl#L1). I think it's possible to share code by [making this rule general](https://github.com/GoogleContainerTools/distroless/pull/551#discussion_r457649864):

> ... perhaps it's not really difficult to make this portion general (e.g., by accepting another input attribute to the rule besides `deb` on line 16) and share code between this and `cacerts/cacerts.bzl`. However, let's not attempt to do this now. I'll just file a cleanup issue.

This can be useful, since there are open issues (such as #447 and #508) where we need to exclude unwanted files from a `.deb` when we install them.

**Comment by petermylemans** [comment]
Maybe add a kind of deb_extract rule with an optional includes / excludes attribute that extracts files from a deb to a tar.

**Comment by chanseokoh** [comment]
FTR: #565 for a more general and flexible rule.
