### ISSUE TITLE
fix(): NodeJS images are not published with version name at all

### ISSUE THREAD

**Issue by davinkevin** [GoogleContainerTools/distroless#558]
By reading the documentation, I see there are 3 versions of nodejs images: 

* Node.js v10 (gcr.io/distroless/nodejs:10) and its dependencies.
* Node.js v12 (gcr.io/distroless/nodejs:12) and its dependencies.
* Node.js v14 (gcr.io/distroless/nodejs:14) and its dependencies.

https://github.com/GoogleContainerTools/distroless/blob/master/experimental/nodejs/README.md

But, in the gcr, I see only two tags, one latest and another for debug. 

![image](https://user-images.githubusercontent.com/1970922/88781789-1ddf7880-d18d-11ea-9a7d-86165a83bbb1.png)

https://console.cloud.google.com/gcr/images/distroless/GLOBAL/nodejs?gcrImageListsize=100

I think there is something strange about this

Thanks for your help/support, distroless images are really great 👍

**Comment by chanseokoh** [comment]
We just added the images to the repo yesterday, but there seems a technical issue with auto-publishing them. From https://github.com/GoogleContainerTools/distroless/pull/556#issuecomment-665330724,

> @chanseokoh I checked the [node.js container registry](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/nodejs?gcrImageListsize=30) and didn't see the images. I tried running the [cloudbuild.yaml locally](https://cloud.google.com/cloud-build/docs/build-debug-locally) and ran into this error.
> 
> ```
> code/distroless > cloud-build-local --config=cloudbuild.yaml .
> 2020/07/28 15:23:56 RUNNER - [docker ps -a -q --filter name=step_[0-9]+|cloudbuild_|metadata]
> 2020/07/28 15:23:56 RUNNER - [docker network ls -q --filter name=cloudbuild]
> 2020/07/28 15:23:56 RUNNER - [docker volume ls -q --filter name=homevol|cloudbuild_]
> 2020/07/28 15:23:58 Error merging substitutions and validating build: Error validating build: invalid .artifacts field: cannot specify more than 100 images to build
> ```
> 
> It seems like there may be a hard limit of 100 images to be published by a single cloudbuild run. Before my commit there were 97 images being published and after there are 103. However I couldn't find anything in the cloudbuild docs about such a limit.
> 
> Not sure what your build pipeline looks like for this behind the scenes, but the easiest thing to do may be to have separate cloudbuild files for different directories `java`, `cc`, `experimental` etc

**Comment by chanseokoh** [comment]
The images are now live.
