### ISSUE TITLE
Error: error contacting notary server: unknown: Project 'project:gcr.io:distroless' not found or deleted.

### ISSUE THREAD

**Issue by cyberbeast** [GoogleContainerTools/distroless#560]
The Docker instruction `FROM gcr.io/distroless/cc-debian10:debug` seems to fail somehow. Here's the output.
`Error: error contacting notary server: unknown: Project 'project:gcr.io:distroless' not found or deleted.`

However, when I run `FROM gcr.io/distroless/cc-debian10@sha256:5879b3ff39847ee4ea875c25ecb48db59a284464b398f2490aa0f5445e53d46f`, it seems to work.

Any suggestions?

**Comment by chanseokoh** [comment]
The image is there, and I have no problem accessing it. Probably a transient error or an issue in your environment.

**Comment by cyberbeast** [comment]
I am able to access it in the following ways:

1. Using the sha digest directly.
2. `docker pull gcr.io/distroless/cc-debian10:debug`

I am still encountering the error reported above when using it to build a `Dockerfile` with the `FROM gcr.io/distroless/cc-debian10:debug` instruction.

I've tried restarting docker, my environment, IDE and even my computer.

**Comment by chanseokoh** [comment]
```
~$ mkdir /tmp/a && cd /tmp/a && cat > Dockerfile <<<'FROM gcr.io/distroless/cc-debian10:debug'
/tmp/a$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM gcr.io/distroless/cc-debian10:debug
debug: Pulling from distroless/cc-debian10
6729630f5ebf: Pull complete 
e2745900642c: Pull complete 
b7539b77e32d: Pull complete 
c5900d68e237: Pull complete 
Digest: sha256:8f9954fb5898847f303b669fa28cdbe7ec0bc7fefda9c6faf527a6f02449bfc4
Status: Downloaded newer image for gcr.io/distroless/cc-debian10:debug
 ---> 14c5cb8f07b3
Successfully built 14c5cb8f07b3
```

@jonjohnsonjr the "notary server" error looks out of place. Any idea? Can this be a regional issue?

**Comment by cyberbeast** [comment]
I investigated further and found that the error appears when `DOCKER_CONTENT_TRUST` is set to `1`. Setting that to `0`, removes the error.

**Comment by chanseokoh** [comment]
Ah, that makes sense. GCR doesn't implement the content trust stuff. You're the second person I've ever seen who uses the notary thing. :) I'll close the issue.

**Comment by cyberbeast** [comment]
Thank you @chanseokoh
