### ISSUE TITLE
Building distroless failing with "could not set sticky bit" in Bazel's file system sandbox

### ISSUE THREAD

**Issue by smijolovic** [GoogleContainerTools/distroless#572]
Attempting to build distroless from source using bazel 3.4.1 is failing with http.client.IncompleteRead: IncompleteRead

Below is the output:

<details>

```
INFO: Analyzed target //package_manager:dpkg_parser.par (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //package_manager:dpkg_parser.par up-to-date:
  bazel-bin/package_manager/dpkg_parser.par
INFO: Elapsed time: 0.246s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Repository package_bundle_debian10 instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule _dpkg_list defined at:
  /home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/package_manager/dpkg.bzl:25:29: in <toplevel>
ERROR: An error occurred during the fetch of repository 'package_bundle_debian10':
   dpkg_parser command failed: Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/bazel-bin/package_manager/dpkg_parser.par/__main__.py", line 217, in <module>
  File "/home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/bazel-bin/package_manager/dpkg_parser.par/__main__.py", line 83, in main
  File "/home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/bazel-bin/package_manager/dpkg_parser.par/__main__.py", line 109, in download_dpkg
  File "/home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/bazel-bin/package_manager/dpkg_parser.par/__main__.py", line 127, in download_and_save
  File "/usr/lib64/python3.6/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/lib64/python3.6/http/client.py", line 624, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(38363136 bytes read, 177091100 more expected)
 (/home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/bazel-bin/package_manager/dpkg_parser.par --package-files /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/external/debian10_security/file/Packages.json,/home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/external/debian10_updates/file/Packages.json,/home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/external/debian10/file/Packages.json --packages libc6,base-files,ca-certificates,openssl,libssl1.1,libbz2-1.0,libdb5.3,libffi6,liblzma5,libexpat1,libreadline7,libsqlite3-0,mime-support,netbase,readline-common,tzdata,libgcc1,libgomp1,libstdc++6,zlib1g,libjpeg62-turbo,libpng16-16,liblcms2-2,libfreetype6,fonts-dejavu-core,fontconfig-config,libfontconfig1,libuuid1,openjdk-11-jre-headless,openjdk-11-jdk-headless,libc-bin,dash,libc-bin,libpython2.7-minimal,libpython2.7-stdlib,python2.7-minimal,libmpdec2,libpython3.7-minimal,libpython3.7-stdlib,libtinfo6,libuuid1,libncursesw6,python3-distutils,python3.7-minimal,libcurl4,libgssapi-krb5-2,libicu63,liblttng-ust0,libssl1.1,libunwind8,libuuid1,zlib1g,curl,libcomerr2,libidn2-0,libk5crypto3,libkrb5-3,libldap-2.4-2,libldap-common,libsasl2-2,libnghttp2-14,libpsl5,librtmp1,libssh2-1,libkeyutils1,libkrb5support0,libunistring2,libgnutls30,libgmp10,libhogweed4,libidn11,libnettle6,libp11-kit0,libffi6,libtasn1-6,libsasl2-modules-db,libgcrypt20,libgpg-error0,libacl1,libattr1,libselinux1,libpcre3,libbz2-1.0,liblzma5 --workspace-name package_bundle_debian10 --versionsfile /home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/package_bundle_debian10.versions)
ERROR: no such package '@package_bundle_debian10//file': dpkg_parser command failed: Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/bazel-bin/package_manager/dpkg_parser.par/__main__.py", line 217, in <module>
  File "/home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/bazel-bin/package_manager/dpkg_parser.par/__main__.py", line 83, in main
  File "/home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/bazel-bin/package_manager/dpkg_parser.par/__main__.py", line 109, in download_dpkg
  File "/home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/bazel-bin/package_manager/dpkg_parser.par/__main__.py", line 127, in download_and_save
  File "/usr/lib64/python3.6/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/lib64/python3.6/http/client.py", line 624, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(38363136 bytes read, 177091100 more expected)
 (/home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/bazel-bin/package_manager/dpkg_parser.par --package-files /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/external/debian10_security/file/Packages.json,/home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/external/debian10_updates/file/Packages.json,/home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/external/debian10/file/Packages.json --packages libc6,base-files,ca-certificates,openssl,libssl1.1,libbz2-1.0,libdb5.3,libffi6,liblzma5,libexpat1,libreadline7,libsqlite3-0,mime-support,netbase,readline-common,tzdata,libgcc1,libgomp1,libstdc++6,zlib1g,libjpeg62-turbo,libpng16-16,liblcms2-2,libfreetype6,fonts-dejavu-core,fontconfig-config,libfontconfig1,libuuid1,openjdk-11-jre-headless,openjdk-11-jdk-headless,libc-bin,dash,libc-bin,libpython2.7-minimal,libpython2.7-stdlib,python2.7-minimal,libmpdec2,libpython3.7-minimal,libpython3.7-stdlib,libtinfo6,libuuid1,libncursesw6,python3-distutils,python3.7-minimal,libcurl4,libgssapi-krb5-2,libicu63,liblttng-ust0,libssl1.1,libunwind8,libuuid1,zlib1g,curl,libcomerr2,libidn2-0,libk5crypto3,libkrb5-3,libldap-2.4-2,libldap-common,libsasl2-2,libnghttp2-14,libpsl5,librtmp1,libssh2-1,libkeyutils1,libkrb5support0,libunistring2,libgnutls30,libgmp10,libhogweed4,libidn11,libnettle6,libp11-kit0,libffi6,libtasn1-6,libsasl2-modules-db,libgcrypt20,libgpg-error0,libacl1,libattr1,libselinux1,libpcre3,libbz2-1.0,liblzma5 --workspace-name package_bundle_debian10 --versionsfile /home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/package_bundle_debian10.versions)
INFO: Elapsed time: 48.285s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: locale ... (8 packages)
    Fetching @package_bundle; fetching 48s
```
</details>

**Comment by chanseokoh** [comment]
http.client.IncompleteRead: IncompleteRead(38363136 bytes read, 177091100 more expected)

Hmm... seems like a transient error about your HTTP connection to the Debian snapshot repo. Builds have been running successfully until today. Try again?

**Comment by smijolovic** [comment]
Tried again...got past that part but hitting another issue:

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //package_manager:dpkg_parser.par (35 packages loaded, 427 targets configured).
INFO: Found 1 target...
Target //package_manager:dpkg_parser.par up-to-date:
  bazel-bin/package_manager/dpkg_parser.par
INFO: Elapsed time: 22.870s, Critical Path: 0.70s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed successfully, 18 total actions
INFO: Repository org_golang_x_tools instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository remote_coverage_tools instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/external/io_bazel_rules_docker/container/BUILD:40:11: no such package '@bazel_tools//third_party/py/gflags': BUILD file not found in directory 'third_party/py/gflags' of external repository @bazel_tools. Add a BUILD file to a directory to mark it as a package. and referenced by '@io_bazel_rules_docker//container:build_tar_lib'
ERROR: Analysis of target '//cc:cc_debian10' failed; build aborted: Analysis failed
INFO: Elapsed time: 135.632s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (49 packages loaded, 6585 targets configured)
    Fetching @com_github_google_go_containerregistry; Restarting.
    Fetching @bazel_gazelle_go_repository_config; fetching

**Comment by chanseokoh** [comment]
That's weird. How about building from a clean state?
```
$ bazel clean --expunge
$ ./test.sh
```
If that doesn't do anything, how about trying with Bazel 3.2.0? Our [Travis runs 3.2.0](https://github.com/GoogleContainerTools/distroless/blob/ad1103a45338e6c2ce08096f8a12c804d171af95/.travis.yml#L9).

**Comment by chanseokoh** [comment]
> Our [Travis runs 3.2.0](https://github.com/GoogleContainerTools/distroless/blob/master/.bazelversion).

Corrected a wrong link.

**Comment by smijolovic** [comment]
Switched to bazel 3.2.0, and getting further. 

Build errors trying to set a stickybit on libpod (we use podman/buildah/skopeo/runc):

ERROR: /home/rpmbuild/nimbus8/distroless-build-source/distroless-1.0.0/distroless/experimental/python2.7/BUILD:100:8: Executing genrule //experimental/python2.7:ld_so_cache_new failed (Exit 1) linux-sandbox failed: error executing command 
  (cd /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/sandbox/linux-sandbox/515/execroot/distroless && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/rpmbuild/.local/bin:/home/rpmbuild/bin:/usr/local/go14/bin:/usr/local/gotools/bin:/home/rpmbuild/nimbus8/bazel-build/bazel-3.2.0/output \
    TMPDIR=/home/rpmbuild/nimbus8/distroless-build-source/tmp \
  /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/install/a116c22e7aaafac1c4dbbe9a93435fc5/linux-sandbox -t 15 -w /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/sandbox/linux-sandbox/515/execroot/distroless -w /home/rpmbuild/nimbus8/distroless-build-source/tmp -w /dev/shm -w /tmp -D -- /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/experimental/python2.7/generate_ldconfig_cache bazel-out/k8-fastbuild/bin/experimental/python2.7/ld.so.cache.new')
src/main/tools/linux-sandbox.cc:156: linux-sandbox-pid1 has PID 676730
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
src/main/tools/linux-sandbox-pid1.cc:176: working dir: /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/sandbox/linux-sandbox/515/execroot/distroless
src/main/tools/linux-sandbox-pid1.cc:195: writable: /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/sandbox/linux-sandbox/515/execroot/distroless
src/main/tools/linux-sandbox-pid1.cc:195: writable: /home/rpmbuild/nimbus8/distroless-build-source/tmp
src/main/tools/linux-sandbox-pid1.cc:195: writable: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:195: writable: /tmp
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/kernel/security
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/systemd
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/cpu,cpuacct
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/cpuset
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/hugetlb
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/net_cls,net_prio
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/devices
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/rdma
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/blkio
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/freezer
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/pids
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/perf_event
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/memory
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/pstore
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/bpf
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/kernel/config
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/selinux
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/kernel/debug
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/fuse/connections
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev/pts
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev/mqueue
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev/hugepages
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /run
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /run/user/2100
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /run/user/5000
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /proc
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /boot
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /boot/efi
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /var/log
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /tmp
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /var/tmp
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /var/lib/containers
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /home
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/sandbox/linux-sandbox/515/execroot/distroless
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/sandbox/linux-sandbox/515/execroot/distroless
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /home/rpmbuild/nimbus8/distroless-build-source/tmp
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /tmp
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
Traceback (most recent call last):
  File "bazel-out/host/bin/experimental/python2.7/generate_ldconfig_cache", line 54, in <module>
    main()
  File "bazel-out/host/bin/experimental/python2.7/generate_ldconfig_cache", line 34, in main
    subprocess.check_call((load_container_exe, ), stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/sandbox/linux-sandbox/515/execroot/distroless/bazel-out/host/bin/experimental/python2.7/generate_ldconfig_cache.runfiles/distroless/experimental/python2.7/python27_debian9.executable',)' returned non-zero exit status 1.
src/main/tools/linux-sandbox-pid1.cc:423: waitpid returned 2
src/main/tools/linux-sandbox-pid1.cc:443: child exited with code 1
src/main/tools/linux-sandbox.cc:206: child exited normally with exitcode 1
loading image /home/rpmbuild/.cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/sandbox/linux-sandbox/515/execroot/distroless/bazel-out/host/bin/experimental/python2.7/generate_ldconfig_cache.runfiles/distroless/experimental/python2.7/python27_debian9.executable ...
time="2020-08-27T20:18:26Z" level=error msg="could not set sticky bit on /run/user/2100/libpod: chmod /run/user/2100/libpod: read-only file system"

libpod is already running with the sticky bit:
drwx-----T. 2 rpmbuild rpmbuild sysadm_u:object_r:user_tmp_t:s0 40 Aug 27 15:54 /run/user/2100/libpod

Mount shows filesystem rw:
tmpfs on /run/user/2100 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=400588k,mode=700,uid=2100,gid=2100)

**Comment by chanseokoh** [comment]
This looks like some issue with podman. I suspect all the images have been built (locally as tar files), but the error is when Bazel tries to load those images into podman. (That is, `bazel build //...` succeeds (image tar files built), but `bazel run` fails.)

Can you find an environment where Docker is installed and test here?

**Comment by smijolovic** [comment]
I'm just running:

bazel build //package_manager:dpkg_parser.par
bazel build //... --sandbox_debug

Is there a way NOT to have it run, and just pull those tar files? I'm assuming they must be docker-archive or oci-archive files.

Docker is a non-starter for security purposes.

**Comment by chanseokoh** [comment]
Hmm... I think my suspicion was wrong. If it's failing on `bazel build` and not on `bazel run`, I think it shouldn't involving any container runtime, be it Docker or podman. But then, it's really weird that the log has `/run/user/2100/libpod`, which I thought is a local directory that podman uses.

> Docker is a non-starter for security purposes.

As an idea, you should be able to run `gcr.io/cloud-marketplace-containers/google/bazel:3.2.0` with your podman, which contains `bazel`, `git`, `docker`, etc. Can you try this only for testing? I am not forcing you to install Docker in your environment, just find some environment for testing/debugging purposes.

**Comment by chanseokoh** [comment]
In any case, I suggest to report the issue to [rules_docker](https://github.com/bazelbuild/rules_docker). This is what Distroless uses to assemble image archive files.

**Comment by smijolovic** [comment]
I will report to that repo...but I'm getting close so I have one other question:

bazel build //package_manager:dpkg_parser.par
bazel build //java:java11_debian10

Appears to work:

INFO: Analyzed target //package_manager:dpkg_parser.par (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //package_manager:dpkg_parser.par up-to-date:
  bazel-bin/package_manager/dpkg_parser.par
INFO: Elapsed time: 0.337s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Analyzed target //java:java11_debian10 (57 packages loaded, 6652 targets configured).
INFO: Found 1 target...
INFO: From ImageLayer base/static_debian10-layer.tar:
Duplicate file in archive: ./etc/os-release, picking first occurrence
INFO: From Action cacerts/cacerts_java_debian10.tar:
+ mkdir -p etc/ssl/certs/java
+ bazel-out/host/bin/cacerts/jksutil/jksutil_/jksutil
+ tar -xOf bazel-out/k8-fastbuild/bin/cacerts/cacerts_debian10.tar ./etc/ssl/certs/ca-certificates.crt
+ bazel-out/host/bin/external/rules_pkg/build_tar --output bazel-out/k8-fastbuild/bin/cacerts/cacerts_java_debian10.tar --file ./etc/ssl/certs/java/cacerts=./etc/ssl/certs/java/cacerts
Target //java:java11_debian10 up-to-date:
  bazel-bin/java/java11_debian10-layer.tar
INFO: Elapsed time: 166.452s, Critical Path: 5.77s
INFO: 38 processes: 38 linux-sandbox.
INFO: Build completed successfully, 70 total actions

How can I extract that via a bazel to as either a docker-archive or oci-archive image vs using bazel run?  I see the tar file produced in .cache/bazel/_bazel_rpmbuild/b7d35c6c7c651f4f3e6802aeff641f4b/execroot/distroless/bazel-out/k8-fastbuild/bin/java/java11_debian10-layer.tar

**Comment by chanseokoh** [comment]
I believe that is a Docker image archive you can load with `docker load` or something. Podman should be able to load it in the same way. (Podman accepts the Docker format by default unless you explicitly specify OCI, if my memory serves right.)

**Comment by chanseokoh** [comment]
Or, it may not be the final archive given that it has the `-layer` suffix. But `bazel build` should definitely create an image archive somewhere. `bazel run` simply loads the archive to Docker for you.

**Comment by chanseokoh** [comment]
Any update on this? Is this resolved?

**Comment by smijolovic** [comment]
Yes I did file an issue there.  Closing here,
