### ISSUE TITLE
Document that go apps need "CGO_ENABLED=0" to work

### ISSUE THREAD

**Issue by dlorenc** [GoogleContainerTools/distroless#58]

**Comment by dlorenc** [comment]
Bonus points for figuring out how to make cgo work.

**Comment by jmhodges** [comment]
Do you have a bit of go code that fails with cgo enabled? I can't reproduce the problem with code that imports and uses mattn/go-sqlite3.

**Comment by jmhodges** [comment]
(Here's the travis build I have where I tested that out: https://travis-ci.org/jmhodges/distroless_sh_bug/builds/266257763)

**Comment by jmhodges** [comment]
Ping! Still looking for cgo-using code that has an error. Can't repro the problems! Maybe Go has fixed the issues?

**Comment by dlorenc** [comment]
@jmhodges Thanks for checking this out, I actually can't remember what I did to cause this issue :( Do you have a small sample that does work? We could add it here as a test case. and close out this issue.

**Comment by jmhodges** [comment]
I have one that depends on sqlite3, does that count?

You might have to play with the `base` param in the BUILD file.

Here's hello.go:

```
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/mattn/go-sqlite3"
)

func main() {
	db, err := sql.Open("sqlite3", ":memory:")
	if err != nil {
		log.Fatalln("Open:", err)
	}
	_, err = db.Exec("create table foo (name text)")
	if err != nil {
		log.Fatalln("Exec:", err)
	}
	defer db.Close()
	fmt.Println("Hello, World")
}
```

And it's BUILD.bazel:

load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_binary", "go_test")
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_build")


go_binary(
    name = "hello",
    visibility = ["//visibility:public"],
    deps = ["@com_github_mattn_go_sqlite3//:go_default_library"],
    srcs = ["hello.go"],
)

docker_build(
    name = "prod",
    base = "//:base",
    entrypoint = ["./hello"],
    files = [
        ":hello",
    ],
    ports = ["8080"],
)

**Comment by jmhodges** [comment]
Perhaps the issue was in loading from shared libs on disk separately, not c files built with the go tool?

**Comment by jmhodges** [comment]
I think maybe building something with the race detector and running it in the image will demonstrate the bug?

**Comment by dolmen** [comment]
`CGO_ENABLED=0` is required to work with `grc.io/distroless/static`.

But `grc.io/distroless/base` exists to work with `CGO_ENABLED=1`.

**Comment by jmhodges** [comment]
Great! (I suspect that's new since this ticket was last updated?)
