### ISSUE TITLE
multi-arch support for nodejs

### ISSUE THREAD

**Issue by mattmoor** [GoogleContainerTools/distroless#607]
In the style of: https://github.com/GoogleContainerTools/distroless/pull/605

I would be much more comfortable with this if the nodejs rules had `container_test` rules similar to what Python does leveraging the repl directly from the testdata file.

cc @JustinBeckwith (I don't know that I know enough Node.js for this 😅 )

**Comment by JustinBeckwith** [comment]
This is a little beyond my capabilities, but it may be nice to get folks from the Node.js Docker working group engaged here :)  @bcoe do you know who would be a good person to reach to and work with?

**Comment by mattmoor** [comment]
Just to further clarify, I think that what I'd like is some very simple canary tests of a base Node environment like: https://github.com/GoogleContainerTools/distroless/blob/master/experimental/python2.7/testdata/python27.yaml

If there are some good Node.js snippets that we can crib to turn into tests like this, I can try to do some of that legwork, since I'm already in the thick of it.

**Comment by chanseokoh** [comment]
Some images have tests under `examples/`, and they do get executed as part of the build. For example,

https://github.com/GoogleContainerTools/distroless/blob/45167136864447c99736f1d3133db4c48f7dc4ed/examples/nodejs/BUILD#L28

I think it's a bit weird to have the tests there.

**Comment by bcoe** [comment]
👋 I notice that Simen Bekkhus, who I've worked with quite a bit, is in the Node.js Docker working group. Would it be helpful for me to try to loop them in?

**Comment by mattmoor** [comment]
@chanseokoh Cool, I didn't see those there.

I think having tests for the examples makes sense, but what I'm talking about specifically is focused testing of the image itself in the style of `python -c "<program>"`.  It's good to know we have some smoke testing, thanks for the pointer. 👍

**Comment by loosebazooka** [comment]
node is multiarch 16,18 support arm64/amd64
