### ISSUE TITLE
multi-arch support for dotnet

### ISSUE THREAD

**Issue by mattmoor** [GoogleContainerTools/distroless#608]
In the style of: https://github.com/GoogleContainerTools/distroless/pull/605

I don't see any `container_test` rules for these, which would build my confidence in the correctness of what they are doing.

**Comment by chanseokoh** [comment]
As mentioned in https://github.com/GoogleContainerTools/distroless/issues/607#issuecomment-702334593, we have some tests under `examples/`. For dotnet,

https://github.com/GoogleContainerTools/distroless/blob/45167136864447c99736f1d3133db4c48f7dc4ed/examples/dotnet/BUILD#L21-L30
