### ISSUE TITLE
describe how folks can view all of the images generated

### ISSUE THREAD

**Issue by jmhodges** [GoogleContainerTools/distroless#61]
Folks who are new to this might not know how to view all the distroless images available to be used in their browser. In fact, I've forgotten how to do it again in my browser. I had to hand hack my own personal registry URLs in order to figure it out.

It might help to link to https://console.cloud.google.com/gcr/images/distroless/GLOBAL/base or similar explicitly.

**Comment by jmhodges** [comment]
Oh, right, but that UI doesn't show the digests. So, it's not quite what we want.

**Comment by mattmoor** [comment]
So the left column there is the abbreviated digest (drop `sha256:` and shorten), you can get the full digest by clicking the checkbox and then "Show Pull Command".

**Comment by jmhodges** [comment]
Cool. Mind if I patch the README to say something about that?

**Comment by mattmoor** [comment]
Not at all!

**Comment by lathama** [comment]
The readme is very complete. Optionally one could link to https://console.cloud.google.com/gcr/images/distroless/GLOBAL for a listing of all the images. Is this still important over a year later?
