### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by jpgu-epam** [GoogleContainerTools/distroless#610]
Hi friends, I've been stook with this error some days, and I'm not able to find what is going on.

I'm trying to create a docker container with kerberos into it. I have a **WORKSPACE** with the following rules:

```
git_repository(
    name = "distroless_rules",
    remote = "https://github.com/googlecloudplatform/distroless.git",
    commit = "45167136864447c99736f1d3133db4c48f7dc4ed"
)

load(
    "@distroless_rules//package_manager:dpkg.bzl",
    "dpkg_src",
    "dpkg_list",
)

dpkg_src(
    name = "debian_stretch",
    arch = "amd64",
    distro = "stretch",
    sha256 = "90ff32c8226b57b879bf6b8c3cfda15e24f2b8c22de28426872f162db4e8d444",
    snapshot = "20201002T083935Z",
    url = "http://snapshot.debian.org/archive",
)

dpkg_list(
    name = "package_bundle",
    packages = [
        "krb5-admin-server",
    ],
    sources = [
        "@debian_stretch//file:Packages.json",
    ],
)
```

And a **BUILD** that looks like this:

```
load("@package_bundle//file:packages.bzl", packages_amd64_debian9 = "packages")

container_image(
    name = "scala_samba_base_image",
    base = DEFAULT_SCALA_BASE_IMAGE,
    debs = [
        packages_amd64_debian9["krb5-admin-server"]
        ],
    visibility = ["//visibility:public"],
)
```

But any time I try to build this I'm getting the following root error:

```
ERROR: An error occurred during the fetch of repository 'debian_stretch':
   dpkg_parser command failed: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/private/var/tmp/_bazel_juan_pablo_gomez/0c4b96ff11a0d8227864b81f1b6c9571/external/distroless_rules/bazel-bin/package_manager/dpkg_parser.par, ...)": No such file or directory
 (/private/var/tmp/_bazel_juan_pablo_gomez/0c4b96ff11a0d8227864b81f1b6c9571/external/distroless_rules/bazel-bin/package_manager/dpkg_parser.par --download-and-extract-only=True --mirror-url=http://snapshot.debian.org/archive --arch=amd64 --distro=stretch --snapshot=20201002T083935Z --packages-gz-url= --package-prefix= --sha256=90ff32c8226b57b879bf6b8c3cfda15e24f2b8c22de28426872f162db4e8d444)
```

Any help would be much appreciated, thanks so much!

**Comment by petermylemans** [comment]
You probably need to build the distroless package manager first:
    `bazel build  @distroless_rules//package_manager:dpkg_parser.par` or something similar (haven't tried it outside of distroless)

Reason: dpkg_list is a repository rule (evaluated first), but it depends on a python tool in the same distroless repository (that needs to be built after the repository is evaluated) to do the work. Effectively creating a chicken and egg kind of problem. 

You can have a look at test.sh or CONTRIBUTING.MD in distroless how it is handled in the internal builds. I guess you'll have to do something similar.

**Comment by chanseokoh** [comment]
Closing as `dpkg_src` and `dpkg_list` are internal rules. No support for public consumption.
