### ISSUE TITLE
Latest OpenJDK 11.0.9 version not available via GCR

### ISSUE THREAD

**Issue by quiqua** [GoogleContainerTools/distroless#634]
Hej!

I've been using the distroless containers for a while now and wanted to check if the most recent LTS for Java11 is available.

According to this file https://github.com/GoogleContainerTools/distroless/blob/03b1c748f6c7aa5d81b92838374309ac997e8100/java/testdata/java11_debian10.yaml#L27

I'd assume that it is.

I then checked the images available at GCR and pulled the [latest java-11-debug](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java-debian9@sha256:ea6afd63c77e1ed9a40e64ed35ef704c7104594717bcd3064cdb0eaca67caa14/details?tab=info) version.

This is the dockerfile to I used:
```
FROM gcr.io/distroless/java@sha256:ea6afd63c77e1ed9a40e64ed35ef704c7104594717bcd3064cdb0eaca67caa14

CMD ["-version"]
```

Building the container: `docker build -t gcr-java11 -f Dockerfile.distroless-java .` and running it `docker run -it gcr-java11` yields:
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1bpo91)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1bpo91, mixed mode)
```  

Is there anything I am missing here?

**Comment by mpeddada1** [comment]
Hey @quiqua, thanks for the question! I see that you’re using `gcr.io/distroless/java-debian-9 `. Debian 9 is currently [old stable](https://wiki.debian.org/DebianOldStable) which occasionally gets updated for security reasons. Debian 10 is the current stable distribution, so you should try using `gcr.io/distroless/java-debian10:11` (which I believe has the updated java package). Hope this helps.

**Comment by quiqua** [comment]
Ah cool, yes that helps - I guess the [readme](https://github.com/GoogleContainerTools/distroless/blob/master/java/README.md) was a bit unclear then.
