### ISSUE TITLE
Please support latest version of Java 11  (11.0.9.1+1)

### ISSUE THREAD

**Issue by NikolayMetchev** [GoogleContainerTools/distroless#650]
There is a bug fix version of java  11.0.9.1+1.
However the latest java-debian10 image still seems to be on the previous version of Java (11.0.9+11-post-Debian-1deb10u1)
It looks like debian has this newer version available:
https://packages.debian.org/sid/openjdk-11-jdk

**Comment by chanseokoh** [comment]
That package info is about [Debian Unstable (sid)](https://wiki.debian.org/DebianUnstable). Looks like Debian 10 buster (stable) [still has 11.0.9+11-1~deb10u1](https://packages.debian.org/buster/openjdk-11-jdk). Not to worry, Distroless will automatically update the version once Debian 10 gets it.
