### ISSUE TITLE
Unable to write in /tmp (Read-only file system (os error 30))

### ISSUE THREAD

**Issue by vadim-shilov** [GoogleContainerTools/distroless#654]
Hello!

One of the dependent libs in my Node.js app tries to create a UDS /tmp/SOME_CUID.sock and fails with the error `Read-only file system (os error 30)`. My image based on `cc-debian10`.
There was the PR https://github.com/GoogleContainerTools/distroless/pull/80/commits with fixes the same problem but these changes were overwritten later by this commit https://github.com/GoogleContainerTools/distroless/commit/c127f3e5f3fed537f808762c1cbccf814c902c24#diff-ccdbb7dd65b28b355ef4e2bcec2d800386b440cd00cf16b44e26a1c73adb3a38.

Could you advise how to deal with this error?

**Comment by chanseokoh** [comment]
The latter commit still [unpacks `tmp.tar`](https://github.com/GoogleContainerTools/distroless/commit/c127f3e5f3fed537f808762c1cbccf814c902c24#diff-8807993c8f4e302c5ba0921c331ea0d5d0b66024188e986c09000a9c2a35d285R45-R49). Are you sure its `/tmp`? Maybe the permission error is coming from a different source.

**Comment by vadim-shilov** [comment]
Not sure. I have the only piece of logs at this moment. I'll ask developers of this lib and will back with additional info.

**Comment by chanseokoh** [comment]
Sounds good. I had no problem creating a unix domain socket using the following code:

```c
#include <fcntl.h>
#include <sys/un.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

int main(int argc, char **argv)
{
    char * mysocketpath = "/tmp/mysock";
    struct sockaddr_un namesock;
    int fd;
    namesock.sun_family = AF_UNIX;
    strncpy(namesock.sun_path, (char *)mysocketpath, sizeof(namesock.sun_path));
    //fd = socket(AF_UNIX, SOCK_DGRAM, 0);
    fd = socket(AF_UNIX, SOCK_STREAM, 0);
    bind(fd, (struct sockaddr *) &namesock, sizeof(struct sockaddr_un));
    close(fd);
    return 0;
}
```
(The code is from https://stackoverflow.com/a/35784688/1701388.)

```Dockerfile
FROM gcr.io/distroless/cc-debian10:debug
COPY a.out /
```

```
$ gcc a.c
$ docker build -t test .
Sending build context to Docker daemon  20.99kB
Step 1/2 : FROM gcr.io/distroless/cc-debian10:debug
 ---> 7c9bc37a93bc
Step 2/2 : COPY a.out /
 ---> c70585b141c3
Successfully built c70585b141c3
Successfully tagged test:latest
$ docker run --rm -it --entrypoint /busybox/sh test
/ # ls -l /tmp
total 0
/ # ./a.out 
/ # ls -l /tmp
total 0
srwxr-xr-x    1 root     root             0 Dec 11 19:07 mysock
/ # 
```

**Comment by vadim-shilov** [comment]
You were right! The reason is that our k8s spec has the flag `readOnlyRootFilesystem: false` :)
Thank you for your help!
