### ISSUE TITLE
Add a test to ensure node.js/grpc works with our glibc

### ISSUE THREAD

**Issue by dlorenc** [GoogleContainerTools/distroless#66]
There have been some issues with node.js and grpc with alpine and other minimal containers. We should make sure it works here.

**Comment by HofmannZ** [comment]
@dlorenc What exactly does not work? We're using `gcr.io/distroless/nodejs` in production with gPRC micro-services. Haven't found any issues so far.

**Comment by chanseokoh** [comment]
Thanks for confirming that gRPC works. I guess the issue is obsolete then.
