### ISSUE TITLE
How to update pkgs in distroless image

### ISSUE THREAD

**Issue by Nikhilrompalli09** [GoogleContainerTools/distroless#667]
As per the gcr scan glibc and other packages are showing as Vulnerable. So i want to update package with stable one. 

I tried to change the pkg version in package_bundle_amd64_debian10.versions & WORKSPACE and tried to build image with `bazel run --host_force_python=PY2 //java:java11_root_debian10` , But still image has the old version pkgs.

Can anyone help me out to update the pkgs versions in distroless image.

**Comment by Nikhilrompalli09** [comment]
corresponding to this snapshot (`https://snapshot.debian.org/archive/debian/$DEBIAN_SNAPSHOT/`) i am able to see both `openssl-1.1.1d-0` and  `openssl1.1.1i-1` in `pool/pkgs/` .. then how come it taking only `openssl-1.1.1d-0`? Are we specifying it ?

**Comment by chanseokoh** [comment]
Basically a higher version is selected (#538).

> * Added current version selection as described by debian guidelines (using pydpkg code).

**Comment by chanseokoh** [comment]
Oh, what I meant above is when multiple `Packages.gz` from different channels (e.g., `main`, `backports`, `updates`, and `security`) have multiple versions for the same package. Note that `pool/pkgs/` is just a storage location for package files. `Packages.gz` is the metadata for a snapshot.

```
$ curl -so- https://snapshot.debian.org/archive/debian/20210105T023154Z/dists/buster/main/binary-amd64/Packages.gz | gunzip | grep -A3 -B3 '^Package: openssl'
MD5sum: 7484e22240fdc090af20c426f3ba378a
SHA256: b293309a892730986e779aea48e97ea94cd58f34f07fefbd432c210ee4a427e2

Package: openssl
Version: 1.1.1d-0+deb10u3
Installed-Size: 1460
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
$ 
```

**Comment by Nikhilrompalli09** [comment]
Okay got it. From debian itself we are getting.

I want to update the **openssl** version to `openssl1.1.1i-1` and **glibc** to `glibc_2.31-6`, how can i do so?

**Comment by chanseokoh** [comment]
Not sure if this is a good workaround in your situation, but how about #533?

Maybe another very hacky way is to hardcode the versions for those packages in `dpkg_parser.py` or `parse_metadata.py`? Never tried myself.

**Comment by Nikhilrompalli09** [comment]
Updated `dpkg_parser.py` to get specific version. its working.
Thanks @chanseokoh for you help.
