### ISSUE TITLE
Adding Chrony to the image

### ISSUE THREAD

**Issue by pranasblk** [GoogleContainerTools/distroless#669]
First of all need to express gratitude and respect for sharing such amazing project free of charge!

I'd like to create base image using AWS [Atomic clock](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure-amazon-time-service-ubuntu)

Is there some way in accomplishing it? Is there some ways in running some linux daemon processes with distroless. Let me know if you have some documentation about available options and best practices. 

Thanks a lot!

**Comment by chanseokoh** [comment]
For installing your own stuff, how about #533?

For general questions about running a daemon process in a container, probably it's out of scope to answer here. I don't see anything specific to distroless in that regard.

**Comment by pranasblk** [comment]
Sorry to bother, but it makes no sense for container as time should be taken from the host VM. It was a silly question.
