### ISSUE TITLE
Location of Debian9/10 building project

### ISSUE THREAD

**Issue by pranasblk** [GoogleContainerTools/distroless#672]
I'm not expert of the Bazel build system, but seems like you just referring Debian binary images from  google image repository https://console.cloud.google.com/gcr/images/debian10/GLOBAL .

Is building whole e.g. ```base``` image from source possible without pointing to google Cloud storage or prefabricated binaries? 
Let me know if I missed something, but I don't see how kernel is build from sources at all.

Thanks for clarification!

**Comment by chanseokoh** [comment]
> seems like you just referring Debian binary images from google image repository https://console.cloud.google.com/gcr/images/debian10/GLOBAL

No. Distroless builds an image from scratch, mostly unpacking Debian packages (`.deb` files) found on the `snapshot.debian.org` package repository. It doesn't use any Docker images on GCR or Cloud Storage.
