### ISSUE TITLE
Add libpq.so to a distroless image

### ISSUE THREAD

**Issue by GaetanFauconnier85** [GoogleContainerTools/distroless#673]
I want to add libpq.so to a distroless image. I have seen this issue : https://github.com/GoogleContainerTools/distroless/issues/533 so i try the following :

```
FROM debian:stretch AS builder
RUN apt install --yes libpq.so

FROM rust:1.49.0 as build-env

WORKDIR /app
ADD . /app
RUN cargo build --release

FROM gcr.io/distroless/cc
COPY --from=builder /usr/lib/x86_64-linux-gnu/libpq.so /usr/lib/x86_64-linux-gnu/libpq.so
COPY --from=build-env /app/target/release/sportbook /

CMD ["./sportbook"]
```

But I got this response :

```
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libpq.so
E: Couldn't find any package by glob 'libpq.so'
E: Couldn't find any package by regex 'libpq.so'
Error response from daemon: The command '/bin/sh -c apt install --yes libpq.so' returned a non-zero code: 100
Failed to deploy '<unknown> Dockerfile: Dockerfile': Can't retrieve image ID from build stream
```

Can you find a way to avoid that ? Maybe im not working with the correct version or name of the library ?

**Comment by chanseokoh** [comment]
Perhaps the package name is `libpq5`. Try `apt install libpq5`. See the [list of files](https://packages.debian.org/buster/amd64/libpq5/filelist) in the package.

**Comment by i0n** [comment]
Here's an image using distroless-cc that includes libpq5 etc. Works as a tiny container for rust based programs with that dependency (diesel migrations etc). Or you could use bazel...

https://github.com/i0n/distroless-libpq5-debian-11
https://hub.docker.com/repository/docker/i0nw/distroless

**Comment by DriLLFreAK100** [comment]
Just an add-on to @i0n's solution, beware of the machine architecture as well. The copy path for `arm64 (aarch64)` architecture and `amd64 (x86_64)` architecture machines are different altogether.

For my use case, I was trying to write a Dockerfile that runs a Rust application with Actix Web + diesel + postgres, while using `distroless` as the image base to achieve a small docker image build size.

You may refer to this [Dockerfile here](https://github.com/DriLLFreAK100/codefee-works-api/blob/1c85f9761d6aa2e0552eeea052242e8582443acc/Dockerfile) as an example. I have also written an in-depth article for this over here https://www.codefeetime.com/post/docker-config-for-actix-web-diesel-and-postgres/ 

Hope it helps!
