### ISSUE TITLE
How to use distroless for infrastructure images without switching build systems to bazel

### ISSUE THREAD

**Issue by FSeidinger** [GoogleContainerTools/distroless#688]
Dear Distroless Team,

I like the Idea of having secure and small base images. But from the view of an end user I lack some support on the UX part. Let me explain:

As a pretty basic docker image developer I know how to handle `docker build` and have a decent knowledge of shell scripts. Some skills in Java and Javascript. So far I have now knowledge in bazel and do not want to learn it, for just using distroless images.

That said, I could not find any helpful hints in this project or on the internet on how to use the distroless images as a base image and install some software in it using one of the common package mangers.

From my point of view this is the ultimate default use case for most of the infrastructure containers you use as surrounding systems for your own application. In my experience you have a ration of 1 to 3 up to 1 to 10 between maintaining your own application (the one part) and needed infrastructure containers.

Do not get me wrong, I love this project and its efforts, but It would be greatly improve, If I can use distroless for the many infrastructure containers without the burden to switch the development to bazel.

**Comment by briandealwis** [comment]
Hi @FSeidinger.  Part of Distroless' security posture is that there are no packages, in large part so that an attacker cannot easily install new packages into an image.  At the moment any extensions must be done through the build system, which means learning Bazel.

You might want to check out nixery.dev: it is a webservice for generating small purpose-driven container images using the Nix package manager.  I don't think it has a way to prevent installing the shell, however.

**Comment by chanseokoh** [comment]
> how to use the distroless images as a base image and install some software in it using one of the common package mangers.

Certainly Distroless doesn't have a package manager, but if you only need install a few small things, you can do something like this: #673 But yeah, this approach is not so feasible for installing a big package with lots of transitive dependencies. At least it's easy to install a simple shell.

And I see there can be two types of Distroless users:
- Users simply using the publicly available Distroless images published on gcr.io: no `bazel` involved.
- Users building new Distroless variants from the git source: they clone the repo, update the source, and run `bazel`.

The point is that you might not need to build images from source (which this repo doesn't support) depending on your situation.
