### ISSUE TITLE
Please update JRE version of the gcr.io/distroless/java:11 image

### ISSUE THREAD

**Issue by cschaible** [GoogleContainerTools/distroless#691]
Dear Distroless Team,

we're using the `gcr.io/distroless/java:11` image and our application logs lots of the following error messages:
```i.k.c.o.ApiException: javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request```.

A workaround is described [here](https://stackoverflow.com/questions/60790118/java-kubernetes-client-sslhandshakeexception-extension-5-should-not-be-present) by adding `-Djdk.tls.client.protocols=TLSv1.2` to the jvm args.

This error seem to be related to the used JRE version and was fixed in JRE 11.0.7 as descibed [here](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8236039).

In the [debian-9](https://github.com/GoogleContainerTools/distroless/blob/master/package_bundle_amd64_debian9.versions) based image, what seems to be used as the base for the `java:11` image, JRE 11.0.6 is used (which is older than a year).
In the [debian-10](https://github.com/GoogleContainerTools/distroless/blob/master/package_bundle_amd64_debian10.versions) a newer version is used, though i haven't found a released `java:11` image that is based on `debian-10` [here](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java?gcrImageListsize=30).

Could you please release a new version with an updated JRE version (latest is currently [11.0.10](https://www.oracle.com/java/technologies/javase/11u-relnotes.html)).

Thanks in advance,

Regards Christian

**Comment by chanseokoh** [comment]
Closing as a dup of #555.
