### ISSUE TITLE
Project ownership and trust level information

### ISSUE THREAD

**Issue by olliefr** [GoogleContainerTools/distroless#696]
Hello,

I've been trying to find the ownership information for the `distroless` project (as well as for wider _GoogleContainerTools_ GitHub organisation), and I have failed in this quest.

Could you please clarify, whether `distroless` is an official Google project? Or unofficial project by Google staffers? A project staffed by volunteers, unrelated to Google, perhaps?

I'm sorry if this information is in some obvious place, please direct me to it if this is the case.

Put bluntly, I'm trying to figure out the trust level of `distroless` - is this a project a few enthusiasts run in their spare time or is it backed by an org? It's not obvious from the project's README or other GitHub info. Unless I missed something obvious.

Thanks!

**Comment by dlorenc** [comment]
Hi @olliefr! This repository is officially maintained by Google in it's current state. You can trust what is here to stay up-to-date and be built/released to the best of our ability.

We do not have any major plans for new features or languages right now - our main goal is supporting the critical projects (like kubernetes/kubernetes) that rely on these images directly.

I hope that answers your questions!

**Comment by olliefr** [comment]
Hi, @dlorenc! Yes, it does, thank you very much! 🙃 

May I be so bold as to suggest that the repo's README is updated with information on the project's ownership and the GitHub org is domain-verified with one of the domains controlled by Google? I think it will go a long way towards communicating authority. 

By the means of example --

Contrast the Go org on GitHub with the GoogleContainerTools org:

![image](https://user-images.githubusercontent.com/967105/111420090-4489f980-86f3-11eb-8ad4-967d4b8087b6.png)

![image](https://user-images.githubusercontent.com/967105/111420200-77cc8880-86f3-11eb-9d22-1dd683df2c1c.png)

The domain verification process on GitHub isn't too tedious: [Verifying your organization's domain](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain). It will help with establishing trust with the new users.

I came across this repo following a Sysdig article suggesting that `distroless` images can be used to run Go binaries without the accumulated cruft of a full distro and I was like "hey, what a cool idea!", but then the next thing the article said was 

> You should prefer verified and official images from trusted repositories and providers over images built by unknown users.

And I was like... sooo, who are these `distroless` guys? I read the `README`, poked around the org pages... I could see that the same org maintains `skaffold` but that's not a qualification in itself, IMO.

What I'm suggesting is a bit of extra work, but I believe it is beneficial in fighting the good fight for better security on the web 🙃

I rest my case!
