### ISSUE TITLE
Vulnerabilities in npm modules

### ISSUE THREAD

**Issue by shulevas** [GoogleContainerTools/distroless#697]
Hi, I'm using image **gcr.io/distroless/nodejs:12**. But there is a vulnerable package **y18n@4.0.0** in it. This vulnerability has been fixed in version 4.0.1. How can I update the package version inside the image?

**Comment by bezzers** [comment]
More to the point, why is npm even in these containers? The npm install work should be happening outside them.

**Comment by ericofusco** [comment]
npm and many npm packages are included in the tar file downloaded from nodejs website: [here](https://github.com/GoogleContainerTools/distroless/blob/5ab7f9867be4f64dd35a1fd482f36ca6e0be3d64/WORKSPACE#L168).

It seems there are no downloads available without npm. I'm not sure if this a hard dependency for node, but maybe npm and these packages can be removed? Assuming all these packages are downloaded by the app in the build stage if needed.
