### ISSUE TITLE
Delete Debian9 Images

### ISSUE THREAD

**Issue by dlorenc** [GoogleContainerTools/distroless#709]
It's been EOL for a year now. We're currently overloading the debian snapshot mirrors and have been getting rate limited on and off for a month or so. We need to trim the build matrix here a bit. Given we're unable to release at all right now, we're unfortunately going to have to go a bit faster than I would have liked.

Images based on debian 9 will stay, but won't get new builds anymore.

**Comment by dlorenc** [comment]
https://github.com/GoogleContainerTools/distroless/pull/712 will handle this for everything, but it opts the "naked" java tags (the ones without a version or distro in them) out of CI builds. This could be a "breaking" change since it updates to java11.

We'll have to track that separately.

cc @chanseokoh

**Comment by dlorenc** [comment]
Java builds on debian9 are now disabled.

**Comment by Sineaggi** [comment]
Does this mean images like `gcr.io/distroless/java` now point to `gcr.io/distroless/java-debian10`? Or only that `gcr.io/distroless/java` is now no longer being updated?

**Comment by dlorenc** [comment]
> Or only that `gcr.io/distroless/java` is now no longer being updated?

Right now they are no longer being updated. We can change them to point to `gcr.io/distroless/java-debian10`. If anyone wants.

**Comment by chanseokoh** [comment]
@dlorenc you can resume updating Java (i.e., making [this line](https://github.com/GoogleContainerTools/distroless/pull/712/files#diff-3053677e4333a96b20ed76c662bca07fb2e1ce059479170139209356787da09cR201) live) as long as the following continues to exist and they are really Java 8 (which I believe they will):

- `gcr.io/distroless/java:8` and their variants
- `gcr.io/distroless/java/jetty:java8` and their variants

Consequences:
1. Those repositories will be a mix of Debian 10 and 9. (Java 8 images will be based on Debian 9.)
2. Java 8 images are no longer updated. This is already the case. It's frozen.

I recommend against using Java 8 images. Don't use them.

**Comment by Sineaggi** [comment]
So is the recommendation to use a fully tagged image name, like `gcr.io/distroless/java:11` for java? Or is that also still debian9? Maybe `gcr.io/distroless/java-debian10:11`?

**Comment by dlorenc** [comment]
Yea, the ones with debian10 in the name I think.

**Comment by StitzL** [comment]
@chanseokoh, could you please explain why Java 8 images are frozen? Would it possible to move them to Debian 10 as well if someone provided a PR, or could you refer me to some information why this can't or mustn't be done?

**Comment by loosebazooka** [comment]
Debian 9 is no longer updated and includes a lot of packages with CVEs, it's potentially dangerous to continue to use it.
Debian 10 does not have a java8 package. The alternatives are really:
1. Use the distroless java11 image
2. Use an adoptopenjdk java8 image from dockerhub
3. Provide a proposal for java8 support on debian10 + contribute that solution here.

**Comment by StitzL** [comment]
Thank you for the concise summary, @loosebazooka. I am looking for guidance on whether option 3 would actually make sense from the point of view of this project's maintainers.

**Comment by loosebazooka** [comment]
I think given the current conditions, it's unlikely that (3) is viable. I would pick (1) or (2). Adding this kind of complexity, with dependencies outside of the debian packages is not the goal of the distroless project.

On the otherhand there is nothing stopping you from forking or building on top of what distroless has to offer.

**Comment by 616b2f** [comment]
Is this issue about delete debian9 images or about how to prevent debian snapshot mirrors to stop rate limit the project? I am interested in the last one, because this was the issue why dotnet images does not exist anymore and I would love to have them back.

**Comment by loosebazooka** [comment]
This is about deleting debian9 images. As a side-effect, this also frees up the cost of builds. Dotnet is not planned for the immediate future.
