### ISSUE TITLE
Query re version of tzdata in gcr.io/distroless/static:nonroot

### ISSUE THREAD

**Issue by davidhay1969** [GoogleContainerTools/distroless#722]
Apologies if this is a dumb question, but we're using `gcr.io/distroless/static:nonroot` on a IBM Z Ubuntu ( `s390x` ) environment, and the resulting image is throwing up vulnerability warnings related to `tzdata` : -

```text
Vulnerable Packages Found
=========================

Vulnerability ID   Policy Status   Affected Packages   How to Resolve   
DLA-2542-1         Active          tzdata              Upgrade tzdata to >= 2021a-0+deb9u1   
DLA-2509-1         Active          tzdata              Upgrade tzdata to >= 2021a-0+deb9u1   
DLA-2424-1         Active          tzdata              Upgrade tzdata to >= 2021a-0+deb9u1   
```

Looking at [package_bundle_s390x_debian9.versions](https://github.com/GoogleContainerTools/distroless/blob/main/package_bundle_s390x_debian9.versions) I *think* that still references an older version of `tzdata` namely: -

```text
    "tzdata": "2020a-0+deb9u1",
```

Any idea if/when that binary might get upgraded to `2021a-0+deb9u1` or above ?

Thanks in advance, Dave

**Comment by dlorenc** [comment]
gcr.io/distroless/static:nonroot is on debian10 I think?

I just checked locally and see 2021a-0+deb10u1, but I haven't tried s390x...

Debian 9 is no longer being updated though, so if it's not on debian10 it's not going to be updated unless we switch.

**Comment by davidhay1969** [comment]
😕 Thanks @dlorenc so I wonder why we're getting reports related to the `deb9` version of `tzdata` ? 😕 

Will dig further ....

**Comment by chanseokoh** [comment]
You should look at [`package_bundle_s390x_debian10.versions`](https://github.com/GoogleContainerTools/distroless/blob/main/package_bundle_s390x_debian10.versions), not [`package_bundle_s390x_debian9.versions`](https://github.com/GoogleContainerTools/distroless/blob/main/package_bundle_s390x_debian9.versions). I think the repo should delete all `pacakge_bundle_*_debian9.versions`?

**Comment by davidhay1969** [comment]
Yeah, good point - just trying to work out why our `docker build`, which is pulling in the image via: -

```text
FROM gcr.io/distroless/static:nonroot
```

in the Dockerfile, is *appearing* to be grabbing [package_bundle_s390x_debian9.versions](https://github.com/GoogleContainerTools/distroless/blob/main/package_bundle_s390x_debian9.versions) rather than [package_bundle_s390x_debian10.versions](https://github.com/GoogleContainerTools/distroless/blob/main/package_bundle_s390x_debian10.versions)

Probably just me "holding it wrong"

Thanks for your guidance, will continue to dig dig dig 👍

**Comment by chanseokoh** [comment]
Run `docker pull gcr.io/distroless/static:nonroot` once before `docker build`.

**Comment by davidhay1969** [comment]
Ooo, that's a good idea - will give that a try, thanks @chanseokoh

**Comment by davidhay1969** [comment]
Looks like you totally nailed it @chanseokoh I did `docker pull gcr.io/distroless/static:nonroot` *before* I did my `docker build` and it appears to have worked - the resulting image doesn't throw up the vulnerability reports re `tzdata`

Not 💯 why this would occur, it feels like there's some kind of "caching" going on, where the `deb9` bundle is being pulled in lieu of `deb10`, even though I'm not specifying a request for either - I'm just using `FROM gcr.io/distroless/static:nonroot
` in my Dockerfile.

Ah, well, no matter - looks good

Will re-run the process again, just to be sure, but thank you SO much for your suggestion

Assuming all is well, I'll come back and close the issue

Thanks again to you both @dlorenc @chanseokoh

**Comment by davidhay1969** [comment]
Yep, I ran back through the build process again, including the preparatory step to pull `gcr.io/distroless/static:nonroot` before doing the `docker build`

Thanks again @dlorenc @chanseokoh happy to close 👍 💯 🙇
