### ISSUE TITLE
How to update vulnerable os packages?

### ISSUE THREAD

**Issue by utkarshmani1997** [GoogleContainerTools/distroless#725]
Since there are no package managers, how affected binaries can be patched or updated with the fixed versions?

**Comment by chgl** [comment]
I don't think there's a way to do so manually. You'll have to wait for the distroless base images to be updated (which happens regularly) and then rebuild your image. In theory, you might be able to do something like `COPY --from debian:10 /usr/lib/libc.so /usr/lib/libc.so`.
