### ISSUE TITLE
Latest tag `gcr.io/distroless/java:11` introduces SSL error when connecting to AWS RDS database

### ISSUE THREAD

**Issue by arthuroz** [GoogleContainerTools/distroless#731]
Current latest tag `gcr.io/distroless/java:11` is pointing to 
gcr.io/distroless/java@sha256:ae5d32ed4da6d2207fd34accde64f5b1264cbdd1340fa8c1cfa70cdf1841f9db

Our Spring Boot v2.4.3 application fails to connect to RDS database using the latest tagged version, below is the root cause in error ​log:
`Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites`

Reverting to previous tagged version works:
gcr.io/distroless/java@sha256:1606422cc472612cb5bcd885684b4bf87b3813246c266df473357dce5a0fb4b

**Comment by DirkRusche** [comment]
We have the same issue. It turns out that there is a change in OpenJDK ([there is a blog post from aws about that](https://aws.amazon.com/blogs/opensource/tls-1-0-1-1-changes-in-openjdk-and-amazon-corretto/)). But we haven't found a final solution yet (except rolling back as you did).

**Comment by cameronbraid** [comment]
Same issue when connecting to mailgun using tls - even though we run with tls 1.2 via `-Djdk.tls.client.protocols=TLSv1.2`

```
org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Can't send command to SMTP host;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate). Failed messages: javax.mail.MessagingException: Can't send command to SMTP host;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate); message exception details (1) are:
Failed message 1:
javax.mail.MessagingException: Can't send command to SMTP host;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:1420)
	at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:1408)
	at com.sun.mail.smtp.SMTPTransport.ehlo(SMTPTransport.java:847)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:384)
	at javax.mail.Service.connect(Service.java:275)
```

**Comment by mabrarov** [comment]
Hi,

Doesn't custom java.security file (like described in https://dzone.com/articles/how-override-java-security) help you to turn on back required cipher suites / TLS protocols?

**Comment by hGURyxDeXPwYydc8m9snMB7sroBz3YKk** [comment]
The MySQL connector uses for compatibility reasons by default <=TLS 1.1, which is okay with older OpenJDKs. Since the recent OpenJDK dropped support for TLS 1.0 and 1.1 only TLS 1.2 is possible.
Just add `?enabledTLSProtocols=TLSv1.2` to your connection string: `jdbc:mysql://hostname:3306/dbname?enabledTLSProtocols=TLSv1.2`.

**Comment by cameronbraid** [comment]
> Same issue when connecting to mailgun using tls - even though we run with tls 1.2 via `-Djdk.tls.client.protocols=TLSv1.2`
> 
> ```
> org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Can't send command to SMTP host;
>   nested exception is:
> 	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate). Failed messages: javax.mail.MessagingException: Can't send command to SMTP host;
>   nested exception is:
> 	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate); message exception details (1) are:
> Failed message 1:
> javax.mail.MessagingException: Can't send command to SMTP host;
>   nested exception is:
> 	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
> 	at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:1420)
> 	at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:1408)
> 	at com.sun.mail.smtp.SMTPTransport.ehlo(SMTPTransport.java:847)
> 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:384)
> 	at javax.mail.Service.connect(Service.java:275)
> ```

Fix for my issue is from https://stackoverflow.com/questions/50707257/how-to-verify-the-tls-version-used-in-javax-mail

```
props.setProperty("mail.smtp.ssl.protocols", "TLSv1.2"); 

```
