### ISSUE TITLE
Add support for NodeJS 16 images

### ISSUE THREAD

**Issue by chgl** [GoogleContainerTools/distroless#736]
NodeJS v16 has been available for a few weeks and will be the next LTS version starting October 2021. It would be great to have distroless images with this new version.

Would you already accept a PR adding v16 images?

We could keep the `latest`, `debug`, etc. tags (https://github.com/GoogleContainerTools/distroless/blob/main/BUILD#L142-L147) pointing to v14 until it's an official LTS.

**Comment by Anthonyzou** [comment]
Any timeline for this happening?

**Comment by chgl** [comment]
If it's as straightforward as adding "16" to some places and updating checksums in others I'd be happy to create a PR if there's an OK from the maintainers.

**Comment by loosebazooka** [comment]
Go for it, getting it all working on debian 11 would be nice too. #844
