### ISSUE TITLE
Make the distroless image as part of Docker official images

### ISSUE THREAD

**Issue by tymonx** [GoogleContainerTools/distroless#739]
I have already opened this issue in Docker  official images https://github.com/docker-library/official-images/issues/10218

This will allow to use the Distroless in Docker official images.

I see two solutions:

- add the Distroless image to [repeatability](https://github.com/docker-library/official-images/blob/master/README.md#repeatability) exceptions. No effort, it requires approval/agreement from Docker maintainers
- add the Distroless as part of Docker official images. Little more effort. It requires Docker project manifest using the [bashbrew](https://github.com/docker-library/bashbrew) tool and it must follow the [Docker official images approach](https://github.com/docker-library/official-images/blob/master/README.md)

**Comment by loosebazooka** [comment]
We currently have no plans to do this.
