### ISSUE TITLE
Use `--production` instead of `--only=production`.

### ISSUE THREAD

**Issue by issuefiler** [GoogleContainerTools/distroless#740]
> With the `--production` flag (or when the `NODE_ENV` environment variable is set to `production`), npm will not install modules listed in `devDependencies`.

Is there any back-compatibility reason for not sticking to the [documented](https://docs.npmjs.com/cli/v7/commands/npm-install) flag “`--production`” and using the undocumented flag “`--only`” instead?

https://github.com/GoogleContainerTools/distroless/blob/2cac07c7c62b2dc52c4274a1810939fb06039ab9/examples/nodejs/Dockerfile#L5

**Comment by loosebazooka** [comment]
Node rely's heavily on community contributions, so contributing a PR to this would be appreciated

**Comment by omBratteng** [comment]
This can probably be closed, as #1036 removed `--only=production`.
