### ISSUE TITLE
Keep lists of packaged-installed files inside a built image

### ISSUE THREAD

**Issue by pombredanne** [GoogleContainerTools/distroless#741]
Since distroless are primarily built with Bazel I filed this issue https://github.com/bazelbuild/rules_docker/issues/1876 that am repasting here... but I reckon this may need to be tracked here instead:

# 🚀 feature request

### Relevant Rules
When a package is installed, only metadata are kept and the list of installed files is lost/not saved with the package metadata.

I have a concern with what happens here: https://github.com/bazelbuild/rules_docker/blob/d18033b7eb3429a55dc4a579b5c19af57ab25e5f/container/build_tar.py#L224

### Description

In a distroless container image, the as-installed .deb packages are not saved with their files/md5sums file lists in what would be in `/var/lib/dpkg/info` on a regular Debian install. As a result, it is not possible to relate an installed package in a distroless image/layer to the set of files that were installed with this package.

This data can be important for software composition analysis and its security and license compliance tracking applications.

### Describe the solution you'd like

Each installed package should include some installed file listing possibly added in some per package file in the  `status.d/` directory. This is a Debian standard in `/var/lib/dpkg/info/<package name>`

This would make distroless images more readily introspectable and observable, otherwise there is no intrinsic way to relate a package (in status.d) to the set of its installed files.

@tejal29 you committed this originally with @dlorenc ... any insight to share there?

### Describe alternatives you've considered

I cannot fathom an in-container alternative to keep a tab of each packaged-installed file. Tracking outside would mean maintaining some external database which does not seem practical.

**Comment by pombredanne** [comment]
@loosebazooka gentle ping... do you want a patch here or at https://github.com/bazelbuild/rules_docker/issues/1876?

**Comment by loosebazooka** [comment]
Oh sorry, yeah I mean I don't know why this form of metadata was chosen. Anyway, it seems like the correct place to inject the metadata is in rules_docker. Please provide a patch there.

**Comment by fedemengo** [comment]
@pombredanne any news on this?

**Comment by fedemengo** [comment]
@pombredanne gentle ping, any news on the patch?

**Comment by pombredanne** [comment]
> @pombredanne gentle ping, any news on the patch?

I have attacked this yet. Do you want to chip in and help?

**Comment by fedemengo** [comment]
Let's continue the discussion over at [bazelbuild/rules_docker#1876](https://github.com/bazelbuild/rules_docker/issues/1876)

**Comment by pombredanne** [comment]
@loosebazooka FYI I pushed a fix in https://github.com/bazelbuild/rules_docker/pull/2065 and your review is mucho welcomed there

**Comment by fedemengo** [comment]
Since the fix has been [provided](https://github.com/bazelbuild/rules_docker/pull/2065) by @pombredanne and released in bazel docker rules [v0.25.0](https://github.com/bazelbuild/rules_docker/releases/tag/v0.25.0) what's left to see the change reflected in new images?

Is it enough to bump `rules_docker` [here](https://github.com/GoogleContainerTools/distroless/blob/2113c917759da0c6178e3ded4d4d8bd13000ddfd/WORKSPACE#L72)?

**Comment by loosebazooka** [comment]
@thesayyn are these covered in the new rules_oci?

**Comment by thesayyn** [comment]
> @thesayyn are these covered in the new rules_oci?

Yes. it is.

**Comment by fedemengo** [comment]
> > @thesayyn are these covered in the new rules_oci?
>
> Yes. it is.

Does this mean we should already see it reflected in new images? 

> NOTE: some packages don't have an md5sums file, in that case, it is absent.

at least for the packages that have md5sums files

**Comment by loosebazooka** [comment]
@fedemengo not yet. We're in the middle of a larger transition to rules_oci and when that is complete, you will being to see this metadata.

**Comment by fedemengo** [comment]
awesome, thanks for the update

**Comment by pombredanne** [comment]
@loosebazooka you wrote:

> We're in the middle of a larger transition to rules_oci and when that is complete, you will being to see this metadata.

Hey! is the transition done?

**Comment by fedemengo** [comment]
looks like after https://github.com/GoogleContainerTools/distroless/pull/1367 the new images contain the expected metadata

**Comment by pombredanne** [comment]
As far as I am concerned, this is fixed.

See https://github.com/aboutcode-org/scancode.io/issues/138#issuecomment-2370554319 for extensive details.

The short story: my patch was merged, then the rules abandoned and in the end bazel rules are not strictly used anymore for this. Instead this shell script by @thesayyn in rules_distroless keeps the Debian md5sum files.
https://github.com/GoogleContainerTools/rules_distroless/blob/35a7d5a37b34e68f1d58d7e452147afe941f3e5a/apt/private/dpkg_statusd.sh#L10

@thesayyn and @loosebazooka Thanks for carrying this through! I hope this stays "API" for the future, as container introspection tools are relying on this and will be broken if this is dropped.
