### ISSUE TITLE
Image: gcr.io/distroless/java:8 only supports CMD in Exec Mode and not in CMD Shell Mode

### ISSUE THREAD

**Issue by joymarielim** [GoogleContainerTools/distroless#745]
I'd like to use _gcr.io/distroless/java:8_ as our base image. Our JAR filename is derived based on the artifact's version. That being said, it is important for me to use variable expansion and that is only possible in CMD Shell Mode. 

**Dockerfile in Exec mode** 
Steps to Recreate:
1. Create Dockerfile in Exec Mode:
 ```
FROM gcr.io/distroless/java:8
COPY ...
CMD ["an-example-application.jar"]
```
2. Build Dockerfile
3. Run the container
`docker run --rm -p 8080:8080 an-example-application:latest`
Output:
<img width="938" alt="Screen Shot 2021-06-04 at 4 45 30 PM" src="https://user-images.githubusercontent.com/7516002/120865798-5477e380-c554-11eb-8641-c424d096dbba.png">

**Dockerfile in Shell mode** 
Steps to Recreate:
1. Create Dockerfile in Exec Mode:
 ```
FROM gcr.io/distroless/java:8
COPY ...
CMD "an-example-application.jar"
```
2. Build Dockerfile
3. Run the container
`docker run --rm -p 8080:8080 an-example-application:latest`
Output:
`Error: Unable to access jarfile /bin/sh`

**Comment by ericofusco** [comment]
This is not possible because distroless doesn't have a shell.

From README:

> Note that distroless images by default do not contain a shell. That means the Dockerfile ENTRYPOINT command, when defined, must be specified in vector form, to avoid the container runtime prefixing with a shell.
