### ISSUE TITLE
Also sign Java image with cosign

### ISSUE THREAD

**Issue by jiebler** [GoogleContainerTools/distroless#747]
Hello together,

Is there a reason that the Java images are, other than the rest of the images, not signed with cosign in the `cloudbuild_cosign.sh` script? I am curious, because in the README it says, that 

> All distroless images are signed by cosign

but I when I execute `cosign verify -key cosign.pub gcr.io/distroless/java:11` I get an `error: fetching signatures`.
Verifying python for example works fine: `cosign verify -key cosign.pub gcr.io/distroless/python3:latest`

It would be very helpful for us to be able to verify the Java images with cosign as well.

**Comment by Tammychmarney** [comment]
I am in CANADA AND I HAVE ISSUES WITH INTERFERENCE FROM EUROPE

**Comment by loosebazooka** [comment]
This is done for java17, java11 and java-base images: https://github.com/GoogleContainerTools/distroless/blob/main/cloudbuild_cosign.sh#L48

You will be required to use the debian distribution specific version though for example:

cosign verify -key cosign.pub gcr.io/distroless/java11-debian11
