### ISSUE TITLE
Build date is 1970-01-01T00:00:00Z

### ISSUE THREAD

**Issue by indigo423** [GoogleContainerTools/distroless#754]
It seems like the created date is set to "Created": "1970-01-01T00:00:00Z". 
```
docker images
gcr.io/distroless/java   11                8dd58dcbce7b   51 years ago   200MB
```

**Comment by jonjohnsonjr** [comment]
https://github.com/GoogleContainerTools/distroless/issues/112

**Comment by dekkagaijin** [comment]
That's done intentionally to make builds reproducible
