### ISSUE TITLE
Which people are allowed to publish images to gcr.io/distroless (Googlers or community too)?

### ISSUE THREAD

**Issue by haroldlbrown** [GoogleContainerTools/distroless#809]
We want to use `gcr.io/distroless/java` in our organization. However, there are still some doubts in our organization about the security policy of `gcr.io/distroless/java`.

I have read the [Security Policy](https://github.com/GoogleContainerTools/distroless/security/policy) of distroless. What's still unclear for us is which people are able to publish manual changes of `gcr.io/distroless/java` to the Docker registry? Are these only people from Google? Or are they from the community as well?

**Comment by mattmoor** [comment]
Generally, only googlers have access to the GCP project where things are published, BUT generally I wouldn't expect humans to be doing anything with that access unless it's debugging an automation failure.  Really the images are published by cloudbuild as PRs merge, so non-Googlers with commit-bit (like myself) can conceivably trigger new images to be published.

Not sure if that helps (or hurts), but if you want to discuss more synchronously, I'd be happy to chat (`mattmoor` on K8s, and several other slacks).

**Comment by loosebazooka** [comment]
There are a few trusted community contributors, but all admins are the project are Googlers.
