### ISSUE TITLE
Doesn't work with distroless/cc

### ISSUE THREAD

**Issue by tomocrafter** [GoogleContainerTools/distroless#812]
Tried with example of rust but it doesn't work properly.
It hangs with `attaching to app_1` without debug tag on docker-compose.
If I added the debug tag to distroless/cc then it says `/hello-world-distroless: line 1: syntax error: unexpected ")"`

Tested machines:
M1 Mac
Docker on Windows Subsystem for Linux
Native Ubuntu

**Comment by tomocrafter** [comment]
I am very sorry to say it but it was mistaken by me.
I still have problem that I cannot gracefully stop the server with `Ctrl + C` on distroless but I close this issue because it is not related to this issue I think.

**Comment by lcmgh** [comment]
@tomocrafter Could you point out the solution to your initial problem? I'm currently facing the same error message.
