### ISSUE TITLE
Publish debian11 variant

### ISSUE THREAD

**Issue by cirocosta** [GoogleContainerTools/distroless#815]
Hi!

I noticed that despite Debian 11 having been released a few weeks ago (see [release article](https://www.debian.org/News/2021/20210814)), here we're still only publishing debian10 ones. 

PRs like https://github.com/GoogleContainerTools/distroless/pull/796 make me think that there's still a bit of work to finalize. That being the case, is there an obvious way that one can see what's missing? 

```console
$ find . -name "BUILD" | xargs -n1 ag -l debian11
base/BUILD
BUILD
cc/BUILD
```

doesn't yield much insight 😅
 
also, is there a particular "cutoff" for deciding on that? e.g., should _all_ experiments be ready for debian11?

Thank you!

---

actually, looking at `BUILD`, `base` and `static` ones do have `debian11` published

https://github.com/GoogleContainerTools/distroless/blob/d984bea67727b03ff04ad848fd31425588ad1c54/BUILD#L37-L47

https://github.com/GoogleContainerTools/distroless/blob/d984bea67727b03ff04ad848fd31425588ad1c54/BUILD#L65-L75
 

might be worth, in the meantime, adding some form of footnote to the README to indicate that? wdyt?

**Comment by dlorenc** [comment]
cc @loosebazooka we should get the rest of the debian ones published this week and flip the default soon.

**Comment by loosebazooka** [comment]
tracking in #844
