### ISSUE TITLE
Tracking java 17

### ISSUE THREAD

**Issue by Sineaggi** [GoogleContainerTools/distroless#838]
Looks like there are a few builds of java 17 build 35 (ga) in sid https://packages.debian.org/sid/openjdk-17-jre-headless
I'm assuming we're waiting for those builds to be available in bullseye https://packages.debian.org/bullseye/openjdk-17-jre-headless

**Comment by sideeffffect** [comment]
The headless variant, to be specific, right?
https://packages.debian.org/bullseye/openjdk-17-jre-headless

**Comment by Sineaggi** [comment]
> 
> 
> The headless variant, to be specific, right? https://packages.debian.org/bullseye/openjdk-17-jre-headless

Correct

**Comment by gabrieljones** [comment]
Is there anything I can do to help with this. I am not so familiar with Bazel. Really anxious to get a `java:17-nonroot` image.

**Comment by loosebazooka** [comment]
Yeah, actually lemme put together a PR today

**Comment by loosebazooka** [comment]
for sure, I'm working on it at the moment.. it wont be pushed to registry quite yet, but local testing should be helpful. I'll add instructions once it's done.

**Comment by loosebazooka** [comment]
So #859 has preliminary java17 builds (based on early access java17 `17~19-1`)

Images are **not** published to gcr

You can use the current build to push the following images to a local docker daemon
- "distroless/java:17"
- "distroless/java:17-nonroot"
- "distroless/java:17-debug"
- "distroless/java:17-debug-nonroot"

by running
```
bazel run //:java17_preview
```

We can always use your help to verify these images work with your application.

**Comment by Sineaggi** [comment]
I meant more wrt requiring debian11 as part of the tag name

**Comment by mohanrao** [comment]
@loosebazooka  i followed the latest steps still i am getting some new errors. Could you please guide me what to do next ?

`ERROR: An error occurred during the fetch of repository 'amd64_debian10_security':
   dpkg_parser command failed: Traceback (most recent call last):
  File "/Users/mohanarao/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mohanarao/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)`

**Comment by gabrieljones** [comment]
17.0.1+12-1 was migrated to testing on Oct 26
https://tracker.debian.org/pkg/openjdk-17
<anticipation.gif>

**Comment by loosebazooka** [comment]
Hah, okay lets go. I'll update the builds and maybe do a release today or next week.

**Comment by tobq** [comment]
> Hah, okay lets go. I'll update the builds and maybe do a release today or next week.

Was it released yesterday?

**Comment by loosebazooka** [comment]
Had to get pushed to next week. Willing to accept PRs from someone working this weekend though.

**Comment by kunal-bhatia** [comment]
Any plans for its release this week or if it has been already released?

**Comment by loosebazooka** [comment]
I think the weird version with the tilde is causing some confusion with the updates. Looking into that. So it is not released. In the future, you can see if something is released by trying to pull the image.

**Comment by rockwotj** [comment]
> In the future, you can see if something is released by trying to pull the image.

I tend to look at https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java is that still a good link?

**Comment by Sineaggi** [comment]
@loosebazooka With the most recent release no longer containing a tilde in its version, is this still a blocker?

**Comment by loosebazooka** [comment]
There's no blockers now. I'm out of office today though, so it'll be a day or two

**Comment by loosebazooka** [comment]
The 17 images are finally available!

https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java17
https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java17-debian11

**Comment by nhmarujo** [comment]
I was expecting to see the images fall under https://console.cloud.google.com/gcr/images/distroless/GLOBAL/java?tag=17. Will that happen or did the organisation change?

**Comment by lborupj** [comment]
Seems like they are under java17 and not just a tag for java

https://console.cloud.google.com/gcr/images/distroless/global/java17

**Comment by nhmarujo** [comment]
Yes, I noticed that. That is why I was asking if that is the organisation or if we should also expect to be able to find by by a tag on `java`, just like gcr.io/distroless/java:17

**Comment by loosebazooka** [comment]
Yes the organization changed a bit. This is more consistent with the other images. Let's us do latest...

**Comment by nhmarujo** [comment]
Thanks for the clarification @loosebazooka . Also thank you for the longed waited images 😉

**Comment by ruslan-platonov** [comment]
Thanks for releasing the image.

**Comment by Sineaggi** [comment]
Are `gcr.io/distroless/java17` and `gcr.io/distroless/java17:nonroot` now the same image/

**Comment by loosebazooka** [comment]
@Sineaggi they shouldn't be? 
`gcr.io/distroless/java17` points to `:latest` which uses the build target: `//java:java17_root_amd64_debian11`
`gcr.io/distroless/java17:nonroot` uses the build target: `//java:java17_nonroot_amd64_debian11`

**Comment by sideeffffect** [comment]
Shouldn't they have different layers then?
https://console.cloud.google.com/gcr/images/distroless/global/java17@sha256:301cd3708314ea6a11bc5fa1ea337d4460f750cf9b3f6349ecac61052c732170/details?tab=pull
vs
https://console.cloud.google.com/gcr/images/distroless/global/java17@sha256:635392c34dfa71b1f4fb48964a074ce69ae1371a3018dbf57a707137ca23de9b/details?tab=pull

**Comment by loosebazooka** [comment]
no the only difference is in the config for the user. `java17:latest` will have `User:0`, and `java17:nonroot` will have a `User:65532`, everything else remains the same.

**Comment by Guillaume-Mayer** [comment]
It's awesome if I may. Big thanks.
Distroless (no shell etc..) and non root, are now two strong arguments, it's a big deal to convince people who care about security.
