### ISSUE TITLE
debian 11 support

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/distroless#844]
Track progress on debian 11 images.
- [x] base (#788)
- [x] static (#788) 
- [x] cc
  - [x] add rules (#795) 
  - [x] publish images (#849)
- [x] java
  - [x] 11 (#846)
  ~~17~~ punted to later
- [x] node (#848)
  - [x] 12
  - [x] 14
  - [x] 16 (#845)
- [x] python 3.9 (#796)

Finally
- [x] test images bug bash
- [x] make defaults point to debian 11

**Comment by loosebazooka** [comment]
PRs are welcome here.
Please leave a comment if you are actively developing support.

**Comment by ericofusco** [comment]
Hey @loosebazooka, it doesn't seem cc is complete, it's not available at gcr.io/distroless/cc-debian11.

**Comment by loosebazooka** [comment]
> Hey @loosebazooka, it doesn't seem cc is complete, it's not available at gcr.io/distroless/cc-debian11.

Ah yeah you're correct. We'll have to update hte root BUILD file for this.

**Comment by ericofusco** [comment]
Thanks @loosebazooka, here is the PR to publish cc images: https://github.com/GoogleContainerTools/distroless/pull/849

**Comment by evanj** [comment]
Now that my Debian 11 Python 3 change is merged, I think some follow up changes to `BUILD` and possibly also to `cloudbuild_cosign.sh` and `cloudbuild_docker.sh`. I do not fully understand how these files are used. I'm happy to take a stab at copy/pasting the changes I see for other images into these if that is helpful?

**Comment by loosebazooka** [comment]
Oh yeah for manifest lists and stuff. Yeah take a look. I think we've been running into a cloud kms rate limit for signing. Not sure if we'll need that up @priyawadhwa ?

**Comment by loosebazooka** [comment]
And we're done! Default images are debian11!
