### ISSUE TITLE
Non-matching os-release files

### ISSUE THREAD

**Issue by robbiemcmichael** [GoogleContainerTools/distroless#867]
The current base and static images (and possibly others) have two os-release files which don't seem to match.

`/etc/os-release`
```
PRETTY_NAME="Distroless"
NAME="Debian GNU/Linux"
ID="debian"
VERSION_ID="11"
VERSION="Debian GNU/Linux 11 (bullseye)"
HOME_URL="https://github.com/GoogleContainerTools/distroless"
SUPPORT_URL="https://github.com/GoogleContainerTools/distroless/blob/master/README.md"
BUG_REPORT_URL="https://github.com/GoogleContainerTools/distroless/issues/new"
```

`/usr/lib/os-release`
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

I'm guessing either the `/usr/lib/os-release` version should be removed or the script which generates `/etc/os-release` needs to be updated to write the file to both locations.

**Comment by loosebazooka** [comment]
Oh strange, and you don't see this on any of the debian 10 images?

**Comment by loosebazooka** [comment]
> I'm guessing either the /usr/lib/os-release version should be removed or the script which generates /etc/os-release needs to be updated to write the file to both locations.

Yeah lets just write to both locations. @abiswas2017 you wanna take a look at this?
