### ISSUE TITLE
Build Distroless Error (no such package '@arm_debian10_security)

### ISSUE THREAD

**Issue by mahdaouimoatassim** [GoogleContainerTools/distroless#877]
When i try to build the distroless image, i get this error : 

in /Users/gitlab/RD/distroless/base/distro.bzl: Encountered error while reading extension file 'file/packages.bzl': no such package '@package_bundle_arm_debian10//file': no such package '@arm_debian10_security//file': dpkg_parser command failed: src/main/tools/process-wrapper-legacy.cc:75: "execvp(/Users/gitlab/RD/distroless/bazel-bin/package_manager/dpkg_parser.par, ...)": No such file or directory

I dont know why bazel cant find the package.

I try the build form two different environment : Linux Debain and MaC ARM64

**Comment by loosebazooka** [comment]
You have to build dpkg_parser.par first: https://github.com/GoogleContainerTools/distroless/blob/main/CONTRIBUTING.md#how-to-build-and-test
