### ISSUE TITLE
OCI runtime exec failed  no such file or directory: unknown

### ISSUE THREAD

**Issue by yuchao86** [GoogleContainerTools/distroless#891]
└─[0] <> docker exec -it 3dc1a0257977 /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

how into exec the command to the container?

**Comment by loosebazooka** [comment]
Distroless is not designed for running a shell, see the first line in the [README.md](https://github.com/GoogleContainerTools/distroless)

> "Distroless" images contain only your application and its runtime dependencies. They do not contain package managers, shells or any other programs you would expect to find in a standard Linux distribution.

**Comment by yuchao86** [comment]
I got，use the image： Distroless:bebug ..

**Comment by loosebazooka** [comment]
Debug is not designed for production use.
