### ISSUE TITLE
Compliance issue with distroless nodejs image.

### ISSUE THREAD

**Issue by vgunugu-BRONGA** [GoogleContainerTools/distroless#892]
Hi team, We found below issue in nodejs distroless image. Is there any other a non-root image for nodejs without this issue which we can use, or have you fixed this known vulnerability highlighted by: CIS_Docker_v1.20 - 4.1? Could you please help with this?

Image details:-  distroless/nodejs:14

<img width="682" alt="image" src="https://user-images.githubusercontent.com/34351461/140187062-daebbcc1-9373-499e-a432-9ada31e5e3dd.png">

**Comment by loosebazooka** [comment]
All node images appear to use the root user. But we're open to contributions for non-root images.
