### ISSUE TITLE
java: Shell hangs using debug image

### ISSUE THREAD

**Issue by cedws** [GoogleContainerTools/distroless#897]
I have no idea why this could be happening, but when running the `gcr.io/distroless/java:debug` image and using `sh` as the entrypoint, the shell will freeze up after one command. The container continues to run so I can exec in with another shell which works perfectly fine. The only way to stop the container is to kill it.

```
$ docker run --rm --entrypoint sh -it gcr.io/distroless/java:debug
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/ #
/ #
(hang)
```

The shell for these images is working as expected:
* `ubuntu:latest`
* `alpine:latest`

Note that it's complaining about architecture. I'm on an M1 MacBook but that shouldn't affect anything unless there is a bug in the compatibility layer provided by Docker.

**Comment by cedws** [comment]
Not happening on my work MBP 2015 which suggests this is indeed a scary compat issue.
Will raise an issue with Docker but I would appreciate if this could be left open until more investigation is done.

**Comment by loosebazooka** [comment]
just fyi, the shell is distorless:debug is from busybox

**Comment by cedws** [comment]
🤔 can't reproduce this anymore. I will reopen if I get it again.
