### ISSUE TITLE
golang code crashes on distroless image

### ISSUE THREAD

**Issue by DB185344** [GoogleContainerTools/distroless#917]
Hey guys, I've been trying to implement distroless containers on 1 of our components that's written in GO, and I've been having some issues, after a lot of online searching I was able to find this Dockerfile which kinda works for us:

```
FROM golang:latest as build-env

RUN GOOS=linux GOARCH=amd64

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN mkdir /app/cover 

WORKDIR /app/cmd/data-sync-messaging/

RUN go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o /app/cmd/data-sync-messaging/main

FROM gcr.io/distroless/base-debian10

WORKDIR /app/cmd/data-sync-messaging/

COPY --from=build-env /app/cmd/data-sync-messaging /app/cmd/data-sync-messaging

ENTRYPOINT ["./main"]

```
The container can start up, but whenever the executable runs, and we send an http request, it crashes. theses are the logs:

```
%7|1640594810.433|TOPPAR|rdkafka#producer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0]: redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0: public [0] 1 message(s) in xmit queue (1 added from partition queue)
%7|1640594810.433|TOPPAR|rdkafka#producer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0]: redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0: public [0] 1 message(s) queued but broker not up
%7|1640594810.433|STATE|rdkafka#producer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0]: redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0: Broker changed state INIT -> TRY_CONNECT
%7|1640594810.433|UAS|rdkafka#producer-1| [thrd:main]: 1/1 messages were partitioned in topic public
%7|1640594810.433|METADATA|rdkafka#producer-1| [thrd:main]: redpanda.redpanda.svc.cluster.local:9092/bootstrap: 1/1 requested topic(s) seen in metadata
%7|1640594810.433|BROADCAST|rdkafka#producer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0]: Broadcasting state change
%7|1640594810.434|CONNECT|rdkafka#producer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0]: redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0: broker in state TRY_CONNECT connecting
%7|1640594810.434|STATE|rdkafka#producer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0]: redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0: Broker changed state TRY_CONNECT -> CONNECT
%7|1640594810.434|BROADCAST|rdkafka#producer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9092/0]: Broadcasting state change
Segmentation fault (core dumped)

```

The application is supposed to be talking to Kafka API (redpanda), and whenever a communication is attempted, it just crashes. Whenever we don't use distroless images (we're using the regular Golang image), it does work (no crashing, and the application can talk to kafka).
I know this is a huge block of information, and that this issue is super specific, but I really don't know what to do about this, since I've searched online about this A LOT, and tried many different solutions, still doesn't work. Can I get some help on this?

**Comment by jonjohnsonjr** [comment]
Have you tried disabling cgo?

```
CGO_ENABLED=0
```

**Comment by DB185344** [comment]
I've tried, still doesn't work, also our application needs CGO

**Comment by loosebazooka** [comment]
I can't make any recommendations on what tool to use. But can you do analysis on what shared libraries your application requires?

**Comment by DB185344** [comment]
I'm checking with our developer, however, the weird things is that whenever we set the kafka host with ip (instead of DNS) it works, but when we use DNS we can get the error I posted above.

We use internal communication so IPs cannot be used (only DNS)

**Comment by loosebazooka** [comment]
honestly, this just seems like some dns requirement is missing, but it might be up to you to determine what that is?

**Comment by DB185344** [comment]
yeah it's definitely related to golang, for some reason it can't resolve the DNS. this probably isn't the place to ask this question.
