### ISSUE TITLE
Old vulnerable version of `libexpat1` in `python3` image

### ISSUE THREAD

**Issue by paul-gould** [GoogleContainerTools/distroless#968]
The version of `libexpat1` in the `python3` image in gcr.io is still `2.2.10-2` although the version listed in `debian_versions.bzl` is `2.2.10-2+deb11u2`. There may be other libraries that are out of date, but I haven't checked as it was specifically `libexpat1` that was causing a trivy alert.

The version in the `python3-debian11` image is up-to-date, but I haven't yet managed to get my head around how the build and deployment process works, so I can't offer any suggestions as to what's broken. My apologies!

**Comment by loosebazooka** [comment]
which image specifically are you seeing not update to date? if it is debian10, please note that debian10 images have stopped being built for the python, java, and node: see https://github.com/GoogleContainerTools/distroless/blob/main/SUPPORT_POLICY.md

**Comment by paul-gould** [comment]
`gcr.io/distroless/python3` is the out of date one. Given that https://github.com/GoogleContainerTools/distroless/blob/main/README.md states

> Specifying an image without the distribution will currently select `-debian11` images

I'd assumed that this should be up-to-date.

**Comment by loosebazooka** [comment]
K, lemme go take a look.

**Comment by loosebazooka** [comment]
Ah, yeah good catch. Looks like we need to create the manifest list for that image references.

**Comment by loosebazooka** [comment]
Thanks again for identifying this, it should be fixed.

**Comment by paul-gould** [comment]
Yes, confirmed fixed. Thanks for jumping on it so quickly.
