### ISSUE TITLE
Write deb manifest data from the package_manager rule in the built container image somehow

### ISSUE THREAD

**Issue by dlorenc** [GoogleContainerTools/distroless#97]
@mattmoor you had some ideas here I believe?

Basically we need a sharded manifest, where each package we unpack dumps it's version/metadata right?

Where should we stick this?

**Comment by dlorenc** [comment]
cc @r2d4

**Comment by tejal29** [comment]
PR https://github.com/bazelbuild/rules_docker/pull/239 is blocked due to https://github.com/bazelbuild/rules_docker/issues/247

**Comment by tejal29** [comment]
Merged!
