### ISSUE TITLE
NodeJS vulnerable dependencies, any way to remove from image?

### ISSUE THREAD

**Issue by fabiohaertel** [GoogleContainerTools/distroless#979]
Hi

We are using the distroless nodejs image (gcr.io/distroless/nodejs:16) and I have some questions.

The IT security team of my company is using a software called Prisma Cloud to scan docker containers for vulnerabilities.

We managed to remove all vulnerable dependencies from our project, but the nodejs folder inside the distroless image still has vulnerabilities:

Minimatch and Ansi-Regex:
![This is an image](https://i.imgur.com/KwrEP6o.png)

Location of nodejs vulnerable dependencies:
![This is an image](https://i.imgur.com/h7NAfs6.png)
![This is an image](https://i.imgur.com/qUYexTP.png)

As we can see they are all inside the 'nodejs/lib' folder.

How I can I remove those folders from the image?
Can't use the 'rm' command in the Dockerfile because the distroless image doesnt have it.

Thanks.

ps: edited to include inline images

**Comment by loosebazooka** [comment]
I believe the very recently merged https://github.com/GoogleContainerTools/distroless/pull/978 could fix the node issue? Openssl was also just upgraded. The libc6 one is low (and debian has not yet released an update). I would check again in an hour or two once all the images are build and released.

Also, I would very much appreciate if you could include information inline next time. Clicking on imgur links isn't a huge burden, but it's not ideal.

**Comment by loosebazooka** [comment]
Oh I don't know, those are part of the standard node distribution. But maybe @omBratteng who has been doing the node udpates has an opinion here?

**Comment by omBratteng** [comment]
They are from the `npm` module, which IIRC is pretty much unusable, as there is no console. And IIRC, you can't do `require("npm")` to try to access it. But removing it, not sure, I could take a look

**Comment by omBratteng** [comment]
After some digging, the directory `/nodejs/lib/node_modules/npm/` and `/nodejs/lib/node_modules/corepack/` can be removed.
I'm not that familiar with Bazel, so not sure how to do it for the images.
Either running `npm uninstall -g npm corepack` or `rm` on the directories. @loosebazooka could you help?

**Comment by loosebazooka** [comment]
I think you just need to exclude the right path here: https://github.com/GoogleContainerTools/distroless/blob/25bd7b1c9a03c18845f9efdef6dd31fa1b733625/nodejs/BUILD.nodejs#L13

I'll try it out when I'm back at my computer on Monday.

**Comment by omBratteng** [comment]
I opened a draft PR #983, where I excluded that paths, just to check if they build
